# Generated by Django 4.2.10 on 2024-03-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("kitsune_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="to_group",
            field=models.ManyToManyField(blank=True, null=True, to="auth.group"),
        ),
        migrations.AddField(
            model_name="outboxmessage",
            name="to_group",
            field=models.ManyToManyField(blank=True, null=True, to="auth.group"),
        ),
    ]
