# Generated by Django 4.2.10 on 2024-04-18 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitsune_messages", "0002_inboxmessage_to_group_outboxmessage_to_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxmessage",
            name="to_group",
        ),
    ]
