# Generated by Django 5.2.10 on 2026-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitsune_messages', '0003_remove_inboxmessage_to_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
