# Generated by Django 2.2.13 on 2020-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160106_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'in progress'), (2, 'done - fail'), (3, 'done - success')], default=0),
        ),
    ]
