stages:
  - build
  - test
  - push

variables:
  COMPOSE_PROJECT_NAME: "kitsune-${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"

.base:
  tags:
    - shell
    - docker

before_script:
  - docker info

after_script:
  - docker-compose kill

build:
  extends: .base
  stage: build
  script:
    - make build-ci

unittest:
  extends: .base
  stage: test
  script:
    - make test-ci

test js:
  extends: .base
  stage: test
  script:
    - make test-js-ci

lint:
  extends: .base
  stage: test
  script:
    - make lint-ci

push:
  extends: .base
  stage: push
  script:
    - echo "will do the docker hub push here"
