image: docker:stable

stages:
  - build
  - test
  - push

variables:
  COMPOSE_PROJECT_NAME: "kitsune-${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"

before_script:
  - docker info

after_script:
  - docker-compose kill

build:
  tags:
    - docker
  stage: build
  script:
    - env
    - make build-ci

unittest:
  tags:
    - docker
  stage: test
  script:
    - make test-ci

test js:
  tags:
    - docker
  stage: test
  script:
    - make test-js-ci

lint:
  tags:
    - docker
  stage: test
  script:
    - make lint-ci

push:
  only:
    refs:
      - master
      - prod
  tags:
    - meao
  stage: push
  script:
    - echo "will do the docker hub push here"
