# Generated by Django 4.1.7 on 2023-04-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("visible", models.BooleanField(default=False)),
                ("display_order", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Used on the the home page. Must be 484x244.",
                        max_length=250,
                        null=True,
                        upload_to="uploads/products/",
                    ),
                ),
                ("image_offset", models.IntegerField(default=None, editable=False, null=True)),
                (
                    "image_cachebuster",
                    models.CharField(default=None, editable=False, max_length=32, null=True),
                ),
                ("sprite_height", models.IntegerField(default=None, editable=False, null=True)),
                ("display_order", models.IntegerField()),
                ("visible", models.BooleanField(default=False)),
                ("platforms", models.ManyToManyField(to="products.platform")),
                (
                    "image_alternate",
                    models.ImageField(
                        blank=True,
                        help_text="Used everywhere except the home page. Must be 96x96.",
                        max_length=250,
                        null=True,
                        upload_to="uploads/products/",
                    ),
                ),
                ("codename", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(db_index=True, max_length=255)),
                ("min_version", models.FloatField()),
                ("max_version", models.FloatField()),
                ("visible", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-max_version"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=250, null=True, upload_to="uploads/topics/"
                    ),
                ),
                ("display_order", models.IntegerField()),
                ("visible", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="products.topic",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="products.product",
                    ),
                ),
                (
                    "in_aaq",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this topic is shown to users in the AAQ or not.",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "display_order"],
                "unique_together": {("slug", "product")},
            },
        ),
    ]
