# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181001_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codename',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
