# Generated by Django 2.2.13 on 2020-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Used on the the home page. Must be 484x244.', max_length=250, null=True, upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alternate',
            field=models.ImageField(blank=True, help_text='Used everywhere except the home page. Must be 96x96.', max_length=250, null=True, upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploads/topics/'),
        ),
    ]
