# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Used on the the home page. Must be 484x244.', max_length=250, null=True, upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alternate',
            field=models.ImageField(blank=True, help_text='Used everywhere except the home page. Must be 96x96.', max_length=250, null=True, upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploads/topics/'),
        ),
    ]
