# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_codename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_alternate',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='The largest this image displays is 80x80 so the ideal image size is 160x160 to account for retina displays', max_length=250, null=True, upload_to=b'uploads/products/'),
        ),
    ]
