# Generated by Django 4.1.7 on 2023-03-31 16:04

from django.db import migrations
import kitsune.sumo.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_squashed_0005_auto_20200629_0826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=kitsune.sumo.fields.ImagePlusField(
                blank=True,
                help_text="Used on the the home page. Must be 484x244.",
                max_length=250,
                null=True,
                upload_to="uploads/products/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_alternate",
            field=kitsune.sumo.fields.ImagePlusField(
                blank=True,
                help_text="Used everywhere except the home page. Must be 96x96.",
                max_length=250,
                null=True,
                upload_to="uploads/products/",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=kitsune.sumo.fields.ImagePlusField(
                blank=True, max_length=250, null=True, upload_to="uploads/topics/"
            ),
        ),
    ]
