# Generated by Django 4.2.11 on 2024-06-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_and_topic_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sprite_height",
        ),
    ]
