# Generated by Django 4.2.11 on 2024-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_sprite_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="products",
            field=models.ManyToManyField(related_name="m2m_topics", to="products.product"),
        ),
    ]
