# Generated by Django 4.2.11 on 2024-06-06 06:32

import copy

from django.db import migrations


def copy_product_to_products(apps, schema_editor):
    Topic = apps.get_model("products", "Topic")
    for topic in Topic.objects.all():
        if topic.product:
            topic.products.add(topic.product)


def m2m_backwards(apps, schema_editor): ...


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_topic_products"),
    ]

    operations = [migrations.RunPython(copy_product_to_products, m2m_backwards)]
