# Generated by Django 4.2.11 on 2024-06-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20240606_0632"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicSlugHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_history",
                        to="products.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
