# Generated by Django 4.2.11 on 2024-07-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_auto_20240624_0616"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
