# Generated by Django 4.2.11 on 2024-07-01 03:07

from django.db import migrations


def archive_old_topics(apps, schema_editor):
    Topic = apps.get_model("products", "Topic")
    TopicSlugHistory = apps.get_model("products", "TopicSlugHistory")

    for topic_slug in TopicSlugHistory.objects.all():
        try:
            old_topic = Topic.objects.get(slug=topic_slug.slug, product=topic_slug.topic.product)
            old_topic.is_archived = True
            old_topic.save()
        except Topic.DoesNotExist:
            pass


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_is_archived_topic_is_archived"),
    ]

    operations = [migrations.RunPython(archive_old_topics, backwards)]
