# Generated by Django 4.2.14 on 2024-07-18 06:34

from django.db import migrations

NEW_TOPICS_DATA = [
    {
        "title": "Backup, recovery, and sync",
        "slug": "backup-recovery-and-sync",
        "description": "Learn how to back up, recover, and sync your data across different platforms and devices.",
        "products": ["firefox", "mobile", "ios", "relay", "mozilla-account"],
        "subtopics": [
            {
                "title": "Backup data",
                "slug": "backup-data",
                "description": "Discover methods to securely back up your important data.",
                "products": ["firefox", "mobile", "ios", "mozilla-account"],
            },
            {
                "title": "Recover data",
                "slug": "recover-data",
                "description": "Follow steps to recover lost or deleted data.",
                "products": ["firefox", "mobile", "ios", "mozilla-account"],
            },
            {
                "title": "Sync data",
                "slug": "sync-data",
                "description": "Sync your data across multiple devices seamlessly.",
                "products": ["firefox", "mobile", "ios", "mozilla-account"],
            },
        ],
    },
    {
        "title": "Browse",
        "slug": "browse",
        "description": "Explore how to browse the web efficiently and effectively.",
        "products": ["firefox", "mobile", "ios", "pocket", "hubs"],
        "subtopics": [
            {
                "title": "Tabs",
                "slug": "tabs",
                "description": "Organize and manage your tabs for better browsing.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "History",
                "slug": "history",
                "description": "View and manage your browsing history.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "Bookmarks",
                "slug": "bookmarks",
                "description": "Save and organize your favorite web pages with bookmarks.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "Multimedia",
                "slug": "multimedia",
                "description": "Play and manage multimedia content on the web.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "Links",
                "slug": "links",
                "description": "Handle web links efficiently.",
                "products": ["firefox", "mobile", "ios"],
            },
        ],
    },
    {
        "title": "Performance and connectivity",
        "slug": "performance-and-connectivity",
        "description": "Optimize performance and connectivity for a smoother experience.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "pocket",
            "mdn-plus",
            "focus-firefox",
            "thunderbird",
        ],
        "subtopics": [
            {
                "title": "Crashing and slow performance",
                "slug": "crashing-and-slow-performance",
                "description": "Troubleshoot issues with crashing or slow performance.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "thunderbird",
                ],
            },
            {
                "title": "Site breakages",
                "slug": "site-breakages",
                "description": "Resolve problems when websites don’t load or function correctly.",
                "products": ["firefox", "mobile", "ios", "focus-firefox"],
            },
        ],
    },
    {
        "title": "Accessibility",
        "slug": "accessibility",
        "description": "Enhance accessibility features for better usability.",
        "products": ["firefox", "mobile", "ios", "pocket", "thunderbird", "mozilla-account"],
        "subtopics": [],
    },
    {
        "title": "Download and save",
        "slug": "download-and-save",
        "description": "Learn how to download and save files from the web.",
        "products": ["firefox", "mobile", "ios", "pocket", "mdn-plus"],
        "subtopics": [
            {
                "title": "Downloads",
                "slug": "downloads",
                "description": "Manage and troubleshoot your downloads.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
            {
                "title": "Save content",
                "slug": "save-content",
                "description": "Save web content for offline use.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
        ],
    },
    {
        "title": "Search, tag, and share",
        "slug": "search-tag-and-share",
        "description": "Search, tag and share content efficiently.",
        "products": ["firefox", "mobile", "ios", "pocket", "focus-firefox", "thunderbird"],
        "subtopics": [
            {
                "title": "Search",
                "slug": "search",
                "description": "Find information quickly and easily.",
                "products": ["firefox", "mobile", "ios", "pocket", "focus-firefox", "thunderbird"],
            },
            {
                "title": "Tags",
                "slug": "tags",
                "description": "Organize your content using tags.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
            {
                "title": "Share content",
                "slug": "share-content",
                "description": "Share your favorite content with others.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
        ],
    },
    {
        "title": "Installation and updates",
        "slug": "installation-and-updates",
        "description": "Install and update your software to the latest version.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "pocket",
            "focus-firefox",
            "firefox-enterprise",
            "thunderbird",
        ],
        "subtopics": [
            {
                "title": "Install",
                "slug": "install",
                "description": "Step-by-step guide to installing the software.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                ],
            },
            {
                "title": "Update",
                "slug": "update",
                "description": "Keep your software up to date with the latest features and improvements.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                ],
            },
        ],
    },
    {
        "title": "Settings",
        "slug": "settings",
        "description": "Customize your settings to enhance your experience.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "pocket",
            "mdn-plus",
            "focus-firefox",
            "firefox-enterprise",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Import and export settings",
                "slug": "import-and-export-settings",
                "description": "Learn how to import and export settings for easy setup.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Customization",
                "slug": "customization",
                "description": "Customize the appearance and functionality to suit your preferences.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Autofill",
                "slug": "autofill",
                "description": "Save time by using autofill for forms and other fields.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Languages",
                "slug": "languages",
                "description": "Change and manage the languages used in your software.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "relay",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Add-ons, extensions, and themes",
                "slug": "add-ons-extensions-and-themes",
                "description": "Enhance your software with add-ons, extensions, and themes.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "relay",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "description": "Protect your privacy and secure your data.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "pocket",
            "focus-firefox",
            "firefox-enterprise",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Tracking protection",
                "slug": "tracking-protection",
                "description": "Enable tracking protection to enhance your privacy.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Encryption",
                "slug": "encryption",
                "description": "Secure your data with encryption.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Masking",
                "slug": "masking",
                "description": "Mask your online activity for better privacy.",
                "products": ["firefox", "mobile", "ios", "relay", "mozilla-account"],
            },
            {
                "title": "Security",
                "slug": "security",
                "description": "Keep your software secure with these tips.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "relay",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Passwords and sign in",
        "slug": "passwords-and-sign-in",
        "description": "Manage your passwords and sign-in securely.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "mdn-plus",
            "hubs",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Save passwords",
                "slug": "save-passwords",
                "description": "Save your passwords for easy sign-in.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Reset passwords",
                "slug": "reset-passwords",
                "description": "Reset your passwords when you forget them.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Two-factor authentication",
                "slug": "two-factor-authentication",
                "description": "Add an extra layer of security with two-factor authentication.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "mozilla-account",
                ],
            },
            {
                "title": "Primary password",
                "slug": "primary-password",
                "description": "Set up a primary password to secure your saved passwords.",
                "products": ["firefox", "mobile", "ios", "firefox-private-network-vpn"],
            },
        ],
    },
    {
        "title": "Accounts",
        "slug": "accounts",
        "description": "Manage your accounts and profiles.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "pocket",
            "hubs",
            "firefox-enterprise",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Profiles",
                "slug": "profiles",
                "description": "Create and manage different profiles in your software.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "pocket",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Account management",
                "slug": "account-management",
                "description": "Manage your account settings and preferences.",
                "products": [
                    "firefox-private-network-vpn",
                    "pocket",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Account recovery",
                "slug": "account-recovery",
                "description": "Recover your account if you encounter issues.",
                "products": [
                    "firefox-private-network-vpn",
                    "pocket",
                    "firefox-enterprise",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Billing and subscriptions",
        "slug": "billing-and-subscriptions",
        "description": "Manage your billing information and subscriptions.",
        "products": [
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "pocket",
            "mdn-plus",
            "hubs",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Manage billing",
                "slug": "manage-billing",
                "description": "Update and manage your billing information.",
                "products": [
                    "firefox-private-network-vpn",
                    "relay",
                    "pocket",
                    "mdn-plus",
                    "hubs",
                    "mozilla-account",
                ],
            },
            {
                "title": "Manage subscriptions",
                "slug": "manage-subscriptions",
                "description": "Manage your subscriptions and payment methods.",
                "products": [
                    "firefox-private-network-vpn",
                    "relay",
                    "pocket",
                    "mdn-plus",
                    "hubs",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Email and messaging",
        "slug": "email-and-messaging",
        "description": "Learn how to manage your emails and messaging services.",
        "products": ["thunderbird", "relay"],
        "subtopics": [
            {
                "title": "Contacts",
                "slug": "contacts",
                "description": "Manage your email contacts efficiently.",
                "products": ["thunderbird"],
            },
            {
                "title": "Junk email and spam",
                "slug": "junk-mail-and-spam",
                "description": "Identify and manage junk email and spam.",
                "products": ["thunderbird"],
            },
            {
                "title": "Instant messaging",
                "slug": "instant-messaging",
                "description": "Set up and use instant messaging services.",
                "products": ["thunderbird"],
            },
            {
                "title": "Attachments",
                "slug": "attachments",
                "description": "Handle email attachments effectively.",
                "products": ["thunderbird"],
            },
            {
                "title": "Send and receive email",
                "slug": "send-and-receive-email",
                "description": "Learn how to send and receive emails properly.",
                "products": ["thunderbird", "relay"],
            },
            {
                "title": "Import and export email",
                "slug": "import-and-export-email",
                "description": "Import and export your emails for backup or transfer.",
                "products": ["thunderbird"],
            },
            {
                "title": "Calendar",
                "slug": "calendar",
                "description": "Manage your calendar events and schedules.",
                "products": ["thunderbird"],
            },
        ],
    },
]


def create_new_taxonomy_topics(apps, schema_editor):
    Topic = apps.get_model("products", "Topic")
    Product = apps.get_model("products", "Product")
    ProductTopic = apps.get_model("products", "ProductTopic")

    for topic_data in NEW_TOPICS_DATA:
        new_topic = Topic.objects.create(
            slug=topic_data["slug"],
            title=topic_data["title"],
            description=topic_data["description"],
            display_order=50,
            visible=True,
        )

        for product_slug in topic_data["products"]:
            try:
                product = Product.objects.get(slug=product_slug)
            except Product.DoesNotExist:
                continue
            else:
                ProductTopic.objects.get_or_create(product=product, topic=new_topic)

        for subtopic_data in topic_data["subtopics"]:
            new_subtopic = Topic.objects.create(
                slug=subtopic_data["slug"],
                title=subtopic_data["title"],
                description=subtopic_data["description"],
                visible=True,
                parent=new_topic,
                display_order=60,
            )

            for product_slug in subtopic_data["products"]:
                try:
                    product = Product.objects.get(slug=product_slug)
                except Product.DoesNotExist:
                    continue
                else:
                    ProductTopic.objects.get_or_create(product=product, topic=new_subtopic)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_topic_product"),
    ]

    operations = [migrations.RunPython(create_new_taxonomy_topics, backwards)]
