# Generated by Django 4.2.14 on 2024-07-18 06:34

from django.db import migrations

NEW_TOPICS_DATA = [
    {
        "title": "Backup, recovery, and sync",
        "slug": "backup-recovery-and-sync",
        "description": "Sync your data across different platforms and devices, backup what’s important, and recover it if it’s lost.",
        "products": ["firefox", "mobile", "ios", "relay", "mozilla-account"],
        "subtopics": [
            {
                "title": "Backup data",
                "slug": "backup-data",
                "description": "From passwords to bookmarks, discover ways to back up your important data.",
                "products": ["firefox", "mobile", "ios", "mozilla-account"],
            },
            {
                "title": "Recover data",
                "slug": "recover-data",
                "description": "Learn how to recover your lost data.",
                "products": ["firefox", "mobile", "ios", "mozilla-account"],
            },
            {
                "title": "Sync data",
                "slug": "sync-data",
                "description": "Sync your data across different platforms and devices.",
                "products": ["firefox", "mobile", "ios", "mozilla-account"],
            },
        ],
    },
    {
        "title": "Browse",
        "slug": "browse",
        "description": "Explore how to navigate the web efficiently and effectively with Mozilla’s products.",
        "products": ["firefox", "mobile", "ios", "pocket", "hubs"],
        "subtopics": [
            {
                "title": "Tabs",
                "slug": "tabs",
                "description": "Organize and manage your tabs for better browsing.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "History",
                "slug": "history",
                "description": "View and manage your browsing history.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "Bookmarks",
                "slug": "bookmarks",
                "description": "Save and organize your favorite web content with bookmarks.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "Multimedia",
                "slug": "multimedia",
                "description": "Everything you need to know about audio, video, images, and more.",
                "products": ["firefox", "mobile", "ios"],
            },
            {
                "title": "Links",
                "slug": "links",
                "description": "Use web links in Mozilla’s products.",
                "products": ["firefox", "mobile", "ios"],
            },
        ],
    },
    {
        "title": "Performance and connectivity",
        "slug": "performance-and-connectivity",
        "description": "Deal with error messages, crashing applications, connectivity issues, and slow performance.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "pocket",
            "mdn-plus",
            "focus-firefox",
            "thunderbird",
        ],
        "subtopics": [
            {
                "title": "Crashing and slow performance",
                "slug": "crashing-and-slow-performance",
                "description": "Troubleshoot issues with app crashes or slow performance.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "thunderbird",
                ],
            },
            {
                "title": "Site breakages",
                "slug": "site-breakages",
                "description": "Resolve problems when websites don’t load or function correctly.",
                "products": ["firefox", "mobile", "ios", "focus-firefox"],
            },
        ],
    },
    {
        "title": "Accessibility",
        "slug": "accessibility",
        "description": "Learn about Mozilla products’ accessibility features and settings for better usability.",
        "products": ["firefox", "mobile", "ios", "pocket", "thunderbird", "mozilla-account"],
        "subtopics": [],
    },
    {
        "title": "Download and save",
        "slug": "download-and-save",
        "description": "Manage your downloaded files and saved content",
        "products": ["firefox", "mobile", "ios", "pocket", "mdn-plus"],
        "subtopics": [
            {
                "title": "Downloads",
                "slug": "downloads",
                "description": "Manage and troubleshoot your downloads.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
            {
                "title": "Save content",
                "slug": "save-content",
                "description": "Save your favorite content for later.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
        ],
    },
    {
        "title": "Search, tag, and share",
        "slug": "search-tag-and-share",
        "description": "Learn about search functionality and how to organize or share content in Mozilla products.",
        "products": ["firefox", "mobile", "ios", "pocket", "focus-firefox", "thunderbird"],
        "subtopics": [
            {
                "title": "Search",
                "slug": "search",
                "description": "Find information quickly and easily.",
                "products": ["firefox", "mobile", "ios", "pocket", "focus-firefox", "thunderbird"],
            },
            {
                "title": "Tags",
                "slug": "tags",
                "description": "Categorize and organize efficiently with tags.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
            {
                "title": "Share content",
                "slug": "share-content",
                "description": "Learn how to share links, content, messages, and more.",
                "products": ["firefox", "mobile", "ios", "pocket"],
            },
        ],
    },
    {
        "title": "Installation and updates",
        "slug": "installation-and-updates",
        "description": "Learn how to install your favorite Mozilla products and keep them updated.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "pocket",
            "focus-firefox",
            "firefox-enterprise",
            "thunderbird",
        ],
        "subtopics": [
            {
                "title": "Install",
                "slug": "install",
                "description": "Learn about how to install Mozilla’s products on your devices.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                ],
            },
            {
                "title": "Update",
                "slug": "update",
                "description": "Keep the Mozilla products you use up to date with the latest features and improvements.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                ],
            },
        ],
    },
    {
        "title": "Settings",
        "slug": "settings",
        "description": "Manage and customize your product experience with settings, add-ons, and more.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "pocket",
            "mdn-plus",
            "focus-firefox",
            "firefox-enterprise",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Import and export settings",
                "slug": "import-and-export-settings",
                "description": "Learn how to import and export product settings for easy setup and migration.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Customization",
                "slug": "customization",
                "description": "Customize product appearance and functionality to suit your preferences.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Autofill",
                "slug": "autofill",
                "description": "Automatically fill your personal information into form fields and more.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Languages",
                "slug": "languages",
                "description": "Change and manage language settings in Mozilla’s products.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "relay",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Add-ons, extensions, and themes",
                "slug": "add-ons-extensions-and-themes",
                "description": "Enhance product functionality with add-ons, extensions, and themes.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "relay",
                    "pocket",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "description": "Learn how to protect your privacy and secure your data.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "pocket",
            "focus-firefox",
            "firefox-enterprise",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Tracking protection",
                "slug": "tracking-protection",
                "description": "Enable tracking protection to enhance your privacy.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Encryption",
                "slug": "encryption",
                "description": "Use encryption features to keep yourself and your data secure.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Masking",
                "slug": "masking",
                "description": "Mask your email and phone number to better protect your privacy.",
                "products": ["firefox", "mobile", "ios", "relay", "mozilla-account"],
            },
            {
                "title": "Security",
                "slug": "security",
                "description": "Keep yourself secure online.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "relay",
                    "focus-firefox",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Passwords and sign in",
        "slug": "passwords-and-sign-in",
        "description": "Manage your passwords and securely access your accounts.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "mdn-plus",
            "hubs",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Save passwords",
                "slug": "save-passwords",
                "description": "Save your passwords for easy sign-in.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Reset passwords",
                "slug": "reset-passwords",
                "description": "Reset your passwords when you forget them.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Two-factor authentication",
                "slug": "two-factor-authentication",
                "description": "Use two-factor authentication to add an extra layer of security when signing in.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "firefox-private-network-vpn",
                    "mozilla-account",
                ],
            },
            {
                "title": "Primary password",
                "slug": "primary-password",
                "description": "Set up a primary password to secure your saved passwords.",
                "products": ["firefox", "mobile", "ios", "firefox-private-network-vpn"],
            },
        ],
    },
    {
        "title": "Accounts",
        "slug": "accounts",
        "description": "Manage your accounts and profiles for Mozilla’s products and services.",
        "products": [
            "firefox",
            "mobile",
            "ios",
            "firefox-private-network-vpn",
            "pocket",
            "hubs",
            "firefox-enterprise",
            "thunderbird",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Profiles",
                "slug": "profiles",
                "description": "Create and manage user profiles.",
                "products": [
                    "firefox",
                    "mobile",
                    "ios",
                    "pocket",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Account management",
                "slug": "account-management",
                "description": "Manage your account settings and preferences.",
                "products": [
                    "firefox-private-network-vpn",
                    "pocket",
                    "firefox-enterprise",
                    "thunderbird",
                    "mozilla-account",
                ],
            },
            {
                "title": "Account recovery",
                "slug": "account-recovery",
                "description": "Recover your account if you lose access to it or encounter issues.",
                "products": [
                    "firefox-private-network-vpn",
                    "pocket",
                    "firefox-enterprise",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Billing and subscriptions",
        "slug": "billing-and-subscriptions",
        "description": "Manage your subscriptions and payment details for Mozilla’s premium products.",
        "products": [
            "firefox-private-network-vpn",
            "relay",
            "monitor",
            "pocket",
            "mdn-plus",
            "hubs",
            "mozilla-account",
        ],
        "subtopics": [
            {
                "title": "Manage billing",
                "slug": "manage-billing",
                "description": "Manage your payment details and billing information.",
                "products": [
                    "firefox-private-network-vpn",
                    "relay",
                    "pocket",
                    "mdn-plus",
                    "hubs",
                    "mozilla-account",
                ],
            },
            {
                "title": "Manage subscriptions",
                "slug": "manage-subscriptions",
                "description": "Manage your subscriptions to Mozilla’s premium products and services.",
                "products": [
                    "firefox-private-network-vpn",
                    "relay",
                    "pocket",
                    "mdn-plus",
                    "hubs",
                    "mozilla-account",
                ],
            },
        ],
    },
    {
        "title": "Email and messaging",
        "slug": "email-and-messaging",
        "description": "Read, send, and manage your emails and messages.",
        "products": ["thunderbird", "relay"],
        "subtopics": [
            {
                "title": "Contacts",
                "slug": "contacts",
                "description": "Manage your email contacts.",
                "products": ["thunderbird"],
            },
            {
                "title": "Junk email and spam",
                "slug": "junk-mail-and-spam",
                "description": "Identify and manage junk email and spam.",
                "products": ["thunderbird"],
            },
            {
                "title": "Instant messaging",
                "slug": "instant-messaging",
                "description": "Features and functionality to use with instant messaging.",
                "products": ["thunderbird"],
            },
            {
                "title": "Attachments",
                "slug": "attachments",
                "description": "Learn how to use and manage email attachments.",
                "products": ["thunderbird"],
            },
            {
                "title": "Send and receive email",
                "slug": "send-and-receive-email",
                "description": "Everything you need to know about sending and receiving emails.",
                "products": ["thunderbird", "relay"],
            },
            {
                "title": "Import and export email",
                "slug": "import-and-export-email",
                "description": "Import and export your emails for backup or transfer.",
                "products": ["thunderbird"],
            },
            {
                "title": "Calendar",
                "slug": "calendar",
                "description": "Manage your calendar events and schedules.",
                "products": ["thunderbird"],
            },
        ],
    },
]


def create_new_taxonomy_topics(apps, schema_editor):
    Topic = apps.get_model("products", "Topic")
    Product = apps.get_model("products", "Product")
    ProductTopic = apps.get_model("products", "ProductTopic")

    for topic_data in NEW_TOPICS_DATA:
        new_topic = Topic.objects.create(
            slug=topic_data["slug"],
            title=topic_data["title"],
            description=topic_data["description"],
            display_order=50,
            visible=True,
        )

        for product_slug in topic_data["products"]:
            try:
                product = Product.objects.get(slug=product_slug)
            except Product.DoesNotExist:
                continue
            else:
                ProductTopic.objects.get_or_create(product=product, topic=new_topic)

        for subtopic_data in topic_data["subtopics"]:
            new_subtopic = Topic.objects.create(
                slug=subtopic_data["slug"],
                title=subtopic_data["title"],
                description=subtopic_data["description"],
                visible=True,
                parent=new_topic,
                display_order=60,
            )

            for product_slug in subtopic_data["products"]:
                try:
                    product = Product.objects.get(slug=product_slug)
                except Product.DoesNotExist:
                    continue
                else:
                    ProductTopic.objects.get_or_create(product=product, topic=new_subtopic)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_topic_product"),
    ]

    operations = [migrations.RunPython(create_new_taxonomy_topics, backwards)]
