# Generated by Django 4.2.14 on 2024-07-22 04:49

from django.db import migrations

TAXONOMY_MAPPING = [
    {
        "old_title": "Fix problems with websites",
        "old_slug": "websites",
        "title": "Site breakages",
        "slug": "site-breakages",
        "parent_topic_slug": "performance-and-connectivity",
    },
    {
        "old_title": "Firefox crashes",
        "old_slug": "crashing",
        "title": "Crashing and slow performance",
        "slug": "crashing-and-slow-performance",
        "parent_topic_slug": "performance-and-connectivity",
    },
    {
        "old_title": "Unblock Firefox from connecting to the internet",
        "old_slug": "unblock-firefox-connecting-internet",
        "title": "Performance and connectivity",
        "slug": "performance-and-connectivity",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Firefox won't save settings or remember information",
        "old_slug": "firefox-wont-save-settings-or-remember-information",
        "title": "Settings",
        "slug": "settings",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Problems with add-ons, plugins or unwanted software",
        "old_slug": "problems-add-ons-plugins-or-unwanted-software",
        "title": "Add-ons, extensions, and themes",
        "slug": "add-ons-extensions-and-themes",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Videos, sound, pictures and animations don't work",
        "old_slug": "videos-sound-pictures-and-animations-dont-work",
        "title": "Multimedia",
        "slug": "multimedia",
        "parent_topic_slug": "browse",
    },
    {
        "old_title": "Basic browsing",
        "old_slug": "basic-browsing-firefox",
        "title": "Browse",
        "slug": "browse",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Basic browsing",
        "old_slug": "basic-browsing-firefox-android",
        "title": "Browse",
        "slug": "browse",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Basic browsing",
        "old_slug": "basic-browsing-firefox-ios",
        "title": "Browse",
        "slug": "browse",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Bookmarks and Tab",
        "old_slug": "bookmarks",
        "title": "Bookmarks",
        "slug": "bookmarks",
        "parent_topic_slug": "browse",
    },
    {
        "old_title": "Bookmarks",
        "old_slug": "back-up-bookmarks",
        "title": "Bookmarks",
        "slug": "bookmarks",
        "parent_topic_slug": "browse",
    },
    {
        "old_title": "Bookmarks and Tabs",
        "old_slug": "bookmarks-and-tabs-firefox-ios",
        "title": "Bookmarks",
        "slug": "bookmarks",
        "parent_topic_slug": "browse",
    },
    {
        "old_title": "Reader View and List",
        "old_slug": "reader-view-and-list",
        "title": "Browse",
        "slug": "browse",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Install and update",
        "old_slug": "install-and-update",
        "title": "Installation and updates",
        "slug": "installation-and-updates",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Sync and save",
        "old_slug": "sync-and-save",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Firefox Sync settings",
        "old_slug": "sync",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Customize settings and preferences",
        "old_slug": "customize-settings-and-preferences",
        "title": "Settings",
        "slug": "settings",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Import settings from other browsers",
        "old_slug": "import-settings-other-browsers-firefox",
        "title": "Import and export settings",
        "slug": "import-and-export-settings",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Video, audio and interactive settings",
        "old_slug": "video-audio-and-file-settings-Firefox",
        "title": "Multimedia",
        "slug": "multimedia",
        "parent_topic_slug": "browse",
    },
    {
        "old_title": "Display and appearance",
        "old_slug": "customize-firefox-appearance",
        "title": "Customization",
        "slug": "customization",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Install and manage add-ons",
        "old_slug": "install-and-manage-add-ons",
        "title": "Add-ons, extensions, and themes",
        "slug": "add-ons-extensions-and-themes",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Search",
        "old_slug": "ios-search",
        "title": "Search",
        "slug": "search",
        "parent_topic_slug": "search-tag-and-share",
    },
    {
        "old_title": "Protect your privacy",
        "old_slug": "protect-your-privacy",
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Cookies and cache",
        "old_slug": "cookies",
        "title": "Tracking protection",
        "slug": "tracking-protection",
        "parent_topic_slug": "privacy-and-security",
    },
    {
        "old_title": "Privacy and security",
        "old_slug": "privacy-and-security",
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Tracking protection",
        "old_slug": "tracking-protection",
        "title": "Tracking protection",
        "slug": "tracking-protection",
        "parent_topic_slug": "privacy-and-security",
    },
    {
        "old_title": "Firefox for families",
        "old_slug": "firefox-for-families",
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Use extension and add-ons",
        "old_slug": "use-extensions-and-add-ons",
        "title": "Add-ons, extensions, and themes",
        "slug": "add-ons-extensions-and-themes",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Stay connected",
        "old_slug": "stay-connected",
        "title": "Performance and connectivity",
        "slug": "performance-and-connectivity",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Personalize your experience",
        "old_slug": "personalize-your-experience",
        "title": "Customization",
        "slug": "customization",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Back up your data",
        "old_slug": "back-up-your-data",
        "title": "Backup data",
        "slug": "backup-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Profile",
        "old_slug": "back-up-profile",
        "title": "Account management",
        "slug": "account-management",
        "parent_topic_slug": "accounts",
    },
    {
        "old_title": "Sync",
        "old_slug": "setup-sync",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Sync and save",
        "old_slug": "save-share-and-sync-firefox-android",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Sync, share and save",
        "old_slug": "sync-share-save",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Sync and save",
        "old_slug": "sync-and-save",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Firefox Sync",
        "old_slug": "sync",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Sync and save",
        "old_slug": "save-and-share-firefox-ios",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Sync devices & services",
        "old_slug": "sync-devices-services",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Sync",
        "old_slug": "sync-preview",
        "title": "Sync data",
        "slug": "sync-data",
        "parent_topic_slug": "backup-recovery-and-sync",
    },
    {
        "old_title": "Privacy and security settings",
        "old_slug": "privacy-and-security-settings",
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Passwords, forms and search",
        "old_slug": "passwords-forms-and-search",
        "title": "Passwords and sign in",
        "slug": "passwords-and-sign-in",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Thunderbird controls and buttons",
        "old_slug": "thunderbird-controls-and-buttons",
        "title": "Settings",
        "slug": "settings",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Calendar",
        "old_slug": "calendar",
        "title": "Calendar",
        "slug": "calendar",
        "parent_topic_slug": "email-and-messaging",
    },
    {
        "old_title": "Thunderbird versions and languages",
        "old_slug": "thunderbird-versions-and-languages",
        "title": "Settings",
        "slug": "settings",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Copy your personal information from one Thunderbird to another",
        "old_slug": "copy-your-personal-information-one-thunderbird-another",
        "title": "Import and export email",
        "slug": "import-and-export-email",
        "parent_topic_slug": "email-and-messaging",
    },
    {
        "old_title": "Emails",
        "old_slug": "emails",
        "title": "Email and messaging",
        "slug": "email-and-messaging",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Set up email",
        "old_slug": "set-up-email-thunderbird",
        "title": "Account management",
        "slug": "account-management",
        "parent_topic_slug": "accounts",
    },
    {
        "old_title": "Read, send and organize emails",
        "old_slug": "read-send-and-organize-emails",
        "title": "Send and receive email",
        "slug": "send-and-receive-email",
        "parent_topic_slug": "email-and-messaging",
    },
    {
        "old_title": "News Feeds (RSS), Blogs and Social",
        "old_slug": "news-feeds-rss-blogs-and-social-thunderbird",
        "title": "Settings",
        "slug": "settings",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Contacts",
        "old_slug": "contacts-thunderbird",
        "title": "Contacts",
        "slug": "contacts",
        "parent_topic_slug": "email-and-messaging",
    },
    {
        "old_title": "Accounts & Sign-in",
        "old_slug": "accounts",
        "title": "Accounts",
        "slug": "accounts",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Billing & Payments",
        "old_slug": "payments",
        "title": "Manage billing",
        "slug": "manage-billing",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Subscriptions & billing",
        "old_slug": "subscriptions-billing",
        "title": "Manage subscriptions",
        "slug": "manage-subscriptions",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Manage subscriptions",
        "old_slug": "manage-subscriptions",
        "title": "Manage subscriptions",
        "slug": "manage-subscriptions",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Billing & Payments",
        "old_slug": "subscriptions-and-payments",
        "title": "Manage billing",
        "slug": "manage-billing",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Services and subscriptions",
        "old_slug": "services-and-subscriptions",
        "title": "Manage subscriptions",
        "slug": "manage-subscriptions",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Connectivity",
        "old_slug": "connectivity",
        "title": "Performance and connectivity",
        "slug": "performance-and-connectivity",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Your Pocket Account",
        "old_slug": "your-pocket-account",
        "title": "Accounts",
        "slug": "accounts",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Pocket Premium",
        "old_slug": "pocket-premium",
        "title": "Manage subscriptions",
        "slug": "manage-subscriptions",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Pocket Browser Extensions",
        "old_slug": "pocket-browser-extensions",
        "title": "Add-ons, extensions, and themes",
        "slug": "add-ons-extensions-and-themes",
        "parent_topic_slug": "settings",
    },
    {
        "old_title": "Free email masking",
        "old_slug": "free-email-masking",
        "title": "Masking",
        "slug": "masking",
        "parent_topic_slug": "privacy-and-security",
    },
    {
        "old_title": "Premium email masking",
        "old_slug": "premium-email-masking",
        "title": "Masking",
        "slug": "masking",
        "parent_topic_slug": "privacy-and-security",
    },
    {
        "old_title": "Premium phone masking",
        "old_slug": "premium-phone-masking",
        "title": "Masking",
        "slug": "masking",
        "parent_topic_slug": "privacy-and-security",
    },
    {
        "old_title": "Accounts & Sign-in",
        "old_slug": "accounts-and-login",
        "title": "Accounts",
        "slug": "accounts",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Accounts",
        "old_slug": "accounts",
        "title": "Accounts",
        "slug": "accounts",
        "parent_topic_slug": "",
    },
    {
        "old_title": "Billing & Payments",
        "old_slug": "billing-payments",
        "title": "Manage billing",
        "slug": "manage-billing",
        "parent_topic_slug": "billing-and-subscriptions",
    },
    {
        "old_title": "Monitor",
        "old_slug": "monitoring",
        "title": "Privacy and security",
        "slug": "privacy-and-security",
        "parent_topic_slug": "",
    },
]


def migrate_topics(apps, schema_editor):
    """Migrate topics to the new taxonomy."""

    Topic = apps.get_model("products", "Topic")
    Product = apps.get_model("products", "Product")
    TopicSlugHistory = apps.get_model("products", "TopicSlugHistory")
    ProductTopic = apps.get_model("products", "ProductTopic")

    # Promote topics for the community product to the new taxonomy
    try:
        product = Product.objects.get(slug="contributor")
    except Product.DoesNotExist:
        ...
    else:
        topics = Topic.objects.filter(product=product)

        for topic in topics:
            topic.products.remove(product)
            topic.products.add(product)

    for entry in TAXONOMY_MAPPING:
        old_topics = Topic.objects.filter(slug=entry["old_slug"], product__isnull=False)
        new_topic = Topic.objects.get(slug=entry["slug"], product__isnull=True)

        # we may have a list of topics with the same slug
        for old_topic in old_topics:
            product = old_topic.product
            if not ProductTopic.objects.filter(product=product, topic=new_topic).exists():
                ProductTopic.objects.create(product=product, topic=new_topic)

            # Migrate KB
            documents = old_topic.document_set.all()
            for document in documents:
                document.topics.add(new_topic)
                document.topics.remove(old_topic)
            # Migrate AAQ
            if old_topic.questions.exists():
                for question in old_topic.questions.all():
                    question.topic = new_topic
                    question.save()

            if product.visible:
                topic_slug, created = TopicSlugHistory.objects.get_or_create(
                    slug=entry["old_slug"], defaults={"topic": new_topic}
                )
                if not created:
                    topic_slug.topic = new_topic
                    topic_slug.save()

            # Archive the old topic
            old_topic.is_archived = True
            old_topic.save()


def backwards(apps, schema_editor): ...


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_auto_20240718_0634"),
    ]

    operations = [migrations.RunPython(migrate_topics, backwards)]
