# Generated by Django 4.2.14 on 2024-07-24 09:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("products", "0014_auto_20240718_0634"),
    ]

    operations = [
        migrations.CreateModel(
            name="SumoPlaceholderPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SingleProductIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("search", wagtail.blocks.StructBlock([])),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=True
                                            ),
                                        ),
                                        ("link", wagtail.blocks.URLBlock(required=True)),
                                        (
                                            "type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("Community", "Community"),
                                                    ("Paid", "Paid"),
                                                    ("Other", "Other"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("featured_articles", wagtail.blocks.StructBlock([])),
                            ("frequent_topics", wagtail.blocks.StructBlock([])),
                        ]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_index",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Single Product Index",
                "verbose_name_plural": "Single Product Indexes",
            },
            bases=("wagtailcore.page",),
        ),
    ]
