# Generated by Django 4.2.14 on 2024-08-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_topic_in_nav_alter_topic_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["title", "display_order"]},
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="topic",
            name="product",
        ),
    ]
