# Generated by Django 4.2.16 on 2024-09-06 13:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("products", "0017_alter_topic_options_alter_topic_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SumoPlaceholderPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SingleProductIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("search", wagtail.blocks.StructBlock([])),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "headline",
                                            wagtail.blocks.CharBlock(
                                                max_length=255, required=True
                                            ),
                                        ),
                                        ("details", wagtail.blocks.RichTextBlock(required=True)),
                                        ("link", wagtail.blocks.URLBlock(required=True)),
                                        (
                                            "type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("Community", "Community"),
                                                    ("Paid", "Paid"),
                                                    ("Other", "Other"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("featured_articles", wagtail.blocks.StructBlock([])),
                            (
                                "featured_article",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "article",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                required=True, target_model="wiki.Document"
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            ("frequent_topics", wagtail.blocks.StructBlock([])),
                            (
                                "text",
                                wagtail.blocks.RichTextBlock(editor="default", search_index=True),
                            ),
                        ]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_index",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Single Product Index",
                "verbose_name_plural": "Single Product Indexes",
            },
            bases=("wagtailcore.page",),
        ),
    ]
