# Generated by Django 4.2.16 on 2024-09-23 06:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_sumoplaceholderpage_singleproductindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleproductindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("search", wagtail.blocks.StructBlock([])),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "headline",
                                    wagtail.blocks.CharBlock(max_length=255, required=True),
                                ),
                                ("details", wagtail.blocks.RichTextBlock(required=True)),
                                ("link", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("Community", "Community"),
                                            ("Paid", "Paid"),
                                            ("Other", "Other"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("featured_articles", wagtail.blocks.StructBlock([])),
                    (
                        "product_snippet",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "product",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        required=True, target_model="products.Product"
                                    ),
                                )
                            ]
                        ),
                    ),
                    ("frequent_topics", wagtail.blocks.StructBlock([])),
                    ("text", wagtail.blocks.RichTextBlock()),
                ]
            ),
        ),
    ]
