# Generated by Django 4.2.20 on 2025-05-02 08:57

from django.db import migrations, models
import kitsune.sumo.utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_auto_20241120_0218"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="metadata",
            field=models.JSONField(
                default=dict,
                encoder=kitsune.sumo.utils.PrettyJSONEncoder,
                help_text="Data useful for things like LLM prompts.",
            ),
        ),
    ]
