# Generated by Django 4.2.22 on 2025-06-10 17:00

from django.db import migrations, models
import kitsune.sumo.utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_auto_20250520_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="metadata",
            field=models.JSONField(
                default=dict,
                encoder=kitsune.sumo.utils.PrettyJSONEncoder,
                help_text="Data useful for things like LLM prompts.",
            ),
        ),
    ]
