# Generated by Django 4.2.23 on 2025-10-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0019_pinnedarticleconfig_and_more"),
        ("products", "0026_initial_product_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pinned_article_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Pinned article configuration for this product's landing page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="wiki.pinnedarticleconfig",
                verbose_name="Pinned article configuration",
            ),
        ),
    ]
