# Generated by Django 4.2.25 on 2025-12-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('questions', '0022_remove_aaqconfig_pinned_articles_and_more'),
        ('products', '0027_product_pinned_article_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this Zendesk configuration', max_length=255)),
                ('ticket_form_id', models.CharField(blank=True, help_text='Zendesk ticket form ID to use for this product (leave blank to use global default)', max_length=50)),
                ('enable_os_field', models.BooleanField(default=False, help_text='Show operating system selector in the support form')),
            ],
            options={
                'verbose_name': 'Zendesk configuration',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZendeskTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique identifier for this topic', max_length=100)),
                ('topic', models.CharField(help_text='User-facing topic text shown in the dropdown', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which topics appear (lower numbers first)')),
                ('legacy_tag', models.CharField(blank=True, help_text='Legacy Zendesk tag', max_length=100)),
                ('tier_tags', models.JSONField(default=list, help_text="List of tier tags (e.g., ['t1-billing-and-subscriptions'])")),
                ('automation_tag', models.CharField(blank=True, help_text='Automation tag for Zendesk workflows', max_length=100, null=True)),
                ('segmentation_tag', models.CharField(blank=True, help_text='Segmentation tag for analytics', max_length=100, null=True)),
                ('loginless_only', models.BooleanField(default=False, help_text='Only show this topic for loginless (unauthenticated) support flows')),
                ('zendesk_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='products.zendeskconfig')),
            ],
            options={
                'verbose_name': 'Zendesk topic',
                'ordering': ['display_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active per product')),
                ('default_support_type', models.CharField(choices=[('forum', 'Community Forums'), ('zendesk', 'Zendesk Support')], default='forum', help_text='Default support channel for users (used when only one channel or no group access)', max_length=20)),
                ('group_default_support_type', models.CharField(blank=True, choices=[('forum', 'Community Forums'), ('zendesk', 'Zendesk Support')], help_text='Default support type for users in hybrid groups (if not set, uses default_support_type)', max_length=20, null=True)),
                ('forum_config', models.ForeignKey(blank=True, help_text='Select forum configuration to enable community support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_configs', to='questions.aaqconfig')),
                ('hybrid_support_groups', models.ManyToManyField(blank=True, help_text='Groups that can choose between forums and Zendesk when both are enabled', related_name='hybrid_support_configs', to='auth.group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_configs', to='products.product')),
                ('zendesk_config', models.ForeignKey(blank=True, help_text='Select Zendesk configuration to enable Zendesk support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_configs', to='products.zendeskconfig')),
            ],
            options={
                'verbose_name': 'Product support configuration',
            },
        ),
        migrations.AddConstraint(
            model_name='zendesktopic',
            constraint=models.UniqueConstraint(fields=('zendesk_config', 'slug'), name='unique_zendesk_topic_per_config'),
        ),
        migrations.AddConstraint(
            model_name='productsupportconfig',
            constraint=models.UniqueConstraint(fields=('product', 'is_active'), name='unique_active_support_config'),
        ),
    ]
