# Generated by Django 4.2.25 on 2025-12-16 02:49

from django.conf import settings
from django.db import migrations


def populate_zendesk_configs(apps, schema_editor):
    """
    Populate ZendeskConfig, ZendeskTopic, and ProductSupportConfig from hardcoded data.

    Reads ZENDESK_CATEGORIES dict and creates database records for products that exist
    in this environment. Creates ProductSupportConfig for all products with either
    AAQConfig or ZendeskConfig.
    """
    from kitsune.customercare import ZENDESK_CATEGORIES, ZENDESK_CATEGORIES_LOGINLESS

    Product = apps.get_model("products", "Product")
    ZendeskConfig = apps.get_model("products", "ZendeskConfig")
    ZendeskTopic = apps.get_model("products", "ZendeskTopic")
    ProductSupportConfig = apps.get_model("products", "ProductSupportConfig")
    AAQConfig = apps.get_model("questions", "AAQConfig")

    zendesk_configs_by_slug = {}
    products_with_os_field = ["mozilla-vpn"]

    for product_slug, categories in ZENDESK_CATEGORIES.items():
        try:
            product = Product.objects.get(slug=product_slug)
        except Product.DoesNotExist:
            continue

        zendesk_config = ZendeskConfig.objects.create(
            name=f"{product.title} Support",
            ticket_form_id=str(settings.ZENDESK_TICKET_FORM_ID),
            enable_os_field=product_slug in products_with_os_field,
        )
        zendesk_configs_by_slug[product_slug] = zendesk_config

        display_order = 0
        for category in categories:
            tags = category.get("tags", {})
            ZendeskTopic.objects.create(
                zendesk_config=zendesk_config,
                slug=category["slug"],
                topic=category["topic"],
                display_order=display_order,
                legacy_tag=tags.get("legacy", ""),
                tier_tags=tags.get("tiers", []),
                automation_tag=tags.get("automation") or "",
                segmentation_tag=tags.get("segmentation") or "",
                loginless_only=False,
            )
            display_order += 1

        if product_slug in ZENDESK_CATEGORIES_LOGINLESS:
            for category in ZENDESK_CATEGORIES_LOGINLESS[product_slug]:
                tags = category.get("tags", {})
                ZendeskTopic.objects.create(
                    zendesk_config=zendesk_config,
                    slug=category["slug"],
                    topic=category["topic"],
                    display_order=display_order,
                    legacy_tag=tags.get("legacy", ""),
                    tier_tags=tags.get("tiers", []),
                    automation_tag=tags.get("automation") or "",
                    segmentation_tag=tags.get("segmentation") or "",
                    loginless_only=True,
                )
                display_order += 1

    for product in Product.objects.all():
        zendesk_config = zendesk_configs_by_slug.get(product.slug)

        config_data = None
        is_active = False

        if zendesk_config:
            config_data = {
                "product": product,
                "forum_config": None,
                "zendesk_config": zendesk_config,
                "default_support_type": "zendesk",
            }
            is_active = True
        else:
            aaq_config = AAQConfig.objects.filter(product=product, is_active=True).first()
            if aaq_config:
                config_data = {
                    "product": product,
                    "forum_config": aaq_config,
                    "zendesk_config": None,
                    "default_support_type": "forum",
                }
                is_active = True

        if config_data:
            ProductSupportConfig.objects.create(
                is_active=is_active, group_default_support_type=None, **config_data
            )


def reverse_migration(apps, schema_editor):
    """Reverse the data migration by deleting all created records."""
    ProductSupportConfig = apps.get_model("products", "ProductSupportConfig")
    ZendeskConfig = apps.get_model("products", "ZendeskConfig")
    ZendeskTopic = apps.get_model("products", "ZendeskTopic")

    ProductSupportConfig.objects.all().delete()
    ZendeskTopic.objects.all().delete()
    ZendeskConfig.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_zendeskconfig_zendesktopic_productsupportconfig_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_zendesk_configs, reverse_migration),
    ]
