# Generated by Django 4.2.25 on 2025-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_populate_zendesk_configs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productsupportconfig',
            constraint=models.CheckConstraint(check=models.Q(('forum_config__isnull', False), ('zendesk_config__isnull', False), _connector='OR'), name='at_least_one_support_channel'),
        ),
    ]
