# Generated by Django 4.2.25 on 2025-12-19 02:18

from django.db import migrations, models
import django.db.models.deletion


def migrate_to_m2m(apps, schema_editor):
    """
    Convert FK relationship to M2M:
    1. Create unique ZendeskTopic records (by slug)
    2. Create ZendeskTopicConfiguration records for each config-topic association
    3. Preserve display_order and loginless_only in through table
    """
    ZendeskTopic = apps.get_model("products", "ZendeskTopic")
    ZendeskTopicConfiguration = apps.get_model("products", "ZendeskTopicConfiguration")

    # Group existing topics by slug to find duplicates
    topics_by_slug = {}
    for old_topic in ZendeskTopic.objects.all():
        slug = old_topic.slug
        if slug not in topics_by_slug:
            # First occurrence - this becomes the canonical topic
            topics_by_slug[slug] = {
                "canonical_topic": old_topic,
                "instances": []
            }
        topics_by_slug[slug]["instances"].append(old_topic)

    # For each unique topic slug
    for slug, data in topics_by_slug.items():
        canonical_topic = data["canonical_topic"]

        # Create through table records for each config that used this topic
        for topic_instance in data["instances"]:
            ZendeskTopicConfiguration.objects.create(
                zendesk_config=topic_instance.zendesk_config,
                zendesk_topic=canonical_topic,
                display_order=topic_instance.display_order,
                loginless_only=topic_instance.loginless_only
            )

        # Delete duplicate topics (keep only canonical)
        for topic_instance in data["instances"]:
            if topic_instance.id != canonical_topic.id:
                topic_instance.delete()


def reverse_migration(apps, schema_editor):
    """
    Revert M2M back to FK by recreating duplicate topics.
    """
    ZendeskTopic = apps.get_model("products", "ZendeskTopic")
    ZendeskTopicConfiguration = apps.get_model("products", "ZendeskTopicConfiguration")

    for config_entry in ZendeskTopicConfiguration.objects.all():
        # Create a new topic for this config
        ZendeskTopic.objects.create(
            zendesk_config=config_entry.zendesk_config,
            slug=config_entry.zendesk_topic.slug,
            topic=config_entry.zendesk_topic.topic,
            display_order=config_entry.display_order,
            legacy_tag=config_entry.zendesk_topic.legacy_tag,
            tier_tags=config_entry.zendesk_topic.tier_tags,
            automation_tag=config_entry.zendesk_topic.automation_tag,
            segmentation_tag=config_entry.zendesk_topic.segmentation_tag,
            loginless_only=config_entry.loginless_only
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_ensure_at_least_one_support_channel'),
    ]

    operations = [
        # Step 1: Create the through table model with basic fields
        migrations.CreateModel(
            name='ZendeskTopicConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which this topic appears in this config (lower numbers first)')),
                ('loginless_only', models.BooleanField(default=False, help_text='Only show this topic for loginless flows in this config')),
            ],
            options={
                'verbose_name': 'Zendesk topic configuration',
                'ordering': ['display_order', 'zendesk_topic__slug'],
            },
        ),
        # Step 2: Add FK fields to the through table
        migrations.AddField(
            model_name='zendesktopicconfiguration',
            name='zendesk_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_configurations', to='products.zendeskconfig'),
        ),
        migrations.AddField(
            model_name='zendesktopicconfiguration',
            name='zendesk_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='products.zendesktopic'),
        ),
        # Step 3: Add unique constraint to through table
        migrations.AddConstraint(
            model_name='zendesktopicconfiguration',
            constraint=models.UniqueConstraint(fields=('zendesk_config', 'zendesk_topic'), name='unique_topic_per_config'),
        ),
        # Step 4: Migrate data from FK relationship to M2M through table
        migrations.RunPython(migrate_to_m2m, reverse_migration),
        # Step 5: Remove old constraint and fields from ZendeskTopic
        migrations.RemoveConstraint(
            model_name='zendesktopic',
            name='unique_zendesk_topic_per_config',
        ),
        migrations.RemoveField(
            model_name='zendesktopic',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='zendesktopic',
            name='loginless_only',
        ),
        migrations.RemoveField(
            model_name='zendesktopic',
            name='zendesk_config',
        ),
        # Step 6: Make slug globally unique and update meta options
        migrations.AlterField(
            model_name='zendesktopic',
            name='slug',
            field=models.SlugField(help_text='Globally unique identifier for this topic', max_length=100, unique=True),
        ),
        migrations.AlterModelOptions(
            name='zendesktopic',
            options={'ordering': ['slug'], 'verbose_name': 'Zendesk topic'},
        ),
        # Step 7: Add M2M field to ZendeskConfig
        migrations.AddField(
            model_name='zendeskconfig',
            name='topics',
            field=models.ManyToManyField(help_text='Topics available for this Zendesk configuration', related_name='zendesk_configs', through='products.ZendeskTopicConfiguration', to='products.zendesktopic'),
        ),
    ]
