# Generated by Django 4.2 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_zendesktopicconfiguration_alter_zendesktopic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskconfig',
            name='skip_spam_moderation',
            field=models.BooleanField(
                default=False,
                help_text='Skip AI-based spam checking for this product'
            ),
        ),
    ]
