# Generated by Django 5.2.11 on 2026-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_zendeskconfig_skip_spam_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskconfig',
            name='enable_deployment_fields',
            field=models.BooleanField(default=False, help_text='Show deployment-related fields (update channel and policy distribution) in the support form'),
        ),
    ]
