# Generated by Django 4.2.25 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_zendeskconfig_skip_spam_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='codename',
        ),
    ]
