# Generated by Django 5.2.11 on 2026-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_add_deployment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskconfig',
            name='brand_id',
            field=models.CharField(blank=True, help_text='Zendesk brand ID to associate tickets with for this product', max_length=50),
        ),
    ]
