# Generated by Django 5.2.12 on 2026-03-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_zendeskconfig_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupportconfig',
            name='subscription_only',
            field=models.BooleanField(default=False, help_text="If enabled, only users with an active product subscription can access support. Unsubscribed users are redirected to another product's AAQ if one is configured, otherwise the support widget is hidden."),
        ),
        migrations.AddField(
            model_name='productsupportconfig',
            name='unsubscribed_redirect_product',
            field=models.ForeignKey(blank=True, help_text="When subscription_only is enabled, redirect unsubscribed users to this product's AAQ. If not set, the support widget is hidden for unsubscribed users.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_target_for', to='products.product'),
        ),
    ]
