# Generated by Django 5.2.14 on 2026-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0036_move_esr_versions_to_firefox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupportconfig',
            name='hybrid_support_groups',
            field=models.ManyToManyField(blank=True, help_text="Groups that can choose between forums and Zendesk when both are enabled. Note: when Zendesk is enabled, each group listed here also becomes an 'organization root' — Zendesk tickets submitted by any of its members (or members of its subgroups) are visible to everyone in that subtree. Group must not be a tree root, and cannot overlap (as ancestor or descendant) with any group already listed in another product's hybrid_support_groups.", related_name='hybrid_support_configs', to='auth.group'),
        ),
    ]
