# Generated by Django 5.2.14 on 2026-05-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_productsupportconfig_hybrid_support_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zendesktopic',
            old_name='topic',
            new_name='form_title',
        ),
    ]
