# Generated by Django 5.2.14 on 2026-05-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_rename_topic_zendesktopic_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='legacy_tag',
            field=models.CharField(blank=True, help_text='Legacy Zendesk bucket (accounts/technical/payments). Set on t1 roots.', max_length=100),
        ),
        migrations.AddField(
            model_name='zendesktopic',
            name='automation_tags',
            field=models.JSONField(blank=True, default=list, help_text='List of automation tags for Zendesk workflows.'),
        ),
        migrations.AddField(
            model_name='zendesktopic',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Linked taxonomy topic. Source of truth for tier_tags and legacy_tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zendesk_topics', to='products.topic'),
        ),
    ]
