# Generated by Django 5.2.14 on 2026-05-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_backfill_topic_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zendesktopic',
            name='automation_tag',
        ),
    ]
