# Generated by Django 5.2.14 on 2026-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0042_repair_edit_email_topic_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="article_ordering",
            field=models.CharField(
                choices=[
                    ("default", "Default (display order, then popularity)"),
                    ("newest", "Newest first (most recently added)"),
                ],
                default="default",
                help_text="How KB articles are ordered for this topic.",
                max_length=20,
            ),
        ),
    ]
