# Generated by Django 5.2.17 on 2026-08-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_new_tab_page_product_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskconfig',
            name='enable_urgency_field',
            field=models.BooleanField(default=False, help_text='Show the urgency selector in the support form'),
        ),
    ]
