# Generated by Django 5.2.17 on 2026-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_firefox_enterprise_zendesk_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskconfig',
            name='skip_spam_moderation',
            field=models.BooleanField(default=False, help_text='Skip AI-based spam and product checking for this product'),
        ),
    ]
