# Generated by Django 5.2.17 on 2026-09-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0047_alter_zendeskconfig_skip_spam_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_live_chat', models.BooleanField(default=False, help_text='Members can start live chats with support agents. Requires Zendesk support.')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_organizations', to='products.productsupportconfig')),
                ('group', models.ForeignKey(help_text='Includes all subgroups. Cannot be a top-level group or nested with another configured group.', on_delete=django.db.models.deletion.CASCADE, related_name='support_organizations', to='auth.group')),
            ],
            options={
                'verbose_name': 'Support organization',
                'constraints': [models.UniqueConstraint(fields=('config', 'group'), name='unique_support_organization_per_config')],
            },
        ),
    ]
