# Generated by Django 5.2.17 on 2026-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_populate_supportorganizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupportconfig',
            name='group_default_support_type',
            field=models.CharField(blank=True, choices=[('forum', 'Community Forums'), ('zendesk', 'Zendesk Support')], help_text='Default support type for organization members (if not set, uses default_support_type)', max_length=20, null=True),
        ),
    ]
