# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 16:54
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import OuterRef, Exists


def change_locale_bn_bd_to_bn_forwards(apps, schema_editor):
    Document = apps.get_model('wiki', 'Document')
    DraftRevision = apps.get_model('wiki', 'DraftRevision')
    Locale = apps.get_model('wiki', 'Locale')

    # Change the locale of the documents that does not have bn-BD translation
    bn_bd_document = (Document.objects.only('id').all()
                                      .filter(parent=OuterRef('parent'), locale='bn-BD'))
    bn_in_documents = (Document.objects.all().filter(locale='bn-IN')
                                             .annotate(has_bn_bd=Exists(bn_bd_document))
                                             .exclude(has_bn_bd=True)
                                             .values_list('id', flat=True))

    Document.objects.all().filter(locale='bn-IN', id__in=list(bn_in_documents)).update(locale='bn')

    Document.objects.all().filter(locale='bn-BD').update(locale='bn')
    DraftRevision.objects.all().filter(locale='bn-BD').update(locale='bn')
    Locale.objects.all().filter(locale='bn-BD').update(locale='bn')


def change_locale_bn_to_bn_bd_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):


    dependencies = [
        ('wiki', '0009_auto_20190507_1052'),
    ]

    operations = [
        migrations.RunPython(change_locale_bn_bd_to_bn_forwards, change_locale_bn_to_bn_bd_backwards)
    ]
