# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import kitsune.sumo.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190816_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, this wiki page will be hidden from basic searches and dashboards. When viewed, the page will warn that it is no longer maintained.', verbose_name='is obsolete'),
        ),
        migrations.AlterField(
            model_name='document',
            name='locale',
            field=kitsune.sumo.models.LocaleField(choices=[('af', 'Afrikaans'), ('ar', 'عربي'), ('az', 'Azərbaycanca'), ('bg', 'Български'), ('bm', 'Bamanankan'), ('bn', 'বাংলা'), ('bs', 'Bosanski'), ('ca', 'català'), ('cs', 'Čeština'), ('da', 'Dansk'), ('de', 'Deutsch'), ('ee', 'Èʋegbe'), ('el', 'Ελληνικά'), ('en-US', 'English'), ('es', 'Español'), ('et', 'eesti keel'), ('eu', 'Euskara'), ('fa', 'فارسی'), ('fi', 'suomi'), ('fr', 'Français'), ('fy-NL', 'Frysk'), ('ga-IE', 'Gaeilge (Éire)'), ('gl', 'Galego'), ('gn', "Avañe'ẽ"), ('gu-IN', 'ગુજરાતી'), ('ha', 'هَرْشَن هَوْسَ'), ('he', 'עברית'), ('hi-IN', 'हिन्दी (भारत)'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('dsb', 'Dolnoserbšćina'), ('hsb', 'Hornjoserbsce'), ('id', 'Bahasa Indonesia'), ('ig', 'Asụsụ Igbo'), ('it', 'Italiano'), ('ja', '日本語'), ('ka', 'ქართული'), ('km', 'ខ្មែរ'), ('kn', 'ಕನ್ನಡ'), ('ko', '한국어'), ('ln', 'Lingála'), ('lt', 'lietuvių kalba'), ('mg', 'Malagasy'), ('mk', 'Македонски'), ('ml', 'മലയാളം'), ('ms', 'Bahasa Melayu'), ('ne-NP', 'नेपाली'), ('nl', 'Nederlands'), ('no', 'Norsk'), ('pl', 'Polski'), ('pt-BR', 'Português (do Brasil)'), ('pt-PT', 'Português (Europeu)'), ('ro', 'română'), ('ru', 'Русский'), ('si', 'සිංහල'), ('sk', 'slovenčina'), ('sl', 'slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sw', 'Kiswahili'), ('sv', 'Svenska'), ('ta', 'தமிழ்'), ('ta-LK', 'தமிழ் (இலங்கை)'), ('te', 'తెలుగు'), ('th', 'ไทย'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('ur', 'اُردو'), ('vi', 'Tiếng Việt'), ('wo', 'Wolof'), ('xh', 'isiXhosa'), ('yo', 'èdè Yorùbá'), ('zh-CN', '中文 (简体)'), ('zh-TW', '正體中文 (繁體)'), ('zu', 'isiZulu')], db_index=True, default='en-US', max_length=7),
        ),
        migrations.AlterField(
            model_name='document',
            name='share_link',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='draftrevision',
            name='locale',
            field=kitsune.sumo.models.LocaleField(choices=[('af', 'Afrikaans'), ('ar', 'عربي'), ('az', 'Azərbaycanca'), ('bg', 'Български'), ('bm', 'Bamanankan'), ('bn', 'বাংলা'), ('bs', 'Bosanski'), ('ca', 'català'), ('cs', 'Čeština'), ('da', 'Dansk'), ('de', 'Deutsch'), ('ee', 'Èʋegbe'), ('el', 'Ελληνικά'), ('en-US', 'English'), ('es', 'Español'), ('et', 'eesti keel'), ('eu', 'Euskara'), ('fa', 'فارسی'), ('fi', 'suomi'), ('fr', 'Français'), ('fy-NL', 'Frysk'), ('ga-IE', 'Gaeilge (Éire)'), ('gl', 'Galego'), ('gn', "Avañe'ẽ"), ('gu-IN', 'ગુજરાતી'), ('ha', 'هَرْشَن هَوْسَ'), ('he', 'עברית'), ('hi-IN', 'हिन्दी (भारत)'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('dsb', 'Dolnoserbšćina'), ('hsb', 'Hornjoserbsce'), ('id', 'Bahasa Indonesia'), ('ig', 'Asụsụ Igbo'), ('it', 'Italiano'), ('ja', '日本語'), ('ka', 'ქართული'), ('km', 'ខ្មែរ'), ('kn', 'ಕನ್ನಡ'), ('ko', '한국어'), ('ln', 'Lingála'), ('lt', 'lietuvių kalba'), ('mg', 'Malagasy'), ('mk', 'Македонски'), ('ml', 'മലയാളം'), ('ms', 'Bahasa Melayu'), ('ne-NP', 'नेपाली'), ('nl', 'Nederlands'), ('no', 'Norsk'), ('pl', 'Polski'), ('pt-BR', 'Português (do Brasil)'), ('pt-PT', 'Português (Europeu)'), ('ro', 'română'), ('ru', 'Русский'), ('si', 'සිංහල'), ('sk', 'slovenčina'), ('sl', 'slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sw', 'Kiswahili'), ('sv', 'Svenska'), ('ta', 'தமிழ்'), ('ta-LK', 'தமிழ் (இலங்கை)'), ('te', 'తెలుగు'), ('th', 'ไทย'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('ur', 'اُردو'), ('vi', 'Tiếng Việt'), ('wo', 'Wolof'), ('xh', 'isiXhosa'), ('yo', 'èdè Yorùbá'), ('zh-CN', '中文 (简体)'), ('zh-TW', '正體中文 (繁體)'), ('zu', 'isiZulu')], db_index=True, default='en-US', max_length=7),
        ),
        migrations.AlterField(
            model_name='locale',
            name='locale',
            field=kitsune.sumo.models.LocaleField(choices=[('af', 'Afrikaans'), ('ar', 'عربي'), ('az', 'Azərbaycanca'), ('bg', 'Български'), ('bm', 'Bamanankan'), ('bn', 'বাংলা'), ('bs', 'Bosanski'), ('ca', 'català'), ('cs', 'Čeština'), ('da', 'Dansk'), ('de', 'Deutsch'), ('ee', 'Èʋegbe'), ('el', 'Ελληνικά'), ('en-US', 'English'), ('es', 'Español'), ('et', 'eesti keel'), ('eu', 'Euskara'), ('fa', 'فارسی'), ('fi', 'suomi'), ('fr', 'Français'), ('fy-NL', 'Frysk'), ('ga-IE', 'Gaeilge (Éire)'), ('gl', 'Galego'), ('gn', "Avañe'ẽ"), ('gu-IN', 'ગુજરાતી'), ('ha', 'هَرْشَن هَوْسَ'), ('he', 'עברית'), ('hi-IN', 'हिन्दी (भारत)'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('dsb', 'Dolnoserbšćina'), ('hsb', 'Hornjoserbsce'), ('id', 'Bahasa Indonesia'), ('ig', 'Asụsụ Igbo'), ('it', 'Italiano'), ('ja', '日本語'), ('ka', 'ქართული'), ('km', 'ខ្មែរ'), ('kn', 'ಕನ್ನಡ'), ('ko', '한국어'), ('ln', 'Lingála'), ('lt', 'lietuvių kalba'), ('mg', 'Malagasy'), ('mk', 'Македонски'), ('ml', 'മലയാളം'), ('ms', 'Bahasa Melayu'), ('ne-NP', 'नेपाली'), ('nl', 'Nederlands'), ('no', 'Norsk'), ('pl', 'Polski'), ('pt-BR', 'Português (do Brasil)'), ('pt-PT', 'Português (Europeu)'), ('ro', 'română'), ('ru', 'Русский'), ('si', 'සිංහල'), ('sk', 'slovenčina'), ('sl', 'slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sw', 'Kiswahili'), ('sv', 'Svenska'), ('ta', 'தமிழ்'), ('ta-LK', 'தமிழ் (இலங்கை)'), ('te', 'తెలుగు'), ('th', 'ไทย'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('ur', 'اُردو'), ('vi', 'Tiếng Việt'), ('wo', 'Wolof'), ('xh', 'isiXhosa'), ('yo', 'èdè Yorùbá'), ('zh-CN', '中文 (简体)'), ('zh-TW', '正體中文 (繁體)'), ('zu', 'isiZulu')], default='en-US', max_length=7, unique=True),
        ),
    ]
