# Generated by Django 3.2.16 on 2022-11-28 06:16

from django.conf import settings
from django.db import migrations, models
import kitsune.tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0012_auto_20200629_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contributors',
            field=models.ManyToManyField(related_name='sumo_documents_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=kitsune.tags.models.BigVocabTaggableManager(help_text='A comma-separated list of tags.', related_name='documents_tagged', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
