# Generated by Django 4.1.10 on 2023-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0001_squashed_0013_alter_document_related_documents_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(fields=["created"], name="wiki_revisi_created_0dd502_idx"),
        ),
    ]
