# Generated by Django 4.1.3 on 2022-12-07 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200629_0826'),
        ('wiki', '0013_alter_document_related_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contributors',
            field=models.ManyToManyField(related_name='sumo_documents_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WgDocument',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', wagtail.fields.RichTextField()),
                ('content', wagtail.fields.RichTextField()),
                ('category', models.IntegerField(blank=True, choices=[(10, 'Troubleshooting'), (20, 'How to'), (30, 'How to contribute'), (40, 'Administration'), (50, 'Navigation'), (60, 'Templates'), (70, 'Canned Responses')], db_index=True)),
                ('is_template', models.BooleanField(default=False)),
                ('allow_discussion', models.BooleanField(default=True, help_text='If checked, this document allows discussion in an associated forum. Uncheck to hide/disable the forum.')),
                ('share_link', models.CharField(blank=True, default='', max_length=24)),
                ('display_order', models.IntegerField(db_index=True, default=1)),
                ('contributors', models.ManyToManyField(related_name='wg_documents_contributed', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
                ('related_documents', models.ManyToManyField(blank=True, to='wiki.wgdocument')),
                ('topics', models.ManyToManyField(blank=True, to='products.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
