# Generated by Django 4.2.7 on 2024-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wiki", "0014_revision_wiki_revisi_created_0dd502_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="restrict_to_groups",
            field=models.ManyToManyField(related_name="restricted_documents", to="auth.group"),
        ),
    ]
