# Generated by Django 4.1.3 on 2022-12-08 02:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200629_0826'),
        ('wiki', '0014_alter_document_contributors_wgdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wgdocument',
            name='products',
        ),
        migrations.RemoveField(
            model_name='wgdocument',
            name='topics',
        ),
        migrations.CreateModel(
            name='WgDocumentTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.topic')),
                ('wgdocument', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='wiki.wgdocument')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WgDocumentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wgdocument', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='wiki.wgdocument')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
