# Generated by Django 4.1.13 on 2023-11-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wiki", "0014_revision_wiki_revisi_created_0dd502_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="restrict_to_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_restricted",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="restrict_to_staff",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
