# Generated by Django 4.1.3 on 2023-01-26 06:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_remove_wgdocument_products_remove_wgdocument_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgdocument',
            name='article_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=False),
        ),
    ]
