# Generated by Django 4.1.6 on 2023-02-09 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0016_wgdocument_article_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wgdocument",
            options={"verbose_name": "Wiki Document"},
        ),
    ]
