# Generated by Django 4.2.18 on 2025-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wiki", "0017_alter_document_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="restrict_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="restricted_documents", to="auth.group"
            ),
        ),
    ]
