# Generated by Django 4.2.20 on 2025-03-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0018_alter_document_restrict_to_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="based_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wiki.revision",
            ),
        ),
    ]
