# Generated by Django 4.2.23 on 2025-10-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_initial_product_metadata"),
        ("wiki", "0018_alter_document_restrict_to_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedArticleConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pinned_articles",
                    models.ManyToManyField(
                        limit_choices_to=models.Q(("parent__isnull", True)), to="wiki.document"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to configure the home page.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_article_config",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pinned Article Configuration",
                "ordering": ("product__title", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="pinnedarticleconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("product",),
                name="unique_pinned_article_config_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="pinnedarticleconfig",
            constraint=models.UniqueConstraint(
                models.Value(1, output_field=models.IntegerField()),
                condition=models.Q(("product__isnull", True)),
                name="unique_pinned_article_config_home_page",
            ),
        ),
    ]
