# Generated by Django 4.2.25 on 2025-10-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_pinnedarticleconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedarticleconfig',
            name='pinned_articles',
            field=models.ManyToManyField(limit_choices_to=models.Q(('category__in', (10, 20, 30)), ('is_archived', False), ('is_template', False), ('parent__isnull', True), models.Q(('html__startswith', '<p>REDIRECT <a '), _negated=True)), to='wiki.document'),
        ),
    ]
