# Generated by Django 4.2.25 on 2025-12-19 11:17

from django.db import migrations, models
import django.db.models.deletion
import kitsune.sumo.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_alter_pinnedarticleconfig_pinned_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAnchorRecord',
            fields=[
                ('revision', models.OneToOneField(help_text='The translated revision to which this map belongs.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anchor_record', serialize=False, to='wiki.revision')),
                ('map', models.JSONField(default=dict, encoder=kitsune.sumo.utils.PrettyJSONEncoder, help_text='Map of source anchors to target anchors.')),
                ('explanation', models.TextField(help_text='The LLM explanation for this anchor map.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
