# Generated by Django 5.2.10 on 2026-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_revisionanchorrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftrevision',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='helpfulvote',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='revision',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
