# Generated by Django 5.2.14 on 2026-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0023_alter_draftrevision_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinnedarticleconfig",
            name="pinned_articles",
            field=models.ManyToManyField(
                limit_choices_to=models.Q(
                    ("category__in", (10, 20, 30)),
                    ("current_revision__isnull", False),
                    ("is_archived", False),
                    ("is_template", False),
                    ("parent__isnull", True),
                    ("restrict_to_groups__isnull", True),
                    models.Q(("html__startswith", "<p>REDIRECT <a "), _negated=True),
                ),
                to="wiki.document",
            ),
        ),
    ]
