# Generated by Django 2.2.13 on 2020-06-29 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(help_text="Use wiki syntax or HTML. It will display similar to a document's content.", max_length=10000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='show_after',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, help_text='When this announcement will start appearing. (US/Pacific)', verbose_name='Start displaying'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='show_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this announcement will stop appearing. Leave blank for indefinite. (US/Pacific)', null=True, verbose_name='Stop displaying'),
        ),
    ]
