# Generated by Django 4.1.7 on 2023-02-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("announcements", "0003_announcement_send_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="announcements", to="auth.group"
            ),
        ),
    ]
