# Generated by Django 4.1.7 on 2023-02-22 01:05

from django.db import migrations


def migrate_groups(apps, schema_editor):
    Announcement = apps.get_model("announcements", "Announcement")

    for announcement in Announcement.objects.all():
        if announcement.group:
            announcement.groups.add(announcement.group)
            announcement.save()


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0004_announcement_groups"),
    ]

    operations = [migrations.RunPython(migrate_groups, migrations.RunPython.noop)]
