# Generated by Django 4.1.7 on 2023-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0005_auto_20230222_0105"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="group",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="send_email",
            field=models.BooleanField(
                default=False,
                help_text="Send an email to all users in the groups. If no groups are selected, this is ignored.",
            ),
        ),
    ]
