# Generated by Django 4.2.23 on 2025-08-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_initial_product_metadata'),
        ('announcements', '0001_squashed_0006_remove_announcement_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='products.platform'),
        ),
    ]
