# Generated by Django 4.2.23 on 2025-11-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_pinned_article_config'),
        ('announcements', '0007_announcement_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='product',
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this announcement will only display on this product's landing page.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='announcements',
                to='products.product'
            ),
        ),
    ]
