# Generated by Django 4.2.25 on 2025-12-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created']},
        ),
    ]
