# Generated by Django 5.2.10 on 2026-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='show_after',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this announcement will start appearing. (US/Pacific)', verbose_name='Start displaying'),
        ),
    ]
