version: 2.1

commands:
  run-tests-with-es:
    parameters:
      app_labels:
        type: string
    steps:
      - checkout:
          method: blobless
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build test image
          command: |
            cp .env-build .env
            ./bin/dc_ci.sh build --progress=plain test
      - run:
          # copy synonym files to elasticsearch container, since circleci doesn't support volume mounts:
          # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
          name: Copy synonym files to elasticsearch
          command: |
            ./bin/dc_ci.sh up -d elasticsearch
            docker cp ./kitsune/search/dictionaries/synonyms/. project-elasticsearch-1:/usr/share/elasticsearch/config/synonyms
      - run:
          name: Run unit tests
          command: ./bin/dc_ci.sh run test ./bin/run-unit-tests.sh << parameters.app_labels >>

  run-tests-no-es:
    parameters:
      app_labels:
        type: string
    steps:
      - checkout:
          method: blobless
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build test image
          command: |
            cp .env-build .env
            ./bin/dc_ci.sh build --progress=plain test
      - run:
          name: Start required services
          command: ./bin/dc_ci.sh up -d postgres redis
      - run:
          name: Run unit tests
          command: ./bin/dc_ci.sh run --no-deps test ./bin/run-unit-tests-no-es.sh << parameters.app_labels >>

jobs:
  lint:
    docker:
      - image: cimg/python:3.14-node
    steps:
      - checkout:
         method: blobless
      - run:
          name: Install Node.js dependencies
          command: npm ci
      - run:
          name: Lint with pre-commit
          command: |
            pip install pre-commit==4.2.0
            pre-commit run --all-files

  wiki-tests:
    docker:
      - image: cimg/python:3.14
    steps:
      - run-tests-no-es:
          app_labels: kitsune.wiki kitsune.kbforums

  questions-tests:
    docker:
      - image: cimg/python:3.14
    steps:
      - run-tests-with-es:
          app_labels: kitsune.questions

  elasticsearch-tests:
    docker:
      - image: cimg/python:3.14
    steps:
      - run-tests-with-es:
          app_labels: kitsune.search kitsune.community kitsune.products kitsune.landings

  kitsune-tests:
    docker:
      - image: cimg/python:3.14
    steps:
      - run-tests-no-es:
          app_labels: >-
            kitsune.sumo kitsune.users kitsune.forums kitsune.groups kitsune.dashboards
            kitsune.customercare kitsune.kpi kitsune.upload kitsune.llm kitsune.announcements
            kitsune.gallery kitsune.notifications kitsune.messages kitsune.flagit kitsune.access
            kitsune.inproduct kitsune.kbadge kitsune.tidings kitsune.karma kitsune.tags

  test-js:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout:
         method: blobless
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build frontend test image
          command: |
            cp .env-build .env
            ./bin/dc_ci.sh build --progress=plain frontend-test
      - run:
          name: Run js tests
          command: ./bin/dc_ci.sh run frontend-test

workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint
      - wiki-tests
      - questions-tests
      - elasticsearch-tests
      - kitsune-tests
      - test-js
