# Generated by Django 4.1.9 on 2023-06-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [("postcrash", "0001_initial")]

    initial = True

    dependencies = [
        ("wiki", "0001_squashed_0013_alter_document_related_documents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("signature", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wiki.document"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
