from django.core.management.base import BaseCommand
from taggit.models import TaggedItem

from kitsune.wiki.models import Document


class Command(BaseCommand):
    help = 'Dumps out a python file with the topic strings.'

    def handle(self, *arg, **kwargs):
        print('##########################################################')
        print('### This file is generated by ./manage.py dump_topics. ###')
        print('##########################################################')
        print('from django.utils.translation import pgettext\n')
        for tag in TaggedItem.tags_for(Document):
            print('pgettext("KB Topic", """{tag}""")'.format(tag=tag.name))
