# Generated by Django 4.2.20 on 2025-03-17 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kbforums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_post_last_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
