# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 18:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kbadge', '0002_auto_20181023_1319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='award',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
