# Generated by Django 2.2.13 on 2020-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbadge', '0003_auto_20190816_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, help_text='Explanation and evidence for the badge award'),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Must be square. Recommended 256x256.', null=True, upload_to='uploads/badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unique',
            field=models.BooleanField(default=True, help_text='Should awards of this badge be limited to one-per-person?'),
        ),
    ]
