# Generated by Django 4.1.7 on 2023-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product", models.CharField(blank=True, db_index=True, max_length=50)),
                ("version", models.CharField(blank=True, db_index=True, max_length=50)),
                ("platform", models.CharField(blank=True, db_index=True, max_length=50)),
                ("locale", models.CharField(blank=True, db_index=True, max_length=10)),
                ("topic", models.CharField(blank=True, db_index=True, max_length=100)),
                ("target", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("product", "version", "platform", "locale", "topic")},
            },
        ),
    ]
