# Generated by Django 4.1.7 on 2023-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inproduct", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="platform",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="product",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="target",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="topic",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="version",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
