services:
  test:
    build:
      context: .
      target: test
    env_file: .env-test
    volumes:
      - ./:/app:delegated

  prod:
    build:
      context: .
      target: prod
      args:
        - GIT_SHA
    image: mozilla/kitsune:prod-${GIT_COMMIT_SHORT:-latest}
