services:
  test:
    image: kitsune-test:ci
    build:
      context: .
      target: test
    env_file: .env-test
    environment:
      DJANGO_TEST_PROCESSES: "2"
    depends_on:
      - postgres
      - elasticsearch
      - redis

  frontend-test:
    image: kitsune-frontend-test:ci
    build:
      context: .
      target: frontend-builder
    command: npx mocha --require ./webpack/mocha-require dist/tests.js

  postgres:
    ports: !reset []

  elasticsearch:
    ports: !reset []

  prod:
    build:
      context: .
      target: prod
      args:
        - GIT_SHA
    image: mozilla/kitsune:prod-${GIT_COMMIT_SHORT:-latest}
