# Generated by Django 2.2.24 on 2021-09-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200629_0826'),
        ('wiki', '0012_auto_20200629_0826'),
        ('questions', '0011_auto_20200629_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAQConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_articles', models.ManyToManyField(to='wiki.Document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aaq_configs', to='products.Product')),
            ],
            options={
                'verbose_name': 'AAQ configuration',
            },
        ),
    ]
