# Generated by Django 2.2.23 on 2021-08-06 09:25

from django.db import migrations
import kitsune.sumo.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200629_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=kitsune.sumo.models.utf8mb3TextField(html=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=kitsune.sumo.models.utf8mb3TextField(html=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=kitsune.sumo.models.utf8mb3CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionmetadata',
            name='value',
            field=kitsune.sumo.models.utf8mb3TextField(),
        ),
    ]
