# Generated by Django 3.2.11 on 2022-01-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_aaqconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
