# Generated by Django 4.2.14 on 2024-08-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0016_alter_document_contributors"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("questions", "0001_squashed_0013_alter_question_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="aaqconfig",
            name="associated_tags",
            field=models.ManyToManyField(blank=True, null=True, to="taggit.tag"),
        ),
        migrations.AddField(
            model_name="aaqconfig",
            name="enabled_locales",
            field=models.ManyToManyField(to="questions.questionlocale"),
        ),
        migrations.AddField(
            model_name="aaqconfig",
            name="extra_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aaqconfig",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aaqconfig",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="aaqconfig",
            name="pinned_articles",
            field=models.ManyToManyField(blank=True, null=True, to="wiki.document"),
        ),
        migrations.AddConstraint(
            model_name="aaqconfig",
            constraint=models.UniqueConstraint(
                fields=("product", "is_active"), name="unique_active_config"
            ),
        ),
    ]
