# Generated by Django 4.2.14 on 2024-08-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0015_auto_20240802_0524"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionlocale",
            name="products",
        ),
    ]
