# Generated by Django 4.2.16 on 2024-11-15 06:58

from django.db import migrations, models
import kitsune.tags.models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("questions", "0018_auto_20241105_0532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aaqconfig",
            name="associated_tags",
            field=models.ManyToManyField(blank=True, null=True, to="tags.sumotag"),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=kitsune.tags.models.BigVocabTaggableManager(
                help_text="A comma-separated list of tags.",
                through="tags.SumoTaggedItem",
                to="tags.SumoTag",
                verbose_name="Tags",
            ),
        ),
    ]
