# Generated by Django 4.2.16 on 2024-12-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0019_alter_aaqconfig_associated_tags_alter_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="moderation_timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
