# Generated by Django 4.2.18 on 2025-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0020_question_moderation_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_failed_deflection",
            field=models.BooleanField(default=False),
        ),
    ]
