# Generated by Django 4.2.23 on 2025-10-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_answer_marked_as_spam_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaqconfig',
            name='pinned_articles',
        ),
    ]
