# Generated by Django 2.2.13 on 2020-06-29 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Assign this title to these groups.', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='title',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Assign this title to these users.', to=settings.AUTH_USER_MODEL),
        ),
    ]
