# Generated by Django 4.2.23 on 2025-08-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20241115_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sumotag',
            options={'ordering': ['name', '-created']},
        ),
    ]
