{{ if .Values.development_mode.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-secrets-local
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # You can include additional key value pairs as you do with Opaque Secrets
  ALLOWED_HOSTS: {{ .Values.allowed_hosts | default "127.0.0.1,localhost" | quote }}
  CELERY_BROKER_URL: {{ .Values.celery_broker_url | default "redis://kitsune@kitsune-redis-master:6379/4" | quote }}
  REDIS_DEFAULT_URL: {{ .Values.redis_default_url | default "redis://kitsune-redis-master:6379/1" | quote }}
  CACHE_URL: {{ .Values.cache_url | default "redis://redis:6379/3" | quote }}
  DATABASE_URL: {{ .Values.config.database_url | default "mysql://root:kitsune@kitsune-mariadb:3306/kitsune" | quote }}
  SECRET_KEY: {{ .Values.config.secret_key | default "this is secret" | quote }}
  REDIS_HELPFULVOTES_URL: {{ .Values.redis_helpful_votes_url | default "redis://kitsune-redis-master:6379/2" | quote }}
{{ end }}