# Generated by Django 5.2.14 on 2026-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskHealth",
            fields=[
                ("name", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_completed_at", models.DateTimeField(null=True)),
                ("last_alerted_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
