# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180523_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageattachment',
            name='file',
            field=models.ImageField(max_length=250, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='uploads/images/thumbnails/'),
        ),
    ]
