# Generated by Django 3.2.16 on 2022-10-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forum",
            options={
                "ordering": ["display_order", "id"],
                "permissions": (
                    ("view_in_forum", "Can view restricted forums"),
                    ("post_in_forum", "Can post in restricted forums"),
                    ("delete_forum_thread", "Can delete forum threads"),
                    ("edit_forum_thread", "Can edit forum threads"),
                    ("lock_forum_thread", "Can lock/unlock forum threads"),
                    ("move_forum_thread", "Can move threads between forums"),
                    ("sticky_forum_thread", "Can mark/unmark a forum thread as sticky"),
                    ("delete_forum_thread_post", "Can delete posts within forum threads"),
                    ("edit_forum_thread_post", "Can edit posts within forum threads"),
                ),
            },
        ),
        migrations.AddField(
            model_name="forum",
            name="restrict_posting",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="forum",
            name="restrict_viewing",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
