# Generated by Django 4.1.3 on 2022-12-19 16:26

from django.db import migrations


def drop_authority_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS authority_permission")


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_authority_to_guardian_data'),
    ]

    operations = [
        migrations.RunPython(drop_authority_tables, migrations.RunPython.noop),
    ]
