# Generated by Django 4.2.20 on 2025-03-11 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forums", "0001_squashed_0004_remove_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_last_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
