# Generated by Django 4.2.16 on 2024-12-09 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wiki", "0017_alter_document_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineTranslationConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Enable machine translation"),
                ),
                (
                    "llm_name",
                    models.CharField(blank=True, max_length=100, verbose_name="LLM model name"),
                ),
                (
                    "heartbeat_period",
                    models.DurationField(
                        default=datetime.timedelta(seconds=14400),
                        help_text="The management of existing machine translations, as well as the generation of any new machine translations, will be performed at this interval.",
                        verbose_name="Heartbeat period",
                    ),
                ),
                (
                    "review_grace_period",
                    models.DurationField(
                        default=datetime.timedelta(days=3),
                        help_text="The grace period provided for the machine translation to be reviewed, after which it will be automatically approved.",
                        verbose_name="Review grace period",
                    ),
                ),
                (
                    "post_review_grace_period",
                    models.DurationField(
                        default=datetime.timedelta(days=3),
                        help_text="The grace period provided after the machine translation has been reviewed and rejected, after which the machine translation will be automatically approved if no other translation has been approved within that period.",
                        verbose_name="Post-review grace period",
                    ),
                ),
                (
                    "locale_team_inactivity_grace_period",
                    models.DurationField(
                        default=datetime.timedelta(days=30),
                        help_text="If a leader or reviewer of a locale team has not created or reviewed a KB article within this period of time, the locale team will be considered inactive.",
                        verbose_name="Locale-team inactivity grace period",
                    ),
                ),
                (
                    "enabled_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The languages enabled for machine translation.",
                    ),
                ),
                (
                    "limit_to_slugs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Limit machine translation to these KB article slugs.",
                    ),
                ),
                (
                    "disabled_slugs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Disable machine translation for these KB article slugs.",
                    ),
                ),
                (
                    "limit_to_approved_after",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="Limit machine translation to KB article revisions approved after this date and time",
                    ),
                ),
                (
                    "limit_to_approver_in_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="auth.group",
                        verbose_name="Limit machine translation to KB article revisions approved by users within this group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine translation configuration",
                "verbose_name_plural": "Machine translation configuration",
            },
        ),
        migrations.CreateModel(
            name="RevisionActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Created as awaiting review"),
                            (1, "Created as already approved"),
                            (2, "Rejected because no longer relevant"),
                            (3, "Approved because not reviewed within grace period"),
                            (
                                4,
                                "Created as already approved because nothing else approved within grace period after rejection",
                            ),
                        ]
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="l10n_actions",
                        to="wiki.revision",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["action"], name="action_idx")],
            },
        ),
        migrations.CreateModel(
            name="MachineTranslationServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "service",
                    models.CharField(
                        choices=[("openai-api", "OpenAI API"), ("vertex-ai-api", "Vertex AI API")],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                (
                    "target_locale",
                    models.CharField(
                        choices=[
                            ("af", "Afrikaans (af)"),
                            ("ar", "Arabic (ar)"),
                            ("az", "Azerbaijani (az)"),
                            ("bg", "Bulgarian (bg)"),
                            ("bm", "Bambara (bm)"),
                            ("bn", "Bengali (bn)"),
                            ("bs", "Bosnian (bs)"),
                            ("ca", "Catalan (ca)"),
                            ("cs", "Czech (cs)"),
                            ("da", "Danish (da)"),
                            ("de", "German (de)"),
                            ("ee", "Ewe (ee)"),
                            ("el", "Greek (el)"),
                            ("es", "Spanish (es)"),
                            ("et", "Estonian (et)"),
                            ("eu", "Basque (eu)"),
                            ("fa", "Persian (fa)"),
                            ("fi", "Finnish (fi)"),
                            ("fr", "French (fr)"),
                            ("fy-NL", "Frisian (fy-NL)"),
                            ("ga-IE", "Irish (Ireland) (ga-IE)"),
                            ("gl", "Galician (gl)"),
                            ("gn", "Guarani (gn)"),
                            ("gu-IN", "Gujarati (gu-IN)"),
                            ("ha", "Hausa (ha)"),
                            ("he", "Hebrew (he)"),
                            ("hi-IN", "Hindi (India) (hi-IN)"),
                            ("hr", "Croatian (hr)"),
                            ("hu", "Hungarian (hu)"),
                            ("dsb", "Lower Sorbian (dsb)"),
                            ("hsb", "Upper Sorbian (hsb)"),
                            ("id", "Indonesian (id)"),
                            ("ig", "Igbo (ig)"),
                            ("it", "Italian (it)"),
                            ("ja", "Japanese (ja)"),
                            ("ka", "Georgian (ka)"),
                            ("km", "Khmer (km)"),
                            ("kn", "Kannada (kn)"),
                            ("ko", "Korean (ko)"),
                            ("ln", "Lingala (ln)"),
                            ("lt", "Lithuanian (lt)"),
                            ("mg", "Malagasy (mg)"),
                            ("mk", "Macedonian (mk)"),
                            ("ml", "Malayalam (ml)"),
                            ("ms", "Malay (ms)"),
                            ("ne-NP", "Nepali (ne-NP)"),
                            ("nl", "Dutch (nl)"),
                            ("no", "Norwegian (no)"),
                            ("pl", "Polish (pl)"),
                            ("pt-BR", "Portuguese (Brazilian) (pt-BR)"),
                            ("pt-PT", "Portuguese (Portugal) (pt-PT)"),
                            ("ro", "Romanian (ro)"),
                            ("ru", "Russian (ru)"),
                            ("si", "Sinhala (si)"),
                            ("sk", "Slovak (sk)"),
                            ("sl", "Slovenian (sl)"),
                            ("sq", "Albanian (sq)"),
                            ("sr", "Serbian (sr)"),
                            ("sw", "Swahili (sw)"),
                            ("sv", "Swedish (sv)"),
                            ("ta", "Tamil (ta)"),
                            ("ta-LK", "Tamil (Sri Lanka) (ta-LK)"),
                            ("te", "Telugu (te)"),
                            ("th", "Thai (th)"),
                            ("tn", "Tswana (tn)"),
                            ("tr", "Turkish (tr)"),
                            ("uk", "Ukrainian (uk)"),
                            ("ur", "Urdu (ur)"),
                            ("vi", "Vietnamese (vi)"),
                            ("wo", "Wolof (wo)"),
                            ("xh", "Xhosa (xh)"),
                            ("yo", "Yoruba (yo)"),
                            ("zh-CN", "Chinese (Simplified) (zh-CN)"),
                            ("zh-TW", "Chinese (Traditional) (zh-TW)"),
                            ("zu", "Zulu (zu)"),
                        ],
                        max_length=7,
                    ),
                ),
                ("source_attribute", models.CharField(max_length=100)),
                ("details", models.JSONField(default=dict)),
                (
                    "source_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mt_service_records",
                        to="wiki.revision",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created"], name="created_idx"),
                    models.Index(fields=["service"], name="service_idx"),
                    models.Index(fields=["model_name"], name="model_name_idx"),
                    models.Index(fields=["target_locale"], name="target_locale_idx"),
                    models.Index(fields=["source_attribute"], name="source_attribute_idx"),
                ],
            },
        ),
    ]
