# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploads/groupavatars/', verbose_name='Avatar'),
        ),
    ]
