# Generated by Django 2.2.13 on 2020-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='uploads/groupavatars/', verbose_name='Avatar'),
        ),
    ]
