# Generated by Django 4.2.25 on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_add_staff_content_team_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='numchild',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
