# Generated by Django 4.2.25 on 2026-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_add_staff_content_team_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupprofile",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Only group members, group leaders, and superusers, can view a private group.",
            ),
        ),
    ]
