# Generated by Django 4.2.25 on 2026-01-14 03:52

from django.db import connection, migrations


def initialize_tree_structure(apps, schema_editor):
    GroupProfileModel = apps.get_model('groups', 'GroupProfile')

    from kitsune.groups.models import GroupProfile as ActualGroupProfile

    existing_groups = GroupProfileModel.objects.all().order_by('id')

    for i, group in enumerate(existing_groups, 1):
        new_path = ActualGroupProfile._get_path(None, 1, i)

        GroupProfileModel.objects.filter(id=group.id).update(
            path=new_path,
            depth=1,
            numchild=0
        )

    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            table_name = GroupProfileModel._meta.db_table
            cursor.execute(f"SELECT setval(pg_get_serial_sequence('{table_name}', 'id'), MAX(id)) FROM {table_name};")


def reverse_initialize(apps, schema_editor):
    GroupProfile = apps.get_model('groups', 'GroupProfile')
    GroupProfile.objects.update(path=None, depth=None, numchild=None)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupprofile_depth_groupprofile_numchild_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_tree_structure, reverse_initialize),
    ]
