# Generated by Django 4.2.25 on 2026-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_initialize_tree_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
