# Generated by Django 4.2.25 on 2026-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0007_alter_groupprofile_depth_alter_groupprofile_numchild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private - members only'), ('public', 'Public - visible to all'), ('moderated', 'Moderated - visible to specific groups')], default='public', help_text='Who can see this group', max_length=20),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can see this group when visibility is MODERATED', related_name='visible_group_profiles', to='auth.group'),
        ),
    ]
