# Generated by Django 4.2.25 on 2026-01-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0008_groupprofile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='isolation_enabled',
            field=models.BooleanField(default=True, help_text='Enable sibling isolation for PRIVATE/MODERATED groups. When enabled, members can only see their hierarchy (ancestors + descendants), not siblings.'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private - members only'), ('public', 'Public - visible to all'), ('moderated', 'Moderated - visible to specific groups')], default='public', help_text="Who can see this group. Children automatically inherit parent's visibility.", max_length=20),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups with view-only access to this group (for auditing/compliance).', related_name='visible_group_profiles', to='auth.group'),
        ),
    ]
