# Generated by Django 4.2.25 on 2026-01-22 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0009_groupprofile_isolation_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='information',
            field=models.TextField(blank=True, default='', help_text='Use Wiki Syntax'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='leaders',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
