# Generated by Django 5.2.14 on 2026-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_groupprofile_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private – members only'), ('public', 'Public – visible to all'), ('moderated', 'Moderated – visible to specific groups')], default='public', help_text="Who can see this group. Children automatically inherit parent's visibility.", max_length=20),
        ),
    ]
