# Generated by Django 5.2.17 on 2026-10-01 16:47

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0011_alter_groupprofile_visibility"),
        ("post_office", "0014_alter_email_recipient_delivery_status_and_more"),
        ("products", "0050_alter_productsupportconfig_group_default_support_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_user", models.BooleanField(default=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("ready", "Ready"),
                            ("accepted", "Accepted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("completed_actions", models.JSONField(default=list)),
                ("failed_action", models.CharField(blank=True, max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("token_version", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField(null=True)),
                ("email_queued_at", models.DateTimeField(null=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_invitations",
                        to="groups.groupprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprise_invitations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productsupportconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprise_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "welcome_email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprise_invitations",
                        to="post_office.email",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("status", "accepted"), _negated=True),
                        name="unique_open_enterprise_invitation_email",
                    )
                ],
            },
        ),
    ]
