# Generated by Django 4.2.25 on 2025-11-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_pinned_article_config'),
        ('customercare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='products.topic'),
        ),
    ]
