# Generated by Django 2.2.18 on 2021-03-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='TwitterAccount',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
