# Generated by Django 4.2.25 on 2025-12-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0002_supportticket_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Ticket Pending Classification'), ('sent', 'Ticket Sent'), ('flagged', 'Ticket under Review'), ('rejected', 'Ticket Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
