# Generated by Django 4.2 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0003_alter_supportticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ticket Pending Classification'),
                    ('sent', 'Ticket Sent'),
                    ('flagged', 'Ticket under Review'),
                    ('rejected', 'Ticket Rejected'),
                    ('processing_failed', 'Ticket Processing Failed'),
                ],
                db_index=True,
                default='pending',
                max_length=20
            ),
        ),
    ]
