# Generated by Django 5.2.11 on 2026-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0004_alter_supportticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='policy_distribution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='update_channel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
