# Generated by Django 5.2.14 on 2026-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0006_rename_status_supportticket_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='zd_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending'), ('hold', 'Hold'), ('solved', 'Solved'), ('closed', 'Closed')], max_length=20, null=True),
        ),
    ]
