# Generated by Django 5.2.14 on 2026-05-20 13:52

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Lower


def normalize_zd_status(apps, schema_editor):
    SupportTicket = apps.get_model("customercare", "SupportTicket")

    uppercase_updated = SupportTicket.objects.exclude(zd_status__isnull=True).update(
        zd_status=Lower(F("zd_status"))
    )

    legacy_waiting_updated = SupportTicket.objects.filter(zd_status="waiting").update(
        zd_status="hold"
    )

    print(
        f"normalize_zd_status: lowercased {uppercase_updated} row(s); "
        f"remapped {legacy_waiting_updated} legacy 'waiting' row(s) to 'hold'."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0007_alter_supportticket_zd_status'),
    ]

    operations = [
        migrations.RunPython(normalize_zd_status, reverse_code=migrations.RunPython.noop),
    ]
