# Generated by Django 5.2.14 on 2026-05-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customercare", "0008_normalize_zd_status_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicketPendingChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("comment", "comment"), ("zd_status", "zd_status")], max_length=30
                    ),
                ),
                ("payload", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("sending", "Sending"), ("failed", "Failed")],
                        default="sending",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_attempted_at", models.DateTimeField(default=None, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_changes",
                        to="customercare.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "kind"), name="unique_kind_per_ticket"
                    )
                ],
            },
        ),
    ]
