# Generated by Django 5.2.14 on 2026-05-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0009_supportticketpendingchange'),
        ('groups', '0010_alter_groupprofile_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='org_group',
            field=models.ForeignKey(blank=True, help_text="Organization that owns this ticket for visibility purposes. Set automatically at submission to the nearest ancestor GroupProfile whose Group is in this product's hybrid_support_groups. Null means a personal ticket — visible only to the submitter.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='groups.groupprofile'),
        ),
    ]
