# Generated by Django 5.2.14 on 2026-05-28 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customercare", "0010_supportticket_org_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupportTicketPendingChange",
        ),
    ]
