# Generated by Django 5.2.14 on 2026-06-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customercare", "0011_delete_supportticketpendingchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="zd_deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the ticket is deleted in Zendesk (soft or permanent).",
                null=True,
            ),
        ),
    ]
