# Generated by Django 5.2.14 on 2026-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0012_supportticket_zd_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(max_length=65535),
        ),
    ]
