# Generated by Django 5.2.17 on 2026-08-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0012_supportticket_zd_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='urgency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
