# Generated by Django 5.2.14 on 2026-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0013_supportticket_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.CharField(max_length=65535),
        ),
    ]
