# Generated by Django 5.2.17 on 2026-09-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercare', '0013_supportticket_urgency'),
        ('groups', '0011_alter_groupprofile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='org_group',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this ticket. Set automatically at submission to the nearest ancestor group configured as a support organization for this product. Null means a personal ticket, visible only to the submitter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='groups.groupprofile'),
        ),
    ]
