# Generated by Django 5.2.17 on 2026-09-25 22:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customercare", "0014_alter_supportticket_org_group"),
        ("groups", "0011_alter_groupprofile_visibility"),
        ("products", "0050_alter_productsupportconfig_group_default_support_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="zd_channel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zendesk channel the ticket was created via (e.g., native_messaging)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="created",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="supportticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("zendesk_ticket_id__isnull", False),
                    models.Q(("zendesk_ticket_id", ""), _negated=True),
                ),
                fields=("zendesk_ticket_id",),
                name="unique_zendesk_ticket_id",
            ),
        ),
    ]
