# Generated by Django 5.2.17 on 2026-10-01 06:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customercare", "0015_supportticket_zd_channel_alter_supportticket_created_and_more"),
        ("groups", "0011_alter_groupprofile_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZendeskOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "zendesk_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "group_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zendesk_organization",
                        to="groups.groupprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
