# Generated by Django 4.2.23 on 2025-07-28 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kitsune.sumo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0026_initial_product_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=None, null=True)),
                ('contribution_timestamp', models.DateTimeField()),
                ('locale', kitsune.sumo.models.LocaleField(choices=[('af', 'Afrikaans'), ('ar', 'عربي'), ('az', 'Azərbaycanca'), ('bg', 'Български'), ('bm', 'Bamanankan'), ('bn', 'বাংলা'), ('bs', 'Bosanski'), ('ca', 'català'), ('cs', 'Čeština'), ('da', 'Dansk'), ('de', 'Deutsch'), ('ee', 'Èʋegbe'), ('el', 'Ελληνικά'), ('en-US', 'English'), ('es', 'Español'), ('et', 'eesti keel'), ('eu', 'Euskara'), ('fa', 'فارسی'), ('fi', 'suomi'), ('fr', 'Français'), ('fy-NL', 'Frysk'), ('ga-IE', 'Gaeilge (Éire)'), ('gl', 'Galego'), ('gn', "Avañe'ẽ"), ('gu-IN', 'ગુજરાતી'), ('ha', 'هَرْشَن هَوْسَ'), ('he', 'עברית'), ('hi-IN', 'हिन्दी (भारत)'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('dsb', 'Dolnoserbšćina'), ('hsb', 'Hornjoserbsce'), ('id', 'Bahasa Indonesia'), ('ig', 'Asụsụ Igbo'), ('it', 'Italiano'), ('ja', '日本語'), ('ka', 'ქართული'), ('km', 'ខ្មែរ'), ('kn', 'ಕನ್ನಡ'), ('ko', '한국어'), ('ln', 'Lingála'), ('lt', 'lietuvių kalba'), ('mg', 'Malagasy'), ('mk', 'Македонски'), ('ml', 'മലയാളം'), ('ms', 'Bahasa Melayu'), ('ne-NP', 'नेपाली'), ('nl', 'Nederlands'), ('no', 'Norsk'), ('pl', 'Polski'), ('pt-BR', 'Português (do Brasil)'), ('pt-PT', 'Português (Europeu)'), ('ro', 'română'), ('ru', 'Русский'), ('si', 'සිංහල'), ('sk', 'slovenčina'), ('sl', 'slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sw', 'Kiswahili'), ('sv', 'Svenska'), ('ta', 'தமிழ்'), ('ta-LK', 'தமிழ் (இலங்கை)'), ('te', 'తెలుగు'), ('th', 'ไทย'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('ur', 'اُردو'), ('vi', 'Tiếng Việt'), ('wo', 'Wolof'), ('xh', 'isiXhosa'), ('yo', 'èdè Yorùbá'), ('zh-CN', '中文 (简体)'), ('zh-TW', '正體中文 (繁體)'), ('zu', 'isiZulu')], default='en-US', max_length=7)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_contributions', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['locale'], name='community_d_locale_80d897_idx'), models.Index(fields=['contribution_timestamp'], name='community_d_contrib_3ff620_idx')],
            },
        ),
    ]
