# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-23 02:00
from __future__ import unicode_literals

from django.db import migrations


def change_locale_bn_bd_to_bn_forwards(apps, schema_editor):
    WikiMetric = apps.get_model('dashboards', 'WikiMetric')

    WikiMetric.objects.all().filter(locale='bn-BD').update(locale='bn')


def change_locale_bn_to_bn_bd_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_auto_20190816_1824'),
    ]

    operations = [
        migrations.RunPython(change_locale_bn_bd_to_bn_forwards,
                             change_locale_bn_to_bn_bd_backwards)
    ]
