# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import kitsune.sumo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_change_locale_bn_BD_to_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimetric',
            name='code',
            field=models.CharField(choices=[('percent_localized_top20', 'Percent Localized: Top 20'), ('percent_localized_top100', 'Percent Localized: Top 100'), ('percent_localized_all', 'Percent Localized: All'), ('active_contributors', 'Monthly Active Contributors')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wikimetric',
            name='locale',
            field=kitsune.sumo.models.LocaleField(blank=True, choices=[('af', 'Afrikaans'), ('ar', 'عربي'), ('az', 'Azərbaycanca'), ('bg', 'Български'), ('bm', 'Bamanankan'), ('bn', 'বাংলা'), ('bs', 'Bosanski'), ('ca', 'català'), ('cs', 'Čeština'), ('da', 'Dansk'), ('de', 'Deutsch'), ('ee', 'Èʋegbe'), ('el', 'Ελληνικά'), ('en-US', 'English'), ('es', 'Español'), ('et', 'eesti keel'), ('eu', 'Euskara'), ('fa', 'فارسی'), ('fi', 'suomi'), ('fr', 'Français'), ('fy-NL', 'Frysk'), ('ga-IE', 'Gaeilge (Éire)'), ('gl', 'Galego'), ('gn', "Avañe'ẽ"), ('gu-IN', 'ગુજરાતી'), ('ha', 'هَرْشَن هَوْسَ'), ('he', 'עברית'), ('hi-IN', 'हिन्दी (भारत)'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('dsb', 'Dolnoserbšćina'), ('hsb', 'Hornjoserbsce'), ('id', 'Bahasa Indonesia'), ('ig', 'Asụsụ Igbo'), ('it', 'Italiano'), ('ja', '日本語'), ('ka', 'ქართული'), ('km', 'ខ្មែរ'), ('kn', 'ಕನ್ನಡ'), ('ko', '한국어'), ('ln', 'Lingála'), ('lt', 'lietuvių kalba'), ('mg', 'Malagasy'), ('mk', 'Македонски'), ('ml', 'മലയാളം'), ('ms', 'Bahasa Melayu'), ('ne-NP', 'नेपाली'), ('nl', 'Nederlands'), ('no', 'Norsk'), ('pl', 'Polski'), ('pt-BR', 'Português (do Brasil)'), ('pt-PT', 'Português (Europeu)'), ('ro', 'română'), ('ru', 'Русский'), ('si', 'සිංහල'), ('sk', 'slovenčina'), ('sl', 'slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sw', 'Kiswahili'), ('sv', 'Svenska'), ('ta', 'தமிழ்'), ('ta-LK', 'தமிழ் (இலங்கை)'), ('te', 'తెలుగు'), ('th', 'ไทย'), ('tn', 'Setswana'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('ur', 'اُردو'), ('vi', 'Tiếng Việt'), ('wo', 'Wolof'), ('xh', 'isiXhosa'), ('yo', 'èdè Yorùbá'), ('zh-CN', '中文 (简体)'), ('zh-TW', '正體中文 (繁體)'), ('zu', 'isiZulu')], db_index=True, default='en-US', max_length=7, null=True),
        ),
    ]
