# Generated by Django 2.2.24 on 2021-07-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_auto_20200629_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidocumentvisits',
            name='period',
            field=models.IntegerField(choices=[(0, 'Last 7 days'), (2, 'Last 30 days'), (3, 'Last 90 days'), (1, 'Last Year')]),
        ),
    ]
