apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sumo-stage-web
  namespace: sumo-stage
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sumo-stage-web
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
