# Enable DB, Redis and ES for local development
development-mode:
  enabled: true
tags:
  local: true
# Default values for sumo production

replicaCount: 1

nameOverride: "sumo-local-dev"
fullnameOverride: "sumo-local-dev"
namespace: "sumo-local-dev"
config:
  celery:
    replicaCount: 1
  cron:
    replicaCount: 1