# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 05:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190419_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fxa_avatar',
            field=models.URLField(blank=True, default=b'', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Some HTML supported: &#x3C;abbr title&#x3E; &#x3C;acronym title&#x3E; &#x3C;b&#x3E; &#x3C;blockquote&#x3E; &#x3C;code&#x3E; &#x3C;em&#x3E; &#x3C;i&#x3E; &#x3C;li&#x3E; &#x3C;ol&#x3E; &#x3C;strong&#x3E; &#x3C;ul&#x3E;. Links are forbidden.', null=True, verbose_name='Biography'),
        ),
    ]
