# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-07 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190917_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Unprocessed'), (2, b'processed'), (3, b'errored')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('event', models.TextField(max_length=4096)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, b'profile deletion'), (2, b'email changed'), (3, b'capabilities changed')], default=None, null=True)),
                ('fxa_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('jwt_id', models.CharField(max_length=256)),
                ('issued_at', models.CharField(max_length=32)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_events', to='users.Profile')),
            ],
        ),
    ]
