# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_accountevent_squashed_0022_auto_20200402_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountevent',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'unprocessed'), (2, b'processed'), (3, b'errored'), (4, b'ignored')], default=1),
        ),
    ]
