# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_accountevent_squashed_0022_auto_20200402_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountevent',
            old_name='events',
            new_name='body',
        ),
        migrations.AddField(
            model_name='profile',
            name='fxa_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountevent',
            name='event_type',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='accountevent',
            name='fxa_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountevent',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'unprocessed'), (2, b'processed'), (3, b'ignored'), (4, b'not-implemented')], default=1),
        ),
    ]
