# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200427_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
