# Generated by Django 2.2.14 on 2020-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200629_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='irc_handle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mozillians',
        ),
        migrations.AddField(
            model_name='profile',
            name='community_mozilla_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Community Portal Username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matrix_handle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Matrix Nickname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='people_mozilla_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='People Directory Username'),
        ),
    ]
