# Generated by Django 2.2.14 on 2020-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200826_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_email',
            field=models.BooleanField(default=False, verbose_name='Make my email address visible to logged in users'),
        ),
    ]
