# Generated by Django 2.2.24 on 2021-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200926_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zendesk_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
