# Generated by Django 2.2.23 on 2021-08-06 09:25

import django.core.validators
from django.db import migrations
import kitsune.sumo.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200926_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=kitsune.sumo.models.utf8mb3TextField(blank=True, help_text='Some HTML supported: &#x3C;abbr title&#x3E; &#x3C;acronym title&#x3E; &#x3C;b&#x3E; &#x3C;blockquote&#x3E; &#x3C;code&#x3E; &#x3C;em&#x3E; &#x3C;i&#x3E; &#x3C;li&#x3E; &#x3C;ol&#x3E; &#x3C;strong&#x3E; &#x3C;ul&#x3E;. Links are forbidden.', html=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=kitsune.sumo.models.utf8mb3CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='community_mozilla_org',
            field=kitsune.sumo.models.utf8mb3CharField(blank=True, default='', max_length=255, verbose_name='Community Portal Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matrix_handle',
            field=kitsune.sumo.models.utf8mb3CharField(blank=True, default='', max_length=255, verbose_name='Matrix Nickname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=kitsune.sumo.models.utf8mb3CharField(blank=True, max_length=255, null=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='people_mozilla_org',
            field=kitsune.sumo.models.utf8mb3CharField(blank=True, default='', max_length=255, verbose_name='People Directory Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=kitsune.sumo.models.utf8mb3CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[\\w]+$', code='Invalid name', message='Please enter correct Twitter Handle')], verbose_name='Twitter Username'),
        ),
    ]
