# Generated by Django 2.2.24 on 2021-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_fxa_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zendesk_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
