# Generated by Django 4.2.16 on 2024-10-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_profile_bio_and_upper_name_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
