# Generated by Django 4.2.16 on 2024-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_remove_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
