# Generated by Django 4.2.20 on 2025-03-13 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0031_alter_accountevent_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular User Account"),
                    ("system", "System Account"),
                    ("admin", "Admin Account"),
                ],
                default="regular",
                max_length=255,
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
