# Generated by Django 4.2.18 on 2025-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_alter_accountevent_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
