# Generated by Django 4.2.20 on 2025-03-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_delete_old_account_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_fxa_migrated",
        ),
    ]
