# Generated by Django 4.2.23 on 2025-07-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_batch_delete_non_migrated_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mozilla_staff',
            field=models.BooleanField(default=False),
        ),
    ]
