# Generated by Django 4.2.25 on 2025-11-03 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_is_mozilla_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='community_mozilla_org',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[\\w]+$', code='Invalid username', message='Please enter a valid username (letters, numbers, and underscores only)')], verbose_name='Community Portal Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='people_mozilla_org',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[\\w]+$', code='Invalid username', message='Please enter a valid username (letters, numbers, and underscores only)')], verbose_name='People Directory Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[\\w]+$', code='Invalid username', message='Please enter a valid username (letters, numbers, and underscores only)')], verbose_name='Twitter Username'),
        ),
    ]
