# Generated by Django 5.2.10 on 2026-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_profile_community_mozilla_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
