# Generated by Django 5.2.14 on 2026-06-17 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_alter_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="csat_email_sent",
        ),
    ]
