##########################################################
### This file is generated by ./manage.py dump_topics. ###
##########################################################
from tower import ugettext as _

_("""mobile""", "KB Topic")
_("""desktop""", "KB Topic")
_("""sync""", "KB Topic")
_("""FxHome""", "KB Topic")
_("""Firefox 6.0.2""", "KB Topic")
_("""Firefox 5.0""", "KB Topic")
_("""general""", "KB Topic")
_("""download""", "KB Topic")
_("""browserID""", "KB Topic")
