#######################################################################
#
# Note: This file is a generated file--do not edit it directly!
# Instead make changes to the appropriate content in the database or
# write up a bug here:
#
#     https://bugzilla.mozilla.org/enter_bug.cgi?product=support.mozilla.org
#
# with the specific lines that are problematic and why.
#
# You can generate this file by running:
#
#     ./manage.py extract_db
#
#######################################################################
from django.utils.translation import pgettext

pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn all you need to know to get started with Firefox.""")
pgettext("DB: products.Topic.title", """Bookmarks and tabs""")
pgettext("DB: products.Topic.description", """Access and organize your favorite webpages easily with bookmarks and tabs""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """Search and navigate easily with these essential features""")
pgettext("DB: products.Topic.title", """Import settings from other browsers""")
pgettext("DB: products.Topic.description", """Learn how to import or export your information between Firefox and another browser""")
pgettext("DB: products.Topic.title", """Video, audio and interactive settings""")
pgettext("DB: products.Topic.description", """Change how Firefox handles videos, animations, music and other interactive content""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Learn how to download Firefox on your desktop devices or move information to and from other browsers.""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Go beyond the basics with these shortcuts and other tips.""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """How to install Firefox and keep it up to date""")
pgettext("DB: products.Topic.title", """Display and appearance""")
pgettext("DB: products.Topic.description", """Learn how to change your toolbar, font sizes and browser colors""")
pgettext("DB: products.Topic.title", """Firefox Sync""")
pgettext("DB: products.Topic.description", """Firefox Sync settings""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Sync information on all your devices""")
pgettext("DB: products.Topic.title", """Manage add-ons""")
pgettext("DB: products.Topic.description", """Enhance Firefox's functionality and appearance with add-ons""")
pgettext("DB: products.Topic.title", """Firefox Hello""")
pgettext("DB: products.Topic.description", """Have video or voice conversations using the Firefox browser""")
pgettext("DB: products.Topic.title", """Chat and share""")
pgettext("DB: products.Topic.description", """Connect on video and share pages with your network""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox yours by adding and managing the features that you want.""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Learn how to keep your information safe and secure with Firefox's private browsing, password features and other security settings.""")
pgettext("DB: products.Topic.title", """Do more with apps""")
pgettext("DB: products.Topic.description", """Install open apps from the Marketplace to add more fun and functionality to your device""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """How to use Firefox's privacy and security features""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Manage preferences and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox yours through customization settings and add-ons""")
pgettext("DB: products.Topic.title", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.description", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.title", """Tab basics""")
pgettext("DB: products.Topic.description", """Tab basics""")
pgettext("DB: products.Topic.title", """Firefox versions and languages""")
pgettext("DB: products.Topic.description", """Firefox versions and languages""")
pgettext("DB: products.Topic.title", """Copy your personal information from one browser to another""")
pgettext("DB: products.Topic.description", """Copy your personal information from one browser to another""")
pgettext("DB: products.Topic.title", """Cookies and cache""")
pgettext("DB: products.Topic.description", """Control the information that Firefox saves""")
pgettext("DB: products.Topic.title", """Passwords, forms, search, and history - control what Firefox suggests""")
pgettext("DB: products.Topic.description", """Passwords, forms, search, and history - control what Firefox suggests""")
pgettext("DB: products.Topic.title", """Firefox controls and buttons""")
pgettext("DB: products.Topic.description", """Firefox controls and buttons""")
pgettext("DB: products.Topic.title", """Tab settings""")
pgettext("DB: products.Topic.description", """Tab settings""")
pgettext("DB: products.Topic.title", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Firefox options, preferences and settings""")
pgettext("DB: products.Topic.description", """Firefox options, preferences and settings""")
pgettext("DB: products.Topic.title", """Bookmark options""")
pgettext("DB: products.Topic.description", """Bookmark options""")
pgettext("DB: products.Topic.title", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.description", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.title", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.description", """How to troubleshoot error messages on Firefox""")
pgettext("DB: products.Topic.title", """Unblock Firefox from connecting to the Internet""")
pgettext("DB: products.Topic.description", """Unblock Firefox from connecting to the Internet""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Videos, sound, pictures and animations don't work""")
pgettext("DB: products.Topic.description", """Videos, sound, pictures and animations don't work""")
pgettext("DB: products.Topic.title", """Firefox is slow or stops working""")
pgettext("DB: products.Topic.description", """Slowness or hanging""")
pgettext("DB: products.Topic.title", """Firefox crashes""")
pgettext("DB: products.Topic.description", """Crashing""")
pgettext("DB: products.Topic.title", """Firefox won't save settings or remember information""")
pgettext("DB: products.Topic.description", """Firefox won't save settings or remember information""")
pgettext("DB: products.Topic.title", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.description", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """Search and navigate easily with these essential features""")
pgettext("DB: products.Topic.title", """How to use Firefox for Android""")
pgettext("DB: products.Topic.description", """How to use Firefox for Android""")
pgettext("DB: products.Topic.title", """What's new in Firefox for Android""")
pgettext("DB: products.Topic.description", """See what new features are available in each release""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """How to install and keep Firefox for Android up to date""")
pgettext("DB: products.Topic.title", """Save, share and sync""")
pgettext("DB: products.Topic.description", """Save, share and synchronize content with other devices""")
pgettext("DB: products.Topic.title", """Cast to your TV""")
pgettext("DB: products.Topic.description", """Learn how to view content on another screen""")
pgettext("DB: products.Topic.title", """Popular articles""")
pgettext("DB: products.Topic.description", """Popular tips and solutions for Firefox for Android""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Control how your information is saved or tracked""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Make Firefox for Android yours with these customization options""")
pgettext("DB: products.Topic.title", """Do more with apps""")
pgettext("DB: products.Topic.description", """Learn to find and install open apps to add more fun and functionality to your device""")
pgettext("DB: products.Topic.title", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.description", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn all you need to know to get Firefox for Android up and running.""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Learn how to install and transfer information to Firefox for Android.""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Tips and tricks""")
pgettext("DB: products.Topic.title", """Use bookmarks""")
pgettext("DB: products.Topic.description", """The basics of using bookmarks""")
pgettext("DB: products.Topic.title", """Firefox Sync settings""")
pgettext("DB: products.Topic.description", """Firefox Sync settings""")
pgettext("DB: products.Topic.title", """Tab basics""")
pgettext("DB: products.Topic.description", """Tab basics""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Keep your information safe with Firefox for Android's privacy and security settings.""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox for Android work the way you want through customization.""")
pgettext("DB: products.Topic.title", """Cookies""")
pgettext("DB: products.Topic.description", """Cookies""")
pgettext("DB: products.Topic.title", """Firefox controls and buttons""")
pgettext("DB: products.Topic.description", """Firefox controls and buttons""")
pgettext("DB: products.Topic.title", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.description", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.title", """Firefox crashes""")
pgettext("DB: products.Topic.description", """Crashing""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Marketplace""")
pgettext("DB: products.Topic.description", """Firefox Marketplace""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other""")
pgettext("DB: products.Topic.title", """Install and Update""")
pgettext("DB: products.Topic.description", """Install and keep Firefox up to date on your iPad, iPhone or iPod Touch.""")
pgettext("DB: products.Topic.title", """Reader View and List""")
pgettext("DB: products.Topic.description", """Read and save web pages in a clutter-free, reader-friendly view""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """How to use bookmarks, tabs and basic Firefox features on your iOS device""")
pgettext("DB: products.Topic.title", """History""")
pgettext("DB: products.Topic.description", """Change your history settings on Firefox for iOS""")
pgettext("DB: products.Topic.title", """How to use Firefox for iOS""")
pgettext("DB: products.Topic.description", """General usage questions""")
pgettext("DB: products.Topic.title", """What's new in Firefox for iOS""")
pgettext("DB: products.Topic.description", """See what features are available in each release.""")
pgettext("DB: products.Topic.title", """Bookmarks and tabs""")
pgettext("DB: products.Topic.description", """Access websites easily with bookmarks and tab features""")
pgettext("DB: products.Topic.title", """Search""")
pgettext("DB: products.Topic.description", """Customize your search settings in Firefox for iOS""")
pgettext("DB: products.Topic.title", """Firefox for iOS is not working as expected""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox for iOS.""")
pgettext("DB: products.Topic.title", """Privacy""")
pgettext("DB: products.Topic.description", """Protect your information with Firefox's privacy settings on iOS""")
pgettext("DB: products.Topic.title", """Sync, save and share""")
pgettext("DB: products.Topic.description", """Share web pages on Firefox for iOS""")
pgettext("DB: products.Topic.title", """Customize preferences""")
pgettext("DB: products.Topic.description", """Customize preferences for Firefox for iOS""")
pgettext("DB: products.Topic.title", """Crashes, errors and other issues""")
pgettext("DB: products.Topic.description", """Troubleshoot error message on Firefox for iOS""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Firefox OS basics""")
pgettext("DB: products.Topic.title", """Basic Features""")
pgettext("DB: products.Topic.description", """Learn the basic functionality for your Firefox OS phone. """)
pgettext("DB: products.Topic.title", """Download and Manage Apps""")
pgettext("DB: products.Topic.description", """Download apps from the Marketplace""")
pgettext("DB: products.Topic.title", """Date and Time""")
pgettext("DB: products.Topic.description", """Setting a date and time on your Firefox OS phone""")
pgettext("DB: products.Topic.title", """Display""")
pgettext("DB: products.Topic.description", """Customize your screen on your Firefox OS device.""")
pgettext("DB: products.Topic.title", """Calling and Contacts""")
pgettext("DB: products.Topic.description", """Learn how to add and manage contacts, as well as make one-to-one or conference calls on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Email and Messages""")
pgettext("DB: products.Topic.description", """Keep in touch with your contacts through email and messaging.""")
pgettext("DB: products.Topic.title", """Music, Photos and Video""")
pgettext("DB: products.Topic.description", """Take pictures, record videos and listen to music on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Marketplace""")
pgettext("DB: products.Topic.description", """How to download, manage and use your favorite apps on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Privacy and security""")
pgettext("DB: products.Topic.description", """Keep your information safe with Firefox OS locks, privacy features and more.""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """Learn how to configure the Internet connection, display and time on your Firefox OS device.""")
pgettext("DB: products.Topic.title", """Internet and Connections""")
pgettext("DB: products.Topic.description", """Learn more about Wi-Fi, Bluetooth and NFC connections.""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Learn how to troubleshoot issues on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """View all Firefox OS articles""")
pgettext("DB: products.Topic.description", """View a list of all Firefox OS articles""")
pgettext("DB: products.Topic.title", """Working with messages""")
pgettext("DB: products.Topic.description", """Firefox OS SMS & email""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Topic.title", """Get Started""")
pgettext("DB: products.Topic.description", """How to use Focus by Firefox""")
pgettext("DB: products.Topic.title", """Get Started""")
pgettext("DB: products.Topic.description", """Klar verwenden""")
pgettext("DB: products.Topic.title", """Learn the Basics. Get Started""")
pgettext("DB: products.Topic.description", """Learn the Basics. Get Started""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Learn tips and shortcuts to help you work faster""")
pgettext("DB: products.Topic.title", """Set up email""")
pgettext("DB: products.Topic.description", """Add and configure your email accounts on Thunderbird""")
pgettext("DB: products.Topic.title", """Install, Migrate and Update""")
pgettext("DB: products.Topic.description", """How to install and keep Thunderbird up to date""")
pgettext("DB: products.Topic.title", """Read, send and organize emails""")
pgettext("DB: products.Topic.description", """Learn how to manage your email messages""")
pgettext("DB: products.Topic.title", """Emails""")
pgettext("DB: products.Topic.description", """Learn to set up accounts, read, send and manage emails""")
pgettext("DB: products.Topic.title", """News Feeds (RSS), Blogs and Social""")
pgettext("DB: products.Topic.description", """Stay up to date with news feeds, blogs and social features""")
pgettext("DB: products.Topic.title", """Contacts""")
pgettext("DB: products.Topic.description", """How to use the address book on Thunderbird""")
pgettext("DB: products.Topic.title", """Calendar""")
pgettext("DB: products.Topic.description", """Related to the Lightning add-on for Calendar""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.title", """Thunderbird versions and languages""")
pgettext("DB: products.Topic.description", """Thunderbird versions and languages""")
pgettext("DB: products.Topic.title", """Passwords, forms and search""")
pgettext("DB: products.Topic.description", """Passwords, forms and search""")
pgettext("DB: products.Topic.title", """Thunderbird controls and buttons """)
pgettext("DB: products.Topic.description", """Learn all about Thunderbird controls and functionality.""")
pgettext("DB: products.Topic.title", """Fix problems with email providers (gmail, Yahoo, etc.) """)
pgettext("DB: products.Topic.description", """Learn how to fix problems with Gmail, Yahoo and other email providers""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Download, install and Migration""")
pgettext("DB: products.Topic.title", """Copy your personal information from  one Thunderbird to another""")
pgettext("DB: products.Topic.description", """Copy your personal information from  one Thunderbird to another""")
pgettext("DB: products.Topic.title", """Tab settings""")
pgettext("DB: products.Topic.description", """Tab settings""")
pgettext("DB: products.Topic.title", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.description", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Keep your information safe with password and security settings""")
pgettext("DB: products.Topic.title", """Customize Thunderbird with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Thunderbird with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Unblock Thunderbird from connecting to the Internet""")
pgettext("DB: products.Topic.description", """Unblock Thunderbird from connecting to the Internet""")
pgettext("DB: products.Topic.title", """Thunderbird options, preferences and settings """)
pgettext("DB: products.Topic.description", """Thunderbird options, preferences and settings """)
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.description", """Troubleshoot error messages on Thunderbird.""")
pgettext("DB: products.Topic.title", """Thunderbird is slow or stops working""")
pgettext("DB: products.Topic.description", """Thunderbird is slow or stops working""")
pgettext("DB: products.Topic.title", """Thunderbird crashes""")
pgettext("DB: products.Topic.description", """Thunderbird crashes""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Thunderbird won't save settings or remember information""")
pgettext("DB: products.Topic.description", """Thunderbird won't save settings or remember information""")
pgettext("DB: products.Topic.title", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.description", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.title", """How To""")
pgettext("DB: products.Topic.description", """Articles that tell you how you can do more with Thunderbird""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other""")
pgettext("DB: products.Topic.title", """Popcorn Maker""")
pgettext("DB: products.Topic.description", """Learn how to remix web video, audio and images into mashups that you can embed on other websites. """)
pgettext("DB: products.Topic.title", """Webmaker for Android""")
pgettext("DB: products.Topic.description", """Get help with the Webmaker app for Android.""")
pgettext("DB: products.Topic.title", """Intro to Open Badges""")
pgettext("DB: products.Topic.description", """Learn the basic about Open Badges""")
pgettext("DB: products.Topic.title", """Thimble""")
pgettext("DB: products.Topic.description", """Learn how to create and share your own webpages quickly and easily.""")
pgettext("DB: products.Topic.title", """BadgeKit""")
pgettext("DB: products.Topic.description", """Learn how to create, assess and issue badges""")
pgettext("DB: products.Topic.title", """X-Ray Goggles""")
pgettext("DB: products.Topic.description", """Learn how to inspect the code behind every webpage.""")
pgettext("DB: products.Topic.title", """Get Involved""")
pgettext("DB: products.Topic.description", """Help the Open Badges community""")
pgettext("DB: products.Topic.title", """Get the most from webmaker.org""")
pgettext("DB: products.Topic.description", """Help or get help on a Webmaker project.""")
pgettext("DB: products.Topic.title", """Earn Badges""")
pgettext("DB: products.Topic.description", """Earn Badges for the skills you learn online and offline""")
pgettext("DB: products.Topic.title", """Events and help for Mentors""")
pgettext("DB: products.Topic.description", """Help teach digital skills and share creative ways of teaching technology.""")
pgettext("DB: products.Topic.title", """Issue Badges""")
pgettext("DB: products.Topic.description", """Issue digital badges to acknowledge new skills and achievements""")
pgettext("DB: products.Topic.title", """Display Badges""")
pgettext("DB: products.Topic.description", """Display your digital badges on your social networks, job sites and your own website.""")
pgettext("DB: products.Topic.title", """Limited Data""")
pgettext("DB: products.Topic.description", """Collect and retain information only when it is necessary to a project or task.""")
pgettext("DB: products.Topic.title", """No Surprises""")
pgettext("DB: products.Topic.description", """Only use and share information about our users for their benefit and as disclosed in our notices.""")
pgettext("DB: products.Topic.title", """User Control""")
pgettext("DB: products.Topic.description", """Do not disclose personal user information without the user’s consent.""")
pgettext("DB: products.Topic.title", """Sensible Settings""")
pgettext("DB: products.Topic.description", """Give our users actionable and informed choices by informing and educating at the point of collection and providing a choice to opt-out whenever possible. """)
pgettext("DB: products.Topic.title", """Defense in Depth""")
pgettext("DB: products.Topic.description", """Make privacy a key factor in selecting and interacting with partners. """)
pgettext("DB: products.Topic.title", """Knowledge Base""")
pgettext("DB: products.Topic.description", """Windows 8 Touch support articles""")
pgettext("DB: products.Topic.title", """How does it work?""")
pgettext("DB: products.Topic.description", """Basics to get started with Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """How to configure and customize Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Problems with websites""")
pgettext("DB: products.Topic.description", """Problems with websites that don't work well in Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other questions with Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn the Basics: get started""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Product.title", """Firefox""")
pgettext("DB: products.Product.description", """Web browser for Windows, Mac and Linux""")
pgettext("DB: products.Product.title", """Firefox for Android""")
pgettext("DB: products.Product.description", """Web browser for Android smartphones and tablets""")
pgettext("DB: products.Product.title", """Firefox for iOS""")
pgettext("DB: products.Product.description", """Firefox for iPhone, iPad and iPod touch devices""")
pgettext("DB: products.Product.title", """Firefox OS""")
pgettext("DB: products.Product.description", """Mobile OS for smartphones""")
pgettext("DB: products.Product.title", """Focus by Firefox""")
pgettext("DB: products.Product.description", """Content blocker for Safari""")
pgettext("DB: products.Product.title", """Klar""")
pgettext("DB: products.Product.description", """Klar""")
pgettext("DB: products.Product.title", """Thunderbird""")
pgettext("DB: products.Product.description", """Email software for Windows, Mac and Linux""")
pgettext("DB: products.Product.title", """Open Badges""")
pgettext("DB: products.Product.description", """A new online standard to recognize and verify learning""")
pgettext("DB: products.Product.title", """Webmaker""")
pgettext("DB: products.Product.description", """Webmaker and other tools for teaching and learning the Web""")
pgettext("DB: products.Product.title", """Privacy and Security""")
pgettext("DB: products.Product.description", """Learn more about Mozilla's privacy and security practices.""")
pgettext("DB: products.Product.title", """Firefox for Windows 8 Touch""")
pgettext("DB: products.Product.description", """Firefox for Windows 8 touch devices""")
pgettext("DB: products.Product.title", """Contributors""")
pgettext("DB: products.Product.description", """Contributor articles""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Administrator""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Buddy of the Month! (10/2015)""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Locale Leader""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Moderator""")
# This is a karma title.
pgettext("DB: karma.Title.name", """SUMO Warrior""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Top 10 Contributor""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Top 25 Contributor""")
pgettext("DB: badger.Badge.title", """2016 L10n Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2016.""")
pgettext("DB: badger.Badge.title", """2016 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2016.""")
pgettext("DB: badger.Badge.title", """2016 KB Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2016.""")
pgettext("DB: badger.Badge.title", """2016 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2016.""")
pgettext("DB: badger.Badge.title", """2015 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2015.""")
pgettext("DB: badger.Badge.title", """2015 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2015.""")
pgettext("DB: badger.Badge.title", """2015 KB Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2015.""")
pgettext("DB: badger.Badge.title", """2015 L10n Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2015.""")
pgettext("DB: badger.Badge.title", """2014 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Army of Awesome 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2014 L10n Badge""")
pgettext("DB: badger.Badge.description", """The SUMO L10n 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2014 KB Badge""")
pgettext("DB: badger.Badge.description", """The SUMO KB 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2014 badge earners for advancing the Mozilla Mission""")
pgettext("DB: badger.Badge.title", """2014 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Forum 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """Firefox 29 Launch Team""")
pgettext("DB: badger.Badge.description", """Awarded to support contributors who contributed (KB article documentation, answering Forum Questions, localizing KB article documentation, tweets, etc) to the launch of Firefox 29, thanks!

Firefox 29 features:

1. Firefox Desktop: Australis new look and feel
AND Firefox Accounts based sync

2. Firefox for Android: Firefox Accounts based sync

MOAR:

https://sumo.etherpad.mozilla.org/sumo-australis-badges""")
pgettext("DB: badger.Badge.title", """2008 L10n Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2008.""")
pgettext("DB: badger.Badge.title", """2009 L10n Badge""")
pgettext("DB: badger.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2009.""")
pgettext("DB: badger.Badge.title", """2012 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Army of Awesome 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2013 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Army of Awesome 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2010 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Army of Awesome 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2011 Army of Awesome Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Army of Awesome 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2012 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Forum 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2010 KB Badge""")
pgettext("DB: badger.Badge.description", """The SUMO KB 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2010 badge earners for advancing the Mozilla Mission""")
pgettext("DB: badger.Badge.title", """2010 L10n Badge""")
pgettext("DB: badger.Badge.description", """The SUMO L10n 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2010 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Forum 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2011 KB Badge""")
pgettext("DB: badger.Badge.description", """The SUMO KB 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2011 L10n Badge""")
pgettext("DB: badger.Badge.description", """The SUMO L10n 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2011 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Forum 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2011 badge earners for advancing the Mozilla Mission!
""")
pgettext("DB: badger.Badge.title", """2012 KB Badge""")
pgettext("DB: badger.Badge.description", """The SUMO KB 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2013 KB Badge""")
pgettext("DB: badger.Badge.description", """The SUMO KB 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2013 L10n Badge""")
pgettext("DB: badger.Badge.description", """The SUMO L10n 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """2013 Support Forum Badge""")
pgettext("DB: badger.Badge.description", """The SUMO Forum 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2013 badge earners for advancing the Mozilla Mission""")
pgettext("DB: badger.Badge.title", """2012 L10n Badge""")
pgettext("DB: badger.Badge.description", """The SUMO L10n 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: badger.Badge.title", """Kitsune Contributor""")
pgettext("DB: badger.Badge.description", """Badge awarded to those who have contributed to the Kitsune code base.""")
