#######################################################################
#
# Note: This file is a generated file--do not edit it directly!
# Instead make changes to the appropriate content in the database or
# write up a bug here:
#
#     https://bugzilla.mozilla.org/enter_bug.cgi?product=support.mozilla.org
#
# with the specific lines that are problematic and why.
#
# You can generate this file by running:
#
#     ./manage.py extract_db
#
#######################################################################
from django.utils.translation import pgettext

# This is a karma title.
pgettext("DB: karma.Title.name", """Top 10 Contributor""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Locale Leader""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Moderator""")
# This is a karma title.
pgettext("DB: karma.Title.name", """SUMO Warrior""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Buddy of the Month! (10/2015)""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Administrator""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Top 25 Contributor""")
pgettext("DB: products.Product.title", """Firefox""")
pgettext("DB: products.Product.description", """Web browser for Windows, Mac and Linux""")
pgettext("DB: products.Product.title", """Firefox for Android""")
pgettext("DB: products.Product.description", """Web browser for Android smartphones and tablets""")
pgettext("DB: products.Product.title", """Firefox for iOS""")
pgettext("DB: products.Product.description", """Firefox for iPhone, iPad and iPod touch devices""")
pgettext("DB: products.Product.title", """Mozilla VPN""")
pgettext("DB: products.Product.description", """VPN for Windows, Mac, Linux, Android, and iOS devices""")
pgettext("DB: products.Product.title", """Firefox Relay""")
pgettext("DB: products.Product.description", """Service that lets you create email masks to hide your real email address""")
pgettext("DB: products.Product.title", """Mozilla Monitor""")
pgettext("DB: products.Product.description", """Find out if your private information has been exposed in a known data breach""")
pgettext("DB: products.Product.title", """Pocket""")
pgettext("DB: products.Product.description", """Discover and save stories for later""")
pgettext("DB: products.Product.title", """MDN Plus""")
pgettext("DB: products.Product.description", """MDN Plus provides a custom user experience for MDN supporters""")
pgettext("DB: products.Product.title", """Firefox Focus""")
pgettext("DB: products.Product.description", """Automatic privacy browser and content blocker""")
pgettext("DB: products.Product.title", """Firefox Private Network""")
pgettext("DB: products.Product.description", """No longer available as of June 20th, 2023""")
pgettext("DB: products.Product.title", """Hubs""")
pgettext("DB: products.Product.description", """Collaborate and engage with each other through spatialized audio and with media from around the web.""")
pgettext("DB: products.Product.title", """Firefox for Enterprise""")
pgettext("DB: products.Product.description", """Firefox Quantum for businesses""")
pgettext("DB: products.Product.title", """Thunderbird""")
pgettext("DB: products.Product.description", """Email software for Windows, Mac and Linux""")
pgettext("DB: products.Product.title", """Thunderbird for Android""")
pgettext("DB: products.Product.description", """Email app for Android smartphones and tablets""")
pgettext("DB: products.Product.title", """Contributors""")
pgettext("DB: products.Product.description", """Contributor articles""")
pgettext("DB: products.Product.title", """Firefox for Amazon Devices""")
pgettext("DB: products.Product.description", """Browser for Amazon devices""")
pgettext("DB: products.Product.title", """Firefox for Android Beta""")
pgettext("DB: products.Product.description", """Early version of an experimental Firefox browser for Android.""")
pgettext("DB: products.Product.title", """Firefox for Android (ESR)""")
pgettext("DB: products.Product.description", """Older version of Firefox for Android (no longer supported)""")
pgettext("DB: products.Product.title", """Firefox for Fire TV""")
pgettext("DB: products.Product.description", """Browser for Amazon Fire TV""")
pgettext("DB: products.Product.title", """Firefox for Windows 8 Touch""")
pgettext("DB: products.Product.description", """Firefox for Windows 8 touch devices""")
pgettext("DB: products.Product.title", """Firefox Klar""")
pgettext("DB: products.Product.description", """Was ist Firefox Klar?""")
pgettext("DB: products.Product.title", """Firefox Lite""")
pgettext("DB: products.Product.description", """Mobile browser for Indonesia, India, The Philippines, and Thailand""")
pgettext("DB: products.Product.title", """Firefox Lockwise""")
pgettext("DB: products.Product.description", """Mobile app that gives you access to passwords you've saved to Firefox.""")
pgettext("DB: products.Product.title", """Firefox OS""")
pgettext("DB: products.Product.description", """Mobile OS for smartphones""")
pgettext("DB: products.Product.title", """Firefox Reality""")
pgettext("DB: products.Product.description", """Web browser for virtual reality headsets""")
pgettext("DB: products.Product.title", """Firefox ScreenshotGo""")
pgettext("DB: products.Product.description", """Screenshot app for mobile""")
pgettext("DB: products.Product.title", """Firefox Send""")
pgettext("DB: products.Product.description", """An app for sending files to anyone.""")
pgettext("DB: products.Product.title", """Mozilla Account""")
pgettext("DB: products.Product.description", """Privacy-first products for desktop and mobile""")
pgettext("DB: products.Product.title", """Open Badges""")
pgettext("DB: products.Product.description", """A new online standard to recognize and verify learning""")
pgettext("DB: products.Product.title", """Privacy and Security""")
pgettext("DB: products.Product.description", """Learn more about Mozilla's privacy and security practices.""")
pgettext("DB: products.Product.title", """Webmaker""")
pgettext("DB: products.Product.description", """Webmaker and other tools for teaching and learning the Web""")
pgettext("DB: products.Topic.title", """3rd party sign in""")
pgettext("DB: products.Topic.description", """Troubleshoot 3rd party sign in issues.""")
pgettext("DB: products.Topic.title", """About Data Sharing""")
pgettext("DB: products.Topic.description", """In order to process or provide our products and services to you, we share your information with the following business partners. These entities are contractually obligated to handle the data in ways that are approved by Mozilla.""")
pgettext("DB: products.Topic.title", """Abuse""")
pgettext("DB: products.Topic.description", """Tools to make your event a safe place for your guests""")
pgettext("DB: products.Topic.title", """Accessibility""")
pgettext("DB: products.Topic.description", """Learn about Mozilla products’ accessibility features and settings for better usability.""")
pgettext("DB: products.Topic.title", """Account management""")
pgettext("DB: products.Topic.description", """Manage your account settings and preferences.""")
pgettext("DB: products.Topic.title", """Account recovery""")
pgettext("DB: products.Topic.description", """Recover your account if you lose access to it or encounter issues.""")
pgettext("DB: products.Topic.title", """Accounts""")
pgettext("DB: products.Topic.description", """Change account and settings for Private Network.""")
pgettext("DB: products.Topic.title", """Accounts""")
pgettext("DB: products.Topic.description", """Manage your Firefox Monitor account""")
pgettext("DB: products.Topic.title", """Accounts""")
pgettext("DB: products.Topic.description", """Manage your accounts and profiles for Mozilla’s products and services.""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """How to sign in and activate more features""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """Manage your Firefox Relay account.""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """Manage your MDN Plus account.""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """Find solutions on managing your account""")
pgettext("DB: products.Topic.title", """Add device""")
pgettext("DB: products.Topic.description", """Troubleshoot add device issues.""")
pgettext("DB: products.Topic.title", """Add-ons, extensions, and themes""")
pgettext("DB: products.Topic.description", """Enhance product functionality with add-ons, extensions, and themes.""")
pgettext("DB: products.Topic.title", """Advanced and experimental features""")
pgettext("DB: products.Topic.description", """Learn tips beyond the basics and try features before they're released to the public.""")
pgettext("DB: products.Topic.title", """Advanced Settings""")
pgettext("DB: products.Topic.description", """Do more with Firefox Preview""")
pgettext("DB: products.Topic.title", """Alerts""")
pgettext("DB: products.Topic.description", """Troubleshoot alerts issues.""")
pgettext("DB: products.Topic.title", """App crash""")
pgettext("DB: products.Topic.description", """Troubleshoot app crash issues.""")
pgettext("DB: products.Topic.title", """App responsiveness""")
pgettext("DB: products.Topic.description", """Troubleshoot app responsiveness issues.""")
pgettext("DB: products.Topic.title", """Article View""")
pgettext("DB: products.Topic.description", """Comfortably read web pages without distractions.""")
pgettext("DB: products.Topic.title", """Attachments""")
pgettext("DB: products.Topic.description", """Learn how to use and manage email attachments.""")
pgettext("DB: products.Topic.title", """Audio and Video""")
pgettext("DB: products.Topic.description", """Everything you need to know about audio and video.""")
pgettext("DB: products.Topic.title", """Autoconfiguration""")
pgettext("DB: products.Topic.description", """How to configure Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Autofill""")
pgettext("DB: products.Topic.description", """Automatically fill your personal information into form fields and more.""")
pgettext("DB: products.Topic.title", """Avatars""")
pgettext("DB: products.Topic.description", """How to set up and navigate using your virtual identity""")
pgettext("DB: products.Topic.title", """Backup data""")
pgettext("DB: products.Topic.description", """From passwords to bookmarks, discover ways to back up your important data.""")
pgettext("DB: products.Topic.title", """Backup, recovery, and sync""")
pgettext("DB: products.Topic.description", """Sync your data across different platforms and devices, backup what’s important, and recover it if it’s lost.""")
pgettext("DB: products.Topic.title", """Back up your data""")
pgettext("DB: products.Topic.description", """Use Firefox Sync to backup and transfer your data.""")
pgettext("DB: products.Topic.title", """BadgeKit""")
pgettext("DB: products.Topic.description", """Learn how to create, assess and issue badges""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """How to use bookmarks, tabs and basic Firefox features on your iOS device""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """Search and navigate easily with these essential features""")
pgettext("DB: products.Topic.title", """Basic Features""")
pgettext("DB: products.Topic.description", """Learn the basic functionality for your Firefox OS phone. """)
pgettext("DB: products.Topic.title", """Billing and subscriptions""")
pgettext("DB: products.Topic.description", """Manage your subscriptions and payment details for Mozilla’s premium products.""")
pgettext("DB: products.Topic.title", """Billing inquiry""")
pgettext("DB: products.Topic.description", """Inquire about your billing.""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your subscription to Firefox Relay Premium""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your payment and subscription""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your MDN Plus subscription.""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your payment and subscription""")
pgettext("DB: products.Topic.title", """Blocked application/service/website""")
pgettext("DB: products.Topic.description", """Troubleshoot blocked application/service/website issues.""")
pgettext("DB: products.Topic.title", """Bookmark options""")
pgettext("DB: products.Topic.description", """Bookmark options""")
pgettext("DB: products.Topic.title", """Bookmarks""")
pgettext("DB: products.Topic.description", """Back up your Firefox bookmarks.""")
pgettext("DB: products.Topic.title", """Bookmarks""")
pgettext("DB: products.Topic.description", """Save and organize your favorite web content with bookmarks.""")
pgettext("DB: products.Topic.title", """Bookmarks and tabs""")
pgettext("DB: products.Topic.description", """Access and organize your favorite webpages easily with bookmarks and tabs""")
pgettext("DB: products.Topic.title", """Bookmarks and tabs""")
pgettext("DB: products.Topic.description", """Access websites easily with bookmarks and tab features""")
pgettext("DB: products.Topic.title", """Browse""")
pgettext("DB: products.Topic.description", """Explore how to navigate the web efficiently and effectively with Mozilla’s products.""")
pgettext("DB: products.Topic.title", """Browser appearance""")
pgettext("DB: products.Topic.description", """Troubleshoot browser appearance issues.""")
pgettext("DB: products.Topic.title", """Browser security""")
pgettext("DB: products.Topic.description", """Troubleshoot browser security issues.""")
pgettext("DB: products.Topic.title", """Browsing""")
pgettext("DB: products.Topic.description", """Surf and navigate the Web on Firefox Preview""")
pgettext("DB: products.Topic.title", """Calendar""")
pgettext("DB: products.Topic.description", """Integrated calendar component of Thunderbird""")
pgettext("DB: products.Topic.title", """Calendar""")
pgettext("DB: products.Topic.description", """Manage your calendar events and schedules.""")
pgettext("DB: products.Topic.title", """Calling and Contacts""")
pgettext("DB: products.Topic.description", """Learn how to add and manage contacts, as well as make one-to-one or conference calls on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Camera (point of view)""")
pgettext("DB: products.Topic.description", """How to change your camera settings in Hubs""")
pgettext("DB: products.Topic.title", """Cancellation""")
pgettext("DB: products.Topic.description", """Troubleshoot cancellation issues.""")
pgettext("DB: products.Topic.title", """Can't select server""")
pgettext("DB: products.Topic.description", """Troubleshoot can't select server issues.""")
pgettext("DB: products.Topic.title", """Cast to your TV""")
pgettext("DB: products.Topic.description", """Learn how to view content on another screen""")
pgettext("DB: products.Topic.title", """Changing your settings""")
pgettext("DB: products.Topic.description", """Change Firefox's behavior.""")
pgettext("DB: products.Topic.title", """Chat and share""")
pgettext("DB: products.Topic.description", """Connect on video and share pages with your network""")
pgettext("DB: products.Topic.title", """Connection failure""")
pgettext("DB: products.Topic.description", """Troubleshoot connection failure issues.""")
pgettext("DB: products.Topic.title", """Connectivity""")
pgettext("DB: products.Topic.description", """Troubleshoot connectivity issues.""")
pgettext("DB: products.Topic.title", """Connectivity""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with connectivity.""")
pgettext("DB: products.Topic.title", """Contacts""")
pgettext("DB: products.Topic.description", """How to use the address book on Thunderbird""")
pgettext("DB: products.Topic.title", """Contacts""")
pgettext("DB: products.Topic.description", """Manage your email contacts.""")
pgettext("DB: products.Topic.title", """Controls (movement)""")
pgettext("DB: products.Topic.description", """How to navigate through virtual spaces""")
pgettext("DB: products.Topic.title", """Cookies""")
pgettext("DB: products.Topic.description", """Cookies""")
pgettext("DB: products.Topic.title", """Cookies""")
pgettext("DB: products.Topic.description", """Troubleshoot cookies issues.""")
pgettext("DB: products.Topic.title", """Cookies and cache""")
pgettext("DB: products.Topic.description", """Control the information that Firefox saves""")
pgettext("DB: products.Topic.title", """Copy your personal information from one browser to another""")
pgettext("DB: products.Topic.description", """Copy your personal information from one browser to another""")
pgettext("DB: products.Topic.title", """Copy your personal information from  one Thunderbird to another""")
pgettext("DB: products.Topic.description", """Copy your personal information from  one Thunderbird to another""")
pgettext("DB: products.Topic.title", """Crashes, errors and other issues""")
pgettext("DB: products.Topic.description", """Troubleshoot error message on Firefox for iOS""")
pgettext("DB: products.Topic.title", """Crashing and slow performance""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with app crashes or slow performance.""")
pgettext("DB: products.Topic.title", """Create & edit articles""")
pgettext("DB: products.Topic.description", """Learn how to create and edit knowledge base articles.""")
pgettext("DB: products.Topic.title", """Creators & developers""")
pgettext("DB: products.Topic.description", """Where to find resources for advanced customization""")
pgettext("DB: products.Topic.title", """Customization""")
pgettext("DB: products.Topic.description", """Customize product appearance and functionality to suit your preferences.""")
pgettext("DB: products.Topic.title", """Customization of Firefox in an enterprise environment""")
pgettext("DB: products.Topic.description", """Customization of Firefox in an enterprise environment""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox yours by adding and managing the features that you want.""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox for Android work the way you want through customization.""")
pgettext("DB: products.Topic.title", """Customized reader""")
pgettext("DB: products.Topic.description", """Troubleshoot customized reader issues.""")
pgettext("DB: products.Topic.title", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Customize settings and preferences""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Customize settings and preferences""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Customize preferences for Firefox for iOS""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Customize settings and preferences""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Make Firefox for Android yours with these customization options""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Customize settings and preferences""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Make Firefox yours through customization settings and add-ons""")
pgettext("DB: products.Topic.title", """Customize Thunderbird with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Thunderbird with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Dashboard""")
pgettext("DB: products.Topic.description", """Troubleshoot dashboard issues.""")
pgettext("DB: products.Topic.title", """Data brokers""")
pgettext("DB: products.Topic.description", """Troubleshoot data brokers issues.""")
pgettext("DB: products.Topic.title", """Data removal""")
pgettext("DB: products.Topic.description", """Remove your data from Mozilla’s products.""")
pgettext("DB: products.Topic.title", """Date and Time""")
pgettext("DB: products.Topic.description", """Setting a date and time on your Firefox OS phone""")
pgettext("DB: products.Topic.title", """Declined payment""")
pgettext("DB: products.Topic.description", """Troubleshoot declined payment issues.""")
pgettext("DB: products.Topic.title", """Defense in Depth""")
pgettext("DB: products.Topic.description", """Make privacy a key factor in selecting and interacting with partners. """)
pgettext("DB: products.Topic.title", """Deploy""")
pgettext("DB: products.Topic.description", """Deployment of Firefox in an enterprise environment""")
pgettext("DB: products.Topic.title", """Device permissions""")
pgettext("DB: products.Topic.description", """Troubleshoot device permissions issues.""")
pgettext("DB: products.Topic.title", """Display""")
pgettext("DB: products.Topic.description", """Customize your screen on your Firefox OS device.""")
pgettext("DB: products.Topic.title", """Display and appearance""")
pgettext("DB: products.Topic.description", """Learn how to change your toolbar, font sizes and browser colors""")
pgettext("DB: products.Topic.title", """Display Badges""")
pgettext("DB: products.Topic.description", """Display your digital badges on your social networks, job sites and your own website.""")
pgettext("DB: products.Topic.title", """Do more with apps""")
pgettext("DB: products.Topic.description", """Install open apps from the Marketplace to add more fun and functionality to your device""")
pgettext("DB: products.Topic.title", """Do more with apps""")
pgettext("DB: products.Topic.description", """Learn to find and install open apps to add more fun and functionality to your device""")
pgettext("DB: products.Topic.title", """Download and Manage Apps""")
pgettext("DB: products.Topic.description", """Download apps from the Marketplace""")
pgettext("DB: products.Topic.title", """Download and save""")
pgettext("DB: products.Topic.description", """Manage your downloaded files and saved content""")
pgettext("DB: products.Topic.title", """Download failure""")
pgettext("DB: products.Topic.description", """Troubleshoot download failure issues.""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Learn how to download Firefox on your desktop devices or move information to and from other browsers.""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Learn how to install and transfer information to Firefox for Android.""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Download, install and Migration""")
pgettext("DB: products.Topic.title", """Downloads""")
pgettext("DB: products.Topic.description", """Manage and troubleshoot your downloads.""")
pgettext("DB: products.Topic.title", """Download & Setup""")
pgettext("DB: products.Topic.description", """Start using Mozilla VPN.""")
pgettext("DB: products.Topic.title", """Earn Badges""")
pgettext("DB: products.Topic.description", """Earn Badges for the skills you learn online and offline""")
pgettext("DB: products.Topic.title", """Edit account details""")
pgettext("DB: products.Topic.description", """Edit your account details.""")
pgettext("DB: products.Topic.title", """Editorial guidelines""")
pgettext("DB: products.Topic.description", """Learn more about to contribute to our knowledge base articles.""")
pgettext("DB: products.Topic.title", """Email and Messages""")
pgettext("DB: products.Topic.description", """Keep in touch with your contacts through email and messaging.""")
pgettext("DB: products.Topic.title", """Email and messaging""")
pgettext("DB: products.Topic.description", """Read, send, and manage your emails and messages.""")
pgettext("DB: products.Topic.title", """Email and phone masking""")
pgettext("DB: products.Topic.description", """Troubleshoot email and phone masking issues.""")
pgettext("DB: products.Topic.title", """Email forwarding""")
pgettext("DB: products.Topic.description", """Troubleshoot email forwarding issues.""")
pgettext("DB: products.Topic.title", """Email masking""")
pgettext("DB: products.Topic.description", """Troubleshoot email masking issues.""")
pgettext("DB: products.Topic.title", """Emails""")
pgettext("DB: products.Topic.description", """Emails""")
pgettext("DB: products.Topic.title", """Emails""")
pgettext("DB: products.Topic.description", """Learn to set up accounts, read, send and manage emails""")
pgettext("DB: products.Topic.title", """Email trackers""")
pgettext("DB: products.Topic.description", """Troubleshoot email trackers issues.""")
pgettext("DB: products.Topic.title", """Email verify lockout""")
pgettext("DB: products.Topic.description", """Troubleshoot email verify lockout issues.""")
pgettext("DB: products.Topic.title", """Encryption""")
pgettext("DB: products.Topic.description", """Use encryption features to keep yourself and your data secure.""")
pgettext("DB: products.Topic.title", """Error codes""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with error codes.""")
pgettext("DB: products.Topic.title", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.description", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.title", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.description", """How to troubleshoot error messages on Firefox""")
pgettext("DB: products.Topic.title", """ESR""")
pgettext("DB: products.Topic.description", """Troubleshoot ESR issues.""")
pgettext("DB: products.Topic.title", """Events""")
pgettext("DB: products.Topic.description", """Troubleshoot events issues.""")
pgettext("DB: products.Topic.title", """Events and help for Mentors""")
pgettext("DB: products.Topic.description", """Help teach digital skills and share creative ways of teaching technology.""")
pgettext("DB: products.Topic.title", """Explore""")
pgettext("DB: products.Topic.description", """Learn about Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Extensions""")
pgettext("DB: products.Topic.description", """Troubleshoot extensions issues.""")
pgettext("DB: products.Topic.title", """Firefox controls and buttons""")
pgettext("DB: products.Topic.description", """Firefox controls and buttons""")
pgettext("DB: products.Topic.title", """Firefox crashes""")
pgettext("DB: products.Topic.description", """Crashing""")
pgettext("DB: products.Topic.title", """Firefox crashes""")
pgettext("DB: products.Topic.description", """Crashing""")
pgettext("DB: products.Topic.title", """Firefox Focus for Android""")
pgettext("DB: products.Topic.description", """Privacy browser for Android""")
pgettext("DB: products.Topic.title", """Firefox Focus for iOS""")
pgettext("DB: products.Topic.description", """Firefox Focus for iOS""")
pgettext("DB: products.Topic.title", """Firefox for Echo Show""")
pgettext("DB: products.Topic.description", """Browser for the Amazon Echo Show""")
pgettext("DB: products.Topic.title", """Firefox for families""")
pgettext("DB: products.Topic.description", """Customize Firefox to keep your family safe and secure""")
pgettext("DB: products.Topic.title", """Firefox for Fire TV""")
pgettext("DB: products.Topic.description", """Browser for the Amazon Fire TV.""")
pgettext("DB: products.Topic.title", """Firefox for iOS is not working as expected""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox for iOS.""")
pgettext("DB: products.Topic.title", """Firefox Hello""")
pgettext("DB: products.Topic.description", """Have video or voice conversations using the Firefox browser""")
pgettext("DB: products.Topic.title", """Firefox is slow or stops working""")
pgettext("DB: products.Topic.description", """Slowness or hanging""")
pgettext("DB: products.Topic.title", """Firefox Klar for Android""")
pgettext("DB: products.Topic.description", """Privacy browser for Android""")
pgettext("DB: products.Topic.title", """Firefox Klar for iOS""")
pgettext("DB: products.Topic.description", """Privacy browser for iOS""")
pgettext("DB: products.Topic.title", """Firefox options, preferences and settings""")
pgettext("DB: products.Topic.description", """Firefox options, preferences and settings""")
pgettext("DB: products.Topic.title", """Firefox settings""")
pgettext("DB: products.Topic.description", """Privacy and personalization""")
pgettext("DB: products.Topic.title", """Firefox Sync""")
pgettext("DB: products.Topic.description", """Firefox Sync settings""")
pgettext("DB: products.Topic.title", """Firefox Sync settings""")
pgettext("DB: products.Topic.description", """Firefox Sync settings""")
pgettext("DB: products.Topic.title", """Firefox versions and languages""")
pgettext("DB: products.Topic.description", """Firefox versions and languages""")
pgettext("DB: products.Topic.title", """Firefox won't save settings or remember information""")
pgettext("DB: products.Topic.description", """Firefox won't save settings or remember information""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox Fire TV""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with Firefox Lockwise""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox Lite.""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot slowness, crashing and error messages.""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Learn how to troubleshoot issues on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Fix problems with email providers (gmail, Yahoo, etc.) """)
pgettext("DB: products.Topic.description", """Learn how to fix problems with Gmail, Yahoo and other email providers""")
pgettext("DB: products.Topic.title", """Fix problems with Firefox Preview""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with Firefox Preview""")
pgettext("DB: products.Topic.title", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.description", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.title", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.description", """Troubleshoot error messages on Thunderbird.""")
pgettext("DB: products.Topic.title", """Forwarded message notification""")
pgettext("DB: products.Topic.description", """Troubleshoot forwarded message notification issues.""")
pgettext("DB: products.Topic.title", """Free email masking""")
pgettext("DB: products.Topic.description", """Learn the basics of Firefox Relay.""")
pgettext("DB: products.Topic.title", """Full text search""")
pgettext("DB: products.Topic.description", """Troubleshoot full text search issues.""")
pgettext("DB: products.Topic.title", """General contribution""")
pgettext("DB: products.Topic.description", """Learn how you can contribute to SUMO in general.""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Get Involved""")
pgettext("DB: products.Topic.description", """Help the Open Badges community""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Download Firefox and safely browse the web""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Everything you need to know to use Firefox Lite.""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Firefox OS basics""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Get Started with Firefox for Fire TV""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """How to use Firefox Reality""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Learn the basics""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Learn the basics about ScreenshotGo""")
pgettext("DB: products.Topic.title", """Get Started""")
pgettext("DB: products.Topic.description", """Klar verwenden""")
pgettext("DB: products.Topic.title", """Get the most from webmaker.org""")
pgettext("DB: products.Topic.description", """Help or get help on a Webmaker project.""")
pgettext("DB: products.Topic.title", """Getting started""")
pgettext("DB: products.Topic.description", """Getting started with Monitor Data Removal""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """Getting started with MDN Plus.""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """Learn the basics of Firefox Relay.""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """Learn the basics of Mozilla VPN.""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """New to Pocket? Start here!""")
pgettext("DB: products.Topic.title", """Help articles""")
pgettext("DB: products.Topic.description", """Topic for any articles related to the Knowledge Base (help articles) contribution.""")
pgettext("DB: products.Topic.title", """Highlighting""")
pgettext("DB: products.Topic.description", """Troubleshoot highlighting issues.""")
pgettext("DB: products.Topic.title", """History""")
pgettext("DB: products.Topic.description", """Change your history settings on Firefox for iOS""")
pgettext("DB: products.Topic.title", """History""")
pgettext("DB: products.Topic.description", """View and manage your browsing history.""")
pgettext("DB: products.Topic.title", """Home screen""")
pgettext("DB: products.Topic.description", """Add Mozilla’s products to your home screen for easy access.""")
pgettext("DB: products.Topic.title", """Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Topic.title", """How does it work?""")
pgettext("DB: products.Topic.description", """Basics to get started with Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """How do I use Firefox Preview?""")
pgettext("DB: products.Topic.description", """Get help with using features in Firefox Preview.""")
pgettext("DB: products.Topic.title", """How To""")
pgettext("DB: products.Topic.description", """Articles that tell you how you can do more with Thunderbird""")
pgettext("DB: products.Topic.title", """How to use Firefox""")
pgettext("DB: products.Topic.description", """How to browse, search and customize your settings""")
pgettext("DB: products.Topic.title", """How to use Firefox for Android""")
pgettext("DB: products.Topic.description", """How to use Firefox for Android""")
pgettext("DB: products.Topic.title", """How to use Firefox for iOS""")
pgettext("DB: products.Topic.description", """General usage questions""")
pgettext("DB: products.Topic.title", """Identity""")
pgettext("DB: products.Topic.description", """How to create and edit your identity in Hubs""")
pgettext("DB: products.Topic.title", """Images""")
pgettext("DB: products.Topic.description", """Troubleshoot images issues.""")
pgettext("DB: products.Topic.title", """Images and documents""")
pgettext("DB: products.Topic.description", """Everything you need to know about images and documents.""")
pgettext("DB: products.Topic.title", """Import and export email""")
pgettext("DB: products.Topic.description", """Import and export your emails for backup or transfer.""")
pgettext("DB: products.Topic.title", """Import and export settings""")
pgettext("DB: products.Topic.description", """Learn how to import and export product settings for easy setup and migration.""")
pgettext("DB: products.Topic.title", """Import settings from other browsers""")
pgettext("DB: products.Topic.description", """Learn how to import or export your information between Firefox and another browser""")
pgettext("DB: products.Topic.title", """Install""")
pgettext("DB: products.Topic.description", """Learn about how to install Mozilla’s products on your devices.""")
pgettext("DB: products.Topic.title", """Install and manage add-ons""")
pgettext("DB: products.Topic.description", """Add-ons let you customize and add features to Firefox.""")
pgettext("DB: products.Topic.title", """Install and manage add-ons""")
pgettext("DB: products.Topic.description", """Install and manage add-ons""")
pgettext("DB: products.Topic.title", """Install and manage add-ons""")
pgettext("DB: products.Topic.description", """Install and manage add-ons""")
pgettext("DB: products.Topic.title", """Install and manage add-ons""")
pgettext("DB: products.Topic.description", """Install and manage add-ons""")
pgettext("DB: products.Topic.title", """Install and manage add-ons""")
pgettext("DB: products.Topic.description", """Install and manage add-ons""")
pgettext("DB: products.Topic.title", """Install and set up""")
pgettext("DB: products.Topic.description", """Sync your logins across Firefox and your apps.""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """Download and install the mobile app on your device.""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """Install and update""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """How to install Firefox and keep it up to date""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """Install and update""")
pgettext("DB: products.Topic.title", """Install and Update""")
pgettext("DB: products.Topic.description", """Install and keep Firefox up to date on your iPad, iPhone or iPod Touch.""")
pgettext("DB: products.Topic.title", """Installation""")
pgettext("DB: products.Topic.description", """How to install Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Installation and updates""")
pgettext("DB: products.Topic.description", """Learn how to install your favorite Mozilla products and keep them updated.""")
pgettext("DB: products.Topic.title", """Install failure""")
pgettext("DB: products.Topic.description", """Troubleshoot install failure issues.""")
pgettext("DB: products.Topic.title", """Install, Migrate and Update""")
pgettext("DB: products.Topic.description", """How to install and keep Thunderbird up to date""")
pgettext("DB: products.Topic.title", """Instant messaging""")
pgettext("DB: products.Topic.description", """Features and functionality to use with instant messaging.""")
pgettext("DB: products.Topic.title", """Internet and Connections""")
pgettext("DB: products.Topic.description", """Learn more about Wi-Fi, Bluetooth and NFC connections.""")
pgettext("DB: products.Topic.title", """Intro to Open Badges""")
pgettext("DB: products.Topic.description", """Learn the basic about Open Badges""")
pgettext("DB: products.Topic.title", """Invitations""")
pgettext("DB: products.Topic.description", """Invite guests to your virtual room""")
pgettext("DB: products.Topic.title", """Issue Badges""")
pgettext("DB: products.Topic.description", """Issue digital badges to acknowledge new skills and achievements""")
pgettext("DB: products.Topic.title", """Junk email and spam""")
pgettext("DB: products.Topic.description", """Identify and manage junk email and spam.""")
pgettext("DB: products.Topic.title", """Knowledge Base""")
pgettext("DB: products.Topic.description", """Windows 8 Touch support articles""")
pgettext("DB: products.Topic.title", """Languages""")
pgettext("DB: products.Topic.description", """Change and manage language settings in Mozilla’s products.""")
pgettext("DB: products.Topic.title", """Launch failure""")
pgettext("DB: products.Topic.description", """Troubleshoot launch failure issues.""")
pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn all you need to know to get started with Firefox.""")
pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn all you need to know to get Firefox for Android up and running.""")
pgettext("DB: products.Topic.title", """Learn the Basics. Get Started""")
pgettext("DB: products.Topic.description", """Learn the Basics. Get Started""")
pgettext("DB: products.Topic.title", """Library""")
pgettext("DB: products.Topic.description", """Manage bookmarks and history""")
pgettext("DB: products.Topic.title", """Links""")
pgettext("DB: products.Topic.description", """Use web links in Mozilla’s products.""")
pgettext("DB: products.Topic.title", """Linux""")
pgettext("DB: products.Topic.description", """Deploy Firefox on your organization's Linux machines.""")
pgettext("DB: products.Topic.title", """Listen""")
pgettext("DB: products.Topic.description", """Listen to your favorite podcasts and audiobooks.""")
pgettext("DB: products.Topic.title", """Loading speed""")
pgettext("DB: products.Topic.description", """Troubleshoot loading speed issues.""")
pgettext("DB: products.Topic.title", """Localization""")
pgettext("DB: products.Topic.description", """Topic for any articles related to article localization (L10n) contribution.""")
pgettext("DB: products.Topic.title", """Location""")
pgettext("DB: products.Topic.description", """Change your location.""")
pgettext("DB: products.Topic.title", """Mac""")
pgettext("DB: products.Topic.description", """Deploy Firefox on your organization's Mac computers""")
pgettext("DB: products.Topic.title", """Manage account""")
pgettext("DB: products.Topic.description", """How to change your account settings""")
pgettext("DB: products.Topic.title", """Manage add-ons""")
pgettext("DB: products.Topic.description", """Working with add-ons on Firefox for your organization.""")
pgettext("DB: products.Topic.title", """Manage billing""")
pgettext("DB: products.Topic.description", """Manage your payment details and billing information.""")
pgettext("DB: products.Topic.title", """Manage certificates""")
pgettext("DB: products.Topic.description", """Set up certificates on Firefox for your organization.""")
pgettext("DB: products.Topic.title", """Manage passwords & emails""")
pgettext("DB: products.Topic.description", """Change your account password or primary email address""")
pgettext("DB: products.Topic.title", """Manage settings and logins""")
pgettext("DB: products.Topic.description", """Setting up your device to work with Firefox Lockwise""")
pgettext("DB: products.Topic.title", """Manage settings via policy""")
pgettext("DB: products.Topic.description", """Change Firefox's settings using policies.""")
pgettext("DB: products.Topic.title", """Manage subscriptions""")
pgettext("DB: products.Topic.description", """Manage or cancel your Mozilla subscriptions.""")
pgettext("DB: products.Topic.title", """Manage subscriptions""")
pgettext("DB: products.Topic.description", """Manage your subscriptions to Mozilla’s premium products and services.""")
pgettext("DB: products.Topic.title", """Manage updates, policies & customization""")
pgettext("DB: products.Topic.description", """Policies for Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Managing Your Data""")
pgettext("DB: products.Topic.description", """Learn how to manage your data (including deleting) for specific products or services.""")
pgettext("DB: products.Topic.title", """Marketplace""")
pgettext("DB: products.Topic.description", """How to download, manage and use your favorite apps on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Marketplace""")
pgettext("DB: products.Topic.description", """Firefox Marketplace""")
pgettext("DB: products.Topic.title", """Masking""")
pgettext("DB: products.Topic.description", """Mask your email and phone number to better protect your privacy.""")
pgettext("DB: products.Topic.title", """Mask labels""")
pgettext("DB: products.Topic.description", """Troubleshoot mask labels issues.""")
pgettext("DB: products.Topic.title", """Media""")
pgettext("DB: products.Topic.description", """How to share media in virtual events""")
pgettext("DB: products.Topic.title", """Missing items""")
pgettext("DB: products.Topic.description", """Troubleshoot missing items issues.""")
pgettext("DB: products.Topic.title", """Mobile Store Support""")
pgettext("DB: products.Topic.description", """Topic for any articles related to the Mobile Store Support contribution.""")
pgettext("DB: products.Topic.title", """Moderators and hosts""")
pgettext("DB: products.Topic.description", """Tools for making Hubs a good experience for all.""")
pgettext("DB: products.Topic.title", """Monitoring""")
pgettext("DB: products.Topic.description", """Manage your personal info in Monitor""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Multimedia""")
pgettext("DB: products.Topic.description", """Everything you need to know about audio, video, images, and more.""")
pgettext("DB: products.Topic.title", """Music, Photos and Video""")
pgettext("DB: products.Topic.description", """Take pictures, record videos and listen to music on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """News Feeds (RSS), Blogs and Social""")
pgettext("DB: products.Topic.description", """Stay up to date with news feeds, blogs and social features""")
pgettext("DB: products.Topic.title", """New tab""")
pgettext("DB: products.Topic.description", """Troubleshoot new tab issues.""")
pgettext("DB: products.Topic.title", """Notifications""")
pgettext("DB: products.Topic.description", """Manage notifications in Mozilla’s products.""")
pgettext("DB: products.Topic.title", """Objects""")
pgettext("DB: products.Topic.description", """How to work with objects in Hubs""")
pgettext("DB: products.Topic.title", """[Obsolete] Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Topic.title", """[Obsolete] Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Older versions of Firefox for Android""")
pgettext("DB: products.Topic.description", """See articles for an unsupported version of Firefox for Android.""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other questions with Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other""")
pgettext("DB: products.Topic.title", """Password autofill""")
pgettext("DB: products.Topic.description", """Troubleshoot password autofill issues.""")
pgettext("DB: products.Topic.title", """Password manager""")
pgettext("DB: products.Topic.description", """Troubleshoot password manager issues.""")
pgettext("DB: products.Topic.title", """Passwords and sign in""")
pgettext("DB: products.Topic.description", """Manage your passwords and securely access your accounts.""")
pgettext("DB: products.Topic.title", """Passwords, forms and search""")
pgettext("DB: products.Topic.description", """Passwords, forms and search""")
pgettext("DB: products.Topic.title", """Passwords, forms, search, and history - control what Firefox suggests""")
pgettext("DB: products.Topic.description", """Passwords, forms, search, and history - control what Firefox suggests""")
pgettext("DB: products.Topic.title", """Passwords & recovery""")
pgettext("DB: products.Topic.description", """Manage or troubleshoot issues with your password and account access.""")
pgettext("DB: products.Topic.title", """Payments""")
pgettext("DB: products.Topic.description", """Manage your payment and subscription""")
pgettext("DB: products.Topic.title", """PDFs""")
pgettext("DB: products.Topic.description", """Troubleshoot PDFs issues.""")
pgettext("DB: products.Topic.title", """Performance and connectivity""")
pgettext("DB: products.Topic.description", """Deal with error messages, crashing applications, connectivity issues, and slow performance.""")
pgettext("DB: products.Topic.title", """Permanent library""")
pgettext("DB: products.Topic.description", """Troubleshoot permanent library issues.""")
pgettext("DB: products.Topic.title", """Permissions & settings""")
pgettext("DB: products.Topic.description", """Moderate your guests' level of access in your virtual events""")
pgettext("DB: products.Topic.title", """Personalize Firefox""")
pgettext("DB: products.Topic.description", """Make Firefox yours with these customization options.""")
pgettext("DB: products.Topic.title", """Personalize Firefox""")
pgettext("DB: products.Topic.description", """Change Firefox's appearance, behavior and settings.""")
pgettext("DB: products.Topic.title", """Personalize your experience""")
pgettext("DB: products.Topic.description", """Customize your Firefox browsing experience""")
pgettext("DB: products.Topic.title", """Phone masking""")
pgettext("DB: products.Topic.description", """Troubleshoot phone masking issues.""")
pgettext("DB: products.Topic.title", """PiP""")
pgettext("DB: products.Topic.description", """Troubleshoot picture in picture issues.""")
pgettext("DB: products.Topic.title", """Pocket Browser Extensions""")
pgettext("DB: products.Topic.description", """Our Save to Pocket extensions.""")
pgettext("DB: products.Topic.title", """Pocket for Android""")
pgettext("DB: products.Topic.description", """Helpful information about using Pocket for Android.""")
pgettext("DB: products.Topic.title", """Pocket for Firefox""")
pgettext("DB: products.Topic.description", """Save to Pocket and New Tab Recommendations.""")
pgettext("DB: products.Topic.title", """Pocket for iOS""")
pgettext("DB: products.Topic.description", """Helpful information about using Pocket for iPhone and iPad.""")
pgettext("DB: products.Topic.title", """Pocket for Web""")
pgettext("DB: products.Topic.description", """Pocket's web application.""")
pgettext("DB: products.Topic.title", """Pocket Premium""")
pgettext("DB: products.Topic.description", """Learn about the powerful features that Pocket Premium has to offer.""")
pgettext("DB: products.Topic.title", """Policies overview""")
pgettext("DB: products.Topic.description", """How to set up policies on Firefox for your organization.""")
pgettext("DB: products.Topic.title", """Popcorn Maker""")
pgettext("DB: products.Topic.description", """Learn how to remix web video, audio and images into mashups that you can embed on other websites. """)
pgettext("DB: products.Topic.title", """Popular articles""")
pgettext("DB: products.Topic.description", """Popular tips and solutions for Firefox for Android""")
pgettext("DB: products.Topic.title", """Preferences""")
pgettext("DB: products.Topic.description", """Customize Firefox Lite to your desired settings""")
pgettext("DB: products.Topic.title", """Premium email masking""")
pgettext("DB: products.Topic.description", """Find out more about the premium features.""")
pgettext("DB: products.Topic.title", """Premium phone masking""")
pgettext("DB: products.Topic.description", """Get started with phone masking.""")
pgettext("DB: products.Topic.title", """Primary password""")
pgettext("DB: products.Topic.description", """Set up a primary password to secure your saved passwords.""")
pgettext("DB: products.Topic.title", """Print""")
pgettext("DB: products.Topic.description", """Troubleshoot print issues.""")
pgettext("DB: products.Topic.title", """Privacy and security""")
pgettext("DB: products.Topic.description", """Keep your information safe with Firefox OS locks, privacy features and more.""")
pgettext("DB: products.Topic.title", """Privacy and security""")
pgettext("DB: products.Topic.description", """Protect your privacy on Firefox Preview.""")
pgettext("DB: products.Topic.title", """Privacy and security""")
pgettext("DB: products.Topic.description", """Learn how to protect your privacy and secure your data.""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Learn how to keep your information safe and secure with Firefox's private browsing, password features and other security settings.""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Keep your information safe with Firefox for Android's privacy and security settings.""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Keep your information safe with password and security settings""")
pgettext("DB: products.Topic.title", """Privacy scan""")
pgettext("DB: products.Topic.description", """Troubleshoot privacy scan issues.""")
pgettext("DB: products.Topic.title", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.description", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.title", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.description", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.title", """Problems with websites""")
pgettext("DB: products.Topic.description", """Problems with websites that don't work well in Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Process & policies""")
pgettext("DB: products.Topic.description", """Learn more about our knowledge base process and policies.""")
pgettext("DB: products.Topic.title", """Profile""")
pgettext("DB: products.Topic.description", """Back up your Firefox profile.""")
pgettext("DB: products.Topic.title", """Profiles""")
pgettext("DB: products.Topic.description", """Create and manage user profiles.""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Protect your information with Firefox's privacy settings on iOS""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Protect your privacy""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Control how your information is saved or tracked""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Protect your privacy""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Protect your privacy""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Protect your privacy""")
pgettext("DB: products.Topic.title", """Push notifications""")
pgettext("DB: products.Topic.description", """Troubleshoot push notifications issues.""")
pgettext("DB: products.Topic.title", """Reader View""")
pgettext("DB: products.Topic.description", """Comfortably read web pages without distractions.""")
pgettext("DB: products.Topic.title", """Reader View and List""")
pgettext("DB: products.Topic.description", """Read and save web pages in a clutter-free, reader-friendly view""")
pgettext("DB: products.Topic.title", """Reading list""")
pgettext("DB: products.Topic.description", """Troubleshoot reading list issues.""")
pgettext("DB: products.Topic.title", """Read, send and organize emails""")
pgettext("DB: products.Topic.description", """Learn how to manage your email messages""")
pgettext("DB: products.Topic.title", """Recommendations""")
pgettext("DB: products.Topic.description", """Troubleshoot recommendations issues.""")
pgettext("DB: products.Topic.title", """Recover data""")
pgettext("DB: products.Topic.description", """Learn how to recover your lost data.""")
pgettext("DB: products.Topic.title", """Recover my account""")
pgettext("DB: products.Topic.description", """Get help to recover your account if you can't sign in.""")
pgettext("DB: products.Topic.title", """Release notes""")
pgettext("DB: products.Topic.description", """Where to find release notes and upcoming features.""")
pgettext("DB: products.Topic.title", """Reset passwords""")
pgettext("DB: products.Topic.description", """Reset your passwords when you forget them.""")
pgettext("DB: products.Topic.title", """Rooms""")
pgettext("DB: products.Topic.description", """How to create and navigate virtual spaces in Hubs""")
pgettext("DB: products.Topic.title", """Sales tax""")
pgettext("DB: products.Topic.description", """Troubleshoot sales tax issues.""")
pgettext("DB: products.Topic.title", """Save content""")
pgettext("DB: products.Topic.description", """Save your favorite content for later.""")
pgettext("DB: products.Topic.title", """Save passwords""")
pgettext("DB: products.Topic.description", """Save your passwords for easy sign-in.""")
pgettext("DB: products.Topic.title", """Scenes""")
pgettext("DB: products.Topic.description", """Change the way your virtual room looks""")
pgettext("DB: products.Topic.title", """Screenshots & icons""")
pgettext("DB: products.Topic.description", """Learn more about using screenshots and icons in knowledge base articles.""")
pgettext("DB: products.Topic.title", """Search""")
pgettext("DB: products.Topic.description", """Customize your search settings in Firefox for iOS""")
pgettext("DB: products.Topic.title", """Search""")
pgettext("DB: products.Topic.description", """Find information quickly and easily.""")
pgettext("DB: products.Topic.title", """Search suggestions""")
pgettext("DB: products.Topic.description", """Troubleshoot search suggestions issues.""")
pgettext("DB: products.Topic.title", """Search, tag, and share""")
pgettext("DB: products.Topic.description", """Learn about search functionality and how to organize or share content in Mozilla products.""")
pgettext("DB: products.Topic.title", """Security""")
pgettext("DB: products.Topic.description", """Keep yourself secure online.""")
pgettext("DB: products.Topic.title", """Security & privacy""")
pgettext("DB: products.Topic.description", """Protect your personal information and passwords.""")
pgettext("DB: products.Topic.title", """Security software""")
pgettext("DB: products.Topic.description", """Troubleshoot security software issues.""")
pgettext("DB: products.Topic.title", """Send and receive email""")
pgettext("DB: products.Topic.description", """Everything you need to know about sending and receiving emails.""")
pgettext("DB: products.Topic.title", """Sensible Settings""")
pgettext("DB: products.Topic.description", """Give our users actionable and informed choices by informing and educating at the point of collection and providing a choice to opt-out whenever possible. """)
pgettext("DB: products.Topic.title", """Services and Subscriptions""")
pgettext("DB: products.Topic.description", """Free and premium privacy offerings""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """Learn how to configure the Internet connection, display and time on your Firefox OS device.""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """How to configure and customize Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """Manage and customize your product experience with settings, add-ons, and more.""")
pgettext("DB: products.Topic.title", """Settings and preferences""")
pgettext("DB: products.Topic.description", """Manage themes and search settings""")
pgettext("DB: products.Topic.title", """Set up email""")
pgettext("DB: products.Topic.description", """Add and configure your email accounts on Thunderbird""")
pgettext("DB: products.Topic.title", """Share content""")
pgettext("DB: products.Topic.description", """Learn how to share links, content, messages, and more.""")
pgettext("DB: products.Topic.title", """Sign in""")
pgettext("DB: products.Topic.description", """Sign in to your accounts securely.""")
pgettext("DB: products.Topic.title", """Sign in failure""")
pgettext("DB: products.Topic.description", """Troubleshoot sign in failure issues.""")
pgettext("DB: products.Topic.title", """Sign in with Google or Apple""")
pgettext("DB: products.Topic.description", """Sign in to accounts using 3rd-party authentication.""")
pgettext("DB: products.Topic.title", """Site breakages""")
pgettext("DB: products.Topic.description", """Resolve problems when websites don’t load or function correctly.""")
pgettext("DB: products.Topic.title", """Slow connection""")
pgettext("DB: products.Topic.description", """Troubleshoot slow connection issues.""")
pgettext("DB: products.Topic.title", """Social Support""")
pgettext("DB: products.Topic.description", """Topic for any articles related to the Social Support Program.""")
pgettext("DB: products.Topic.title", """Stay connected""")
pgettext("DB: products.Topic.description", """Sync information across devices""")
pgettext("DB: products.Topic.title", """Stay private and secure""")
pgettext("DB: products.Topic.description", """Keep your family's information private and secure""")
pgettext("DB: products.Topic.title", """Subscriptions & billing""")
pgettext("DB: products.Topic.description", """Manage your Mozilla subscriptions and payment methods.""")
pgettext("DB: products.Topic.title", """Suggested tags""")
pgettext("DB: products.Topic.description", """Troubleshoot suggested tags issues.""")
pgettext("DB: products.Topic.title", """Support Forum""")
pgettext("DB: products.Topic.description", """Topic for any articles related to support forum contribution.""")
pgettext("DB: products.Topic.title", """Sync""")
pgettext("DB: products.Topic.description", """Sync your Firefox data.""")
pgettext("DB: products.Topic.title", """Sync""")
pgettext("DB: products.Topic.description", """Sync your browsing information across other devices.""")
pgettext("DB: products.Topic.title", """Sync and backup confusion""")
pgettext("DB: products.Topic.description", """Troubleshoot sync and backup confusion.""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Save, share and synchronize content with other devices""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Sync information on all your devices""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Share web pages on Firefox for iOS""")
pgettext("DB: products.Topic.title", """Sync configuration""")
pgettext("DB: products.Topic.description", """Change your sync configuration.""")
pgettext("DB: products.Topic.title", """Sync data""")
pgettext("DB: products.Topic.description", """Sync your data across different platforms and devices.""")
pgettext("DB: products.Topic.title", """Sync devices & services""")
pgettext("DB: products.Topic.description", """Sync information on all your devices.""")
pgettext("DB: products.Topic.title", """Sync failure""")
pgettext("DB: products.Topic.description", """Troubleshoot sync issues.""")
pgettext("DB: products.Topic.title", """Sync, share and save""")
pgettext("DB: products.Topic.description", """Sync browsing information and content across multiple devices with Firefox Accounts.""")
pgettext("DB: products.Topic.title", """Tab basics""")
pgettext("DB: products.Topic.description", """Tab basics""")
pgettext("DB: products.Topic.title", """Tabs""")
pgettext("DB: products.Topic.description", """Organize and manage your tabs for better browsing.""")
pgettext("DB: products.Topic.title", """Tab settings""")
pgettext("DB: products.Topic.description", """Tab settings""")
pgettext("DB: products.Topic.title", """Tab settings""")
pgettext("DB: products.Topic.description", """Tab settings""")
pgettext("DB: products.Topic.title", """Tags""")
pgettext("DB: products.Topic.description", """Categorize and organize efficiently with tags.""")
pgettext("DB: products.Topic.title", """Technical""")
pgettext("DB: products.Topic.description", """Find solutions for how to use the Firefox Private Network add-on.""")
pgettext("DB: products.Topic.title", """Technical""")
pgettext("DB: products.Topic.description", """Learn how to use all Firefox Relay features.""")
pgettext("DB: products.Topic.title", """Text-to-speech""")
pgettext("DB: products.Topic.description", """Read web pages aloud.""")
pgettext("DB: products.Topic.title", """Themes""")
pgettext("DB: products.Topic.description", """Troubleshoot themes issues.""")
pgettext("DB: products.Topic.title", """Thimble""")
pgettext("DB: products.Topic.description", """Learn how to create and share your own webpages quickly and easily.""")
pgettext("DB: products.Topic.title", """Thunderbird controls and buttons """)
pgettext("DB: products.Topic.description", """Learn all about Thunderbird controls and functionality.""")
pgettext("DB: products.Topic.title", """Thunderbird crashes""")
pgettext("DB: products.Topic.description", """Thunderbird crashes""")
pgettext("DB: products.Topic.title", """Thunderbird is slow or stops working""")
pgettext("DB: products.Topic.description", """Thunderbird is slow or stops working""")
pgettext("DB: products.Topic.title", """Thunderbird options, preferences and settings """)
pgettext("DB: products.Topic.description", """Thunderbird options, preferences and settings """)
pgettext("DB: products.Topic.title", """Thunderbird versions and languages""")
pgettext("DB: products.Topic.description", """Thunderbird versions and languages""")
pgettext("DB: products.Topic.title", """Thunderbird won't save settings or remember information""")
pgettext("DB: products.Topic.description", """Thunderbird won't save settings or remember information""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Learn tips and shortcuts to help you work faster""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Go beyond the basics with these shortcuts and other tips.""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Tips and tricks""")
pgettext("DB: products.Topic.title", """Tracking protection""")
pgettext("DB: products.Topic.description", """Prevent websites from tracking you as you browse.""")
pgettext("DB: products.Topic.title", """Tracking protection""")
pgettext("DB: products.Topic.description", """Enable tracking protection to enhance your privacy.""")
pgettext("DB: products.Topic.title", """Troubleshoot""")
pgettext("DB: products.Topic.description", """Fix problems with Firefox Accounts""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Troubleshooting""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Discover solutions for common issues and explore best practices to diagnose and resolve problems.""")
pgettext("DB: products.Topic.title", """Troubleshoot issues""")
pgettext("DB: products.Topic.description", """Resolve problems you're having with your account""")
pgettext("DB: products.Topic.title", """Two-factor authentication""")
pgettext("DB: products.Topic.description", """Use two-factor authentication to add an extra layer of security when signing in.""")
pgettext("DB: products.Topic.title", """Two-factor lockout""")
pgettext("DB: products.Topic.description", """Troubleshoot two-factor lockout issues.""")
pgettext("DB: products.Topic.title", """Unblock Firefox from connecting to the Internet""")
pgettext("DB: products.Topic.description", """Unblock Firefox from connecting to the Internet""")
pgettext("DB: products.Topic.title", """Unblock Thunderbird from connecting to the Internet""")
pgettext("DB: products.Topic.description", """Unblock Thunderbird from connecting to the Internet""")
pgettext("DB: products.Topic.title", """Update""")
pgettext("DB: products.Topic.description", """Keep the Mozilla products you use up to date with the latest features and improvements.""")
pgettext("DB: products.Topic.title", """Update account settings""")
pgettext("DB: products.Topic.description", """Change your password, email address, and more.""")
pgettext("DB: products.Topic.title", """Update billing & payment methods""")
pgettext("DB: products.Topic.description", """Update billing information for your Mozilla subscriptions.""")
pgettext("DB: products.Topic.title", """Update failure""")
pgettext("DB: products.Topic.description", """Troubleshoot update failure issues.""")
pgettext("DB: products.Topic.title", """Upgrade/downgrade subscription""")
pgettext("DB: products.Topic.description", """Troubleshoot upgrade/downgrade subscription issues.""")
pgettext("DB: products.Topic.title", """Use bookmarks""")
pgettext("DB: products.Topic.description", """The basics of using bookmarks""")
pgettext("DB: products.Topic.title", """Use extensions and add-ons""")
pgettext("DB: products.Topic.description", """Enhance your family's Firefox browsing experience""")
pgettext("DB: products.Topic.title", """Video, audio and interactive settings""")
pgettext("DB: products.Topic.description", """Change how Firefox handles videos, animations, music and other interactive content""")
pgettext("DB: products.Topic.title", """Videos, sound, pictures and animations don't work""")
pgettext("DB: products.Topic.description", """Videos, sound, pictures and animations don't work""")
pgettext("DB: products.Topic.title", """View all Firefox OS articles""")
pgettext("DB: products.Topic.description", """View a list of all Firefox OS articles""")
pgettext("DB: products.Topic.title", """Web certificates""")
pgettext("DB: products.Topic.description", """Troubleshoot web certificates issues.""")
pgettext("DB: products.Topic.title", """Web compatibility""")
pgettext("DB: products.Topic.description", """Troubleshoot web compatibility issues.""")
pgettext("DB: products.Topic.title", """Webmaker for Android""")
pgettext("DB: products.Topic.description", """Get help with the Webmaker app for Android.""")
pgettext("DB: products.Topic.title", """Website breakages""")
pgettext("DB: products.Topic.description", """Fix site breakage issues.""")
pgettext("DB: products.Topic.title", """What's new in Firefox for Android""")
pgettext("DB: products.Topic.description", """See what new features are available in each release""")
pgettext("DB: products.Topic.title", """What's new in Firefox for iOS""")
pgettext("DB: products.Topic.description", """See what features are available in each release.""")
pgettext("DB: products.Topic.title", """Windows""")
pgettext("DB: products.Topic.description", """Deploying Firefox on Windows computers.""")
pgettext("DB: products.Topic.title", """Working with messages""")
pgettext("DB: products.Topic.description", """Firefox OS SMS & email""")
pgettext("DB: products.Topic.title", """X-Ray Goggles""")
pgettext("DB: products.Topic.description", """Learn how to inspect the code behind every webpage.""")
pgettext("DB: products.Topic.title", """Your Pocket Account""")
pgettext("DB: products.Topic.description", """Signup, login, password reset and more.""")
pgettext("DB: kbadge.Badge.title", """2025 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2025.""")
pgettext("DB: kbadge.Badge.title", """2025 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2025.""")
pgettext("DB: kbadge.Badge.title", """2025 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2025.""")
pgettext("DB: kbadge.Badge.title", """Firefox 20th Anniversary Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with >=100 contributions within 2024, when we celebrate Firefox 20th anniversary on November 9, 2024.""")
pgettext("DB: kbadge.Badge.title", """2024 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2024.""")
pgettext("DB: kbadge.Badge.title", """2024 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2024.""")
pgettext("DB: kbadge.Badge.title", """2024 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2024.""")
pgettext("DB: kbadge.Badge.title", """2023 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2023.""")
pgettext("DB: kbadge.Badge.title", """2023 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2023.""")
pgettext("DB: kbadge.Badge.title", """2023 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2023.""")
pgettext("DB: kbadge.Badge.title", """2021 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2021.""")
pgettext("DB: kbadge.Badge.title", """2022 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2022.""")
pgettext("DB: kbadge.Badge.title", """2022 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2022.""")
pgettext("DB: kbadge.Badge.title", """2022 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2022.""")
pgettext("DB: kbadge.Badge.title", """2021 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2021.""")
pgettext("DB: kbadge.Badge.title", """2021 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2021.""")
pgettext("DB: kbadge.Badge.title", """2020 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2019.""")
pgettext("DB: kbadge.Badge.title", """2020 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2019.""")
pgettext("DB: kbadge.Badge.title", """2020 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2019.""")
pgettext("DB: kbadge.Badge.title", """2020 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2019.""")
pgettext("DB: kbadge.Badge.title", """2018 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2018.""")
pgettext("DB: kbadge.Badge.title", """2018 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2018.""")
pgettext("DB: kbadge.Badge.title", """2018 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2018.""")
pgettext("DB: kbadge.Badge.title", """2018 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2018.""")
pgettext("DB: kbadge.Badge.title", """2017 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2017.""")
pgettext("DB: kbadge.Badge.title", """2017 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2017.""")
pgettext("DB: kbadge.Badge.title", """2017 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2017.""")
pgettext("DB: kbadge.Badge.title", """2017 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2017.""")
pgettext("DB: kbadge.Badge.title", """2016 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2016.""")
pgettext("DB: kbadge.Badge.title", """2016 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2016.""")
pgettext("DB: kbadge.Badge.title", """2016 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2016.""")
pgettext("DB: kbadge.Badge.title", """2016 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2016.""")
pgettext("DB: kbadge.Badge.title", """2015 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2015.""")
pgettext("DB: kbadge.Badge.title", """2015 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2015.""")
pgettext("DB: kbadge.Badge.title", """2015 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2015.""")
pgettext("DB: kbadge.Badge.title", """2015 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2015.""")
pgettext("DB: kbadge.Badge.title", """2014 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2014 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2014 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2014 badge earners for advancing the Mozilla Mission""")
pgettext("DB: kbadge.Badge.title", """2014 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """Firefox 29 Launch Team""")
pgettext("DB: kbadge.Badge.description", """Awarded to support contributors who contributed (KB article documentation, answering Forum Questions, localizing KB article documentation, tweets, etc) to the launch of Firefox 29, thanks! 

Firefox 29 features:

1. Firefox Desktop: Australis new look and feel
AND Firefox Accounts based sync

2. Firefox for Android: Firefox Accounts based sync

MOAR:

https://sumo.etherpad.mozilla.org/sumo-australis-badges""")
pgettext("DB: kbadge.Badge.title", """2008 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2008.""")
pgettext("DB: kbadge.Badge.title", """2009 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2009.""")
pgettext("DB: kbadge.Badge.title", """2012 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2010 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2012 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2010 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2010 badge earners for advancing the Mozilla Mission""")
pgettext("DB: kbadge.Badge.title", """2010 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2010 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2011 badge earners for advancing the Mozilla Mission!
""")
pgettext("DB: kbadge.Badge.title", """2012 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2013 badge earners for advancing the Mozilla Mission""")
pgettext("DB: kbadge.Badge.title", """2012 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """Kitsune Contributor""")
pgettext("DB: kbadge.Badge.description", """Badge awarded to those who have contributed to the Kitsune code base.""")
