#######################################################################
#
# Note: This file is a generated file--do not edit it directly!
# Instead make changes to the appropriate content in the database or
# write up a bug here:
#
#     https://bugzilla.mozilla.org/enter_bug.cgi?product=support.mozilla.org
#
# with the specific lines that are problematic and why.
#
# You can generate this file by running:
#
#     ./manage.py extract_db
#
#######################################################################
from django.utils.translation import pgettext

# This is a karma title.
pgettext("DB: karma.Title.name", """Administrator""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Buddy of the Month! (10/2015)""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Locale Leader""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Moderator""")
# This is a karma title.
pgettext("DB: karma.Title.name", """SUMO Warrior""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Top 10 Contributor""")
# This is a karma title.
pgettext("DB: karma.Title.name", """Top 25 Contributor""")
pgettext("DB: products.Product.title", """Firefox""")
pgettext("DB: products.Product.description", """Web browser for Windows, Mac and Linux""")
pgettext("DB: products.Product.title", """Firefox for Android""")
pgettext("DB: products.Product.description", """Web browser for Android smartphones and tablets""")
pgettext("DB: products.Product.title", """Firefox for iOS""")
pgettext("DB: products.Product.description", """Firefox for iPhone, iPad and iPod touch devices""")
pgettext("DB: products.Product.title", """Mozilla VPN""")
pgettext("DB: products.Product.description", """VPN for Windows 10, Mac, Linux, Android, and iOS devices""")
pgettext("DB: products.Product.title", """Firefox Relay""")
pgettext("DB: products.Product.description", """Service that lets you create email masks to hide your real email address""")
pgettext("DB: products.Product.title", """Monitor""")
pgettext("DB: products.Product.description", """Find out if your private information has been exposed in a known data breach.""")
pgettext("DB: products.Product.title", """Firefox Focus""")
pgettext("DB: products.Product.description", """Automatic privacy browser and content blocker""")
pgettext("DB: products.Product.title", """MDN Plus""")
pgettext("DB: products.Product.description", """MDN Plus provides a custom user experience for MDN supporters.""")
pgettext("DB: products.Product.title", """Hubs""")
pgettext("DB: products.Product.description", """Collaborate and engage with each other through spatialized audio and with media from around the web.""")
pgettext("DB: products.Product.title", """Firefox for Enterprise""")
pgettext("DB: products.Product.description", """Firefox Quantum for businesses""")
pgettext("DB: products.Product.title", """Thunderbird""")
pgettext("DB: products.Product.description", """Email software for Windows, Mac and Linux""")
pgettext("DB: products.Product.title", """Firefox Private Network""")
pgettext("DB: products.Product.description", """Browse securely on public Wi-Fi using a Firefox add-on.""")
pgettext("DB: products.Product.title", """Contributors""")
pgettext("DB: products.Product.description", """Contributor articles""")
pgettext("DB: products.Product.title", """Firefox Accounts""")
pgettext("DB: products.Product.description", """Privacy-first products for desktop and mobile""")
pgettext("DB: products.Product.title", """Firefox for Amazon Devices""")
pgettext("DB: products.Product.description", """Browser for Amazon devices""")
pgettext("DB: products.Product.title", """Firefox for Android (ESR)""")
pgettext("DB: products.Product.description", """Older version of Firefox for Android (no longer supported)""")
pgettext("DB: products.Product.title", """Firefox for Android Beta""")
pgettext("DB: products.Product.description", """Early version of an experimental Firefox browser for Android.""")
pgettext("DB: products.Product.title", """Firefox for Fire TV""")
pgettext("DB: products.Product.description", """Browser for Amazon Fire TV""")
pgettext("DB: products.Product.title", """Firefox for Windows 8 Touch""")
pgettext("DB: products.Product.description", """Firefox for Windows 8 touch devices""")
pgettext("DB: products.Product.title", """Firefox Klar""")
pgettext("DB: products.Product.description", """Was ist Firefox Klar?""")
pgettext("DB: products.Product.title", """Firefox Lite""")
pgettext("DB: products.Product.description", """Mobile browser for Indonesia, India, The Philippines, and Thailand""")
pgettext("DB: products.Product.title", """Firefox Lockwise""")
pgettext("DB: products.Product.description", """Mobile app that gives you access to passwords you've saved to Firefox.""")
pgettext("DB: products.Product.title", """Firefox OS""")
pgettext("DB: products.Product.description", """Mobile OS for smartphones""")
pgettext("DB: products.Product.title", """Firefox Reality""")
pgettext("DB: products.Product.description", """Web browser for virtual reality headsets""")
pgettext("DB: products.Product.title", """Firefox ScreenshotGo""")
pgettext("DB: products.Product.description", """Screenshot app for mobile""")
pgettext("DB: products.Product.title", """Firefox Send""")
pgettext("DB: products.Product.description", """An app for sending files to anyone.""")
pgettext("DB: products.Product.title", """Open Badges""")
pgettext("DB: products.Product.description", """A new online standard to recognize and verify learning""")
pgettext("DB: products.Product.title", """Pocket""")
pgettext("DB: products.Product.description", """Discover and save stories for later""")
pgettext("DB: products.Product.title", """Privacy and Security""")
pgettext("DB: products.Product.description", """Learn more about Mozilla's privacy and security practices.""")
pgettext("DB: products.Product.title", """Webmaker""")
pgettext("DB: products.Product.description", """Webmaker and other tools for teaching and learning the Web""")
pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn all you need to know to get started with Firefox.""")
pgettext("DB: products.Topic.title", """Bookmarks and tabs""")
pgettext("DB: products.Topic.description", """Access and organize your favorite webpages easily with bookmarks and tabs""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """Search and navigate easily with these essential features""")
pgettext("DB: products.Topic.title", """Import settings from other browsers""")
pgettext("DB: products.Topic.description", """Learn how to import or export your information between Firefox and another browser""")
pgettext("DB: products.Topic.title", """Video, audio and interactive settings""")
pgettext("DB: products.Topic.description", """Change how Firefox handles videos, animations, music and other interactive content""")
pgettext("DB: products.Topic.title", """How to use Firefox""")
pgettext("DB: products.Topic.description", """How to browse, search and customize your settings""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Download Firefox and safely browse the web""")
pgettext("DB: products.Topic.title", """Install and manage add-ons""")
pgettext("DB: products.Topic.description", """Add-ons let you customize and add features to Firefox.""")
pgettext("DB: products.Topic.title", """Bookmarks""")
pgettext("DB: products.Topic.description", """Back up your Firefox bookmarks.""")
pgettext("DB: products.Topic.title", """How to use Firefox for Android""")
pgettext("DB: products.Topic.description", """How to use Firefox for Android""")
pgettext("DB: products.Topic.title", """What's new in Firefox for Android""")
pgettext("DB: products.Topic.description", """See what new features are available in each release""")
pgettext("DB: products.Topic.title", """Install and Update""")
pgettext("DB: products.Topic.description", """Install and keep Firefox up to date on your iPad, iPhone or iPod Touch.""")
pgettext("DB: products.Topic.title", """Reader View and List""")
pgettext("DB: products.Topic.description", """Read and save web pages in a clutter-free, reader-friendly view""")
pgettext("DB: products.Topic.title", """Basic browsing""")
pgettext("DB: products.Topic.description", """How to use bookmarks, tabs and basic Firefox features on your iOS device""")
pgettext("DB: products.Topic.title", """History""")
pgettext("DB: products.Topic.description", """Change your history settings on Firefox for iOS""")
pgettext("DB: products.Topic.title", """How to use Firefox for iOS""")
pgettext("DB: products.Topic.description", """General usage questions""")
pgettext("DB: products.Topic.title", """What's new in Firefox for iOS""")
pgettext("DB: products.Topic.description", """See what features are available in each release.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Fix slowness, crashing, error messages and other problems.""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Learn how to download Firefox on your desktop devices or move information to and from other browsers.""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Go beyond the basics with these shortcuts and other tips.""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """How to install Firefox and keep it up to date""")
pgettext("DB: products.Topic.title", """Display and appearance""")
pgettext("DB: products.Topic.description", """Learn how to change your toolbar, font sizes and browser colors""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """Download or update Firefox for Windows, Mac and Linux.""")
pgettext("DB: products.Topic.title", """Stay private and secure""")
pgettext("DB: products.Topic.description", """Keep your family's information private and secure""")
pgettext("DB: products.Topic.title", """Profile""")
pgettext("DB: products.Topic.description", """Back up your Firefox profile.""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """How to install and keep Firefox for Android up to date""")
pgettext("DB: products.Topic.title", """Bookmarks and tabs""")
pgettext("DB: products.Topic.description", """Access websites easily with bookmarks and tab features""")
pgettext("DB: products.Topic.title", """Search""")
pgettext("DB: products.Topic.description", """Customize your search settings in Firefox for iOS""")
pgettext("DB: products.Topic.title", """Firefox for iOS is not working as expected""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox for iOS.""")
pgettext("DB: products.Topic.title", """Firefox Sync""")
pgettext("DB: products.Topic.description", """Firefox Sync settings""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Sync information on all your devices""")
pgettext("DB: products.Topic.title", """Manage add-ons""")
pgettext("DB: products.Topic.description", """Enhance Firefox's functionality and appearance with add-ons""")
pgettext("DB: products.Topic.title", """Sync, share and save""")
pgettext("DB: products.Topic.description", """Sync browsing information and content across multiple devices with Firefox Accounts.""")
pgettext("DB: products.Topic.title", """Firefox settings""")
pgettext("DB: products.Topic.description", """Privacy and personalization""")
pgettext("DB: products.Topic.title", """Use extensions and add-ons""")
pgettext("DB: products.Topic.description", """Enhance your family's Firefox browsing experience""")
pgettext("DB: products.Topic.title", """Sync""")
pgettext("DB: products.Topic.description", """Sync your Firefox data.""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Save, share and synchronize content with other devices""")
pgettext("DB: products.Topic.title", """Changing your settings""")
pgettext("DB: products.Topic.description", """Change Firefox's behavior.""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Protect your information with Firefox's privacy settings on iOS""")
pgettext("DB: products.Topic.title", """Firefox Hello""")
pgettext("DB: products.Topic.description", """Have video or voice conversations using the Firefox browser""")
pgettext("DB: products.Topic.title", """Chat and share""")
pgettext("DB: products.Topic.description", """Connect on video and share pages with your network""")
pgettext("DB: products.Topic.title", """Personalize Firefox""")
pgettext("DB: products.Topic.description", """Make Firefox yours with these customization options.""")
pgettext("DB: products.Topic.title", """Personalize your experience""")
pgettext("DB: products.Topic.description", """Customize your Firefox browsing experience""")
pgettext("DB: products.Topic.title", """Cast to your TV""")
pgettext("DB: products.Topic.description", """Learn how to view content on another screen""")
pgettext("DB: products.Topic.title", """Popular articles""")
pgettext("DB: products.Topic.description", """Popular tips and solutions for Firefox for Android""")
pgettext("DB: products.Topic.title", """Sync and save""")
pgettext("DB: products.Topic.description", """Share web pages on Firefox for iOS""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Customize preferences for Firefox for iOS""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox yours by adding and managing the features that you want.""")
pgettext("DB: products.Topic.title", """Personalize Firefox""")
pgettext("DB: products.Topic.description", """Change Firefox's appearance, behavior and settings.""")
pgettext("DB: products.Topic.title", """Stay connected""")
pgettext("DB: products.Topic.description", """Sync information across devices""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Control how your information is saved or tracked""")
pgettext("DB: products.Topic.title", """Crashes, errors and other issues""")
pgettext("DB: products.Topic.description", """Troubleshoot error message on Firefox for iOS""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Learn how to keep your information safe and secure with Firefox's private browsing, password features and other security settings.""")
pgettext("DB: products.Topic.title", """Do more with apps""")
pgettext("DB: products.Topic.description", """Install open apps from the Marketplace to add more fun and functionality to your device""")
pgettext("DB: products.Topic.title", """Protect your privacy""")
pgettext("DB: products.Topic.description", """Keep your information safe from prying eyes with the latest privacy and security features.""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Make Firefox for Android yours with these customization options""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Customize settings and preferences""")
pgettext("DB: products.Topic.description", """Make Firefox yours through customization settings and add-ons""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot slowness, crashing and error messages.""")
pgettext("DB: products.Topic.title", """Firefox for families""")
pgettext("DB: products.Topic.description", """Customize Firefox to keep your family safe and secure""")
pgettext("DB: products.Topic.title", """Do more with apps""")
pgettext("DB: products.Topic.description", """Learn to find and install open apps to add more fun and functionality to your device""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.title", """Advanced and experimental features""")
pgettext("DB: products.Topic.description", """Learn tips beyond the basics and try features before they're released to the public.""")
pgettext("DB: products.Topic.title", """Back up your data""")
pgettext("DB: products.Topic.description", """Use Firefox Sync to backup and transfer your data.""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Learn the Basics: get started""")
pgettext("DB: products.Topic.description", """Learn all you need to know to get Firefox for Android up and running.""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Learn how to install and transfer information to Firefox for Android.""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Tips and tricks""")
pgettext("DB: products.Topic.title", """Use bookmarks""")
pgettext("DB: products.Topic.description", """The basics of using bookmarks""")
pgettext("DB: products.Topic.title", """Firefox Sync settings""")
pgettext("DB: products.Topic.description", """Firefox Sync settings""")
pgettext("DB: products.Topic.title", """Tab basics""")
pgettext("DB: products.Topic.description", """Tab basics""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Keep your information safe with Firefox for Android's privacy and security settings.""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Make Firefox for Android work the way you want through customization.""")
pgettext("DB: products.Topic.title", """Firefox versions and languages""")
pgettext("DB: products.Topic.description", """Firefox versions and languages""")
pgettext("DB: products.Topic.title", """Copy your personal information from one browser to another""")
pgettext("DB: products.Topic.description", """Copy your personal information from one browser to another""")
pgettext("DB: products.Topic.title", """Cookies and cache""")
pgettext("DB: products.Topic.description", """Control the information that Firefox saves""")
pgettext("DB: products.Topic.title", """Cookies""")
pgettext("DB: products.Topic.description", """Cookies""")
pgettext("DB: products.Topic.title", """Passwords, forms, search, and history - control what Firefox suggests""")
pgettext("DB: products.Topic.description", """Passwords, forms, search, and history - control what Firefox suggests""")
pgettext("DB: products.Topic.title", """Website breakages""")
pgettext("DB: products.Topic.description", """Fix site breakage issues.""")
pgettext("DB: products.Topic.title", """Tracking protection""")
pgettext("DB: products.Topic.description", """Prevent websites from tracking you as you browse.""")
pgettext("DB: products.Topic.title", """Firefox controls and buttons""")
pgettext("DB: products.Topic.description", """Firefox controls and buttons""")
pgettext("DB: products.Topic.title", """Tab settings""")
pgettext("DB: products.Topic.description", """Tab settings""")
pgettext("DB: products.Topic.title", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Firefox with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Firefox options, preferences and settings""")
pgettext("DB: products.Topic.description", """Firefox options, preferences and settings""")
pgettext("DB: products.Topic.title", """Bookmark options""")
pgettext("DB: products.Topic.description", """Bookmark options""")
pgettext("DB: products.Topic.title", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.description", """Fix problems with websites (Facebook, YouTube, webmail etc.)""")
pgettext("DB: products.Topic.title", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.description", """How to troubleshoot error messages on Firefox""")
pgettext("DB: products.Topic.title", """Firefox crashes""")
pgettext("DB: products.Topic.description", """Crashing""")
pgettext("DB: products.Topic.title", """Unblock Firefox from connecting to the Internet""")
pgettext("DB: products.Topic.description", """Unblock Firefox from connecting to the Internet""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Videos, sound, pictures and animations don't work""")
pgettext("DB: products.Topic.description", """Videos, sound, pictures and animations don't work""")
pgettext("DB: products.Topic.title", """Firefox is slow or stops working""")
pgettext("DB: products.Topic.description", """Slowness or hanging""")
pgettext("DB: products.Topic.title", """Firefox crashes""")
pgettext("DB: products.Topic.description", """Crashing""")
pgettext("DB: products.Topic.title", """Firefox won't save settings or remember information""")
pgettext("DB: products.Topic.description", """Firefox won't save settings or remember information""")
pgettext("DB: products.Topic.title", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.description", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other""")
pgettext("DB: products.Topic.title", """Marketplace""")
pgettext("DB: products.Topic.description", """Firefox Marketplace""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """Learn the basics of Mozilla VPN.""")
pgettext("DB: products.Topic.title", """Download & Setup""")
pgettext("DB: products.Topic.description", """Start using Mozilla VPN.""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """Find solutions on managing your account""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your payment and subscription""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Fix problems with Firefox Private Network VPN""")
pgettext("DB: products.Topic.title", """Connectivity""")
pgettext("DB: products.Topic.description", """Troubleshoot connectivity issues.""")
pgettext("DB: products.Topic.title", """Technical""")
pgettext("DB: products.Topic.description", """Learn how to use all Firefox Relay features.""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """Learn the basics of Firefox Relay.""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your subscription to Firefox Relay Premium""")
pgettext("DB: products.Topic.title", """Free email masking""")
pgettext("DB: products.Topic.description", """Learn the basics of Firefox Relay.""")
pgettext("DB: products.Topic.title", """Premium email masking""")
pgettext("DB: products.Topic.description", """Find out more about the premium features.""")
pgettext("DB: products.Topic.title", """Premium phone masking""")
pgettext("DB: products.Topic.description", """Get started with phone masking.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Fix the most common problems with Firefox Relay.""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """Manage your Firefox Relay account.""")
pgettext("DB: products.Topic.title", """Getting started""")
pgettext("DB: products.Topic.description", """Getting started with Monitor Data Removal""")
pgettext("DB: products.Topic.title", """Monitoring""")
pgettext("DB: products.Topic.description", """Manage your personal info in Monitor""")
pgettext("DB: products.Topic.title", """Accounts""")
pgettext("DB: products.Topic.description", """Manage your Firefox Monitor account""")
pgettext("DB: products.Topic.title", """Firefox Focus for iOS""")
pgettext("DB: products.Topic.description", """Firefox Focus for iOS""")
pgettext("DB: products.Topic.title", """Getting Started""")
pgettext("DB: products.Topic.description", """Getting started with MDN Plus.""")
pgettext("DB: products.Topic.title", """Firefox Focus for Android""")
pgettext("DB: products.Topic.description", """Privacy browser for Android""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """Manage your MDN Plus account.""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your MDN Plus subscription.""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Learn the basics""")
pgettext("DB: products.Topic.title", """Identity""")
pgettext("DB: products.Topic.description", """How to create and edit your identity in Hubs""")
pgettext("DB: products.Topic.title", """Scenes""")
pgettext("DB: products.Topic.description", """Change the way your virtual room looks""")
pgettext("DB: products.Topic.title", """Objects""")
pgettext("DB: products.Topic.description", """How to work with objects in Hubs""")
pgettext("DB: products.Topic.title", """Media""")
pgettext("DB: products.Topic.description", """How to share media in virtual events""")
pgettext("DB: products.Topic.title", """Accounts & Sign-in""")
pgettext("DB: products.Topic.description", """How to sign in and activate more features""")
pgettext("DB: products.Topic.title", """Camera (point of view)""")
pgettext("DB: products.Topic.description", """How to change your camera settings in Hubs""")
pgettext("DB: products.Topic.title", """Invitations""")
pgettext("DB: products.Topic.description", """Invite guests to your virtual room""")
pgettext("DB: products.Topic.title", """Billing & Payments""")
pgettext("DB: products.Topic.description", """Manage your payment and subscription""")
pgettext("DB: products.Topic.title", """Avatars""")
pgettext("DB: products.Topic.description", """How to set up and navigate using your virtual identity""")
pgettext("DB: products.Topic.title", """Controls (movement)""")
pgettext("DB: products.Topic.description", """How to navigate through virtual spaces""")
pgettext("DB: products.Topic.title", """Permissions & settings""")
pgettext("DB: products.Topic.description", """Moderate your guests' level of access in your virtual events""")
pgettext("DB: products.Topic.title", """Moderators and hosts""")
pgettext("DB: products.Topic.description", """Tools for making Hubs a good experience for all.""")
pgettext("DB: products.Topic.title", """Rooms""")
pgettext("DB: products.Topic.description", """How to create and navigate virtual spaces in Hubs""")
pgettext("DB: products.Topic.title", """Abuse""")
pgettext("DB: products.Topic.description", """Tools to make your event a safe place for your guests""")
pgettext("DB: products.Topic.title", """Creators & developers""")
pgettext("DB: products.Topic.description", """Where to find resources for advanced customization""")
pgettext("DB: products.Topic.title", """Release notes""")
pgettext("DB: products.Topic.description", """Where to find release notes and upcoming features.""")
pgettext("DB: products.Topic.title", """Windows""")
pgettext("DB: products.Topic.description", """Deploying Firefox on Windows computers.""")
pgettext("DB: products.Topic.title", """Manage certificates""")
pgettext("DB: products.Topic.description", """Set up certificates on Firefox for your organization.""")
pgettext("DB: products.Topic.title", """Customization of Firefox in an enterprise environment""")
pgettext("DB: products.Topic.description", """Customization of Firefox in an enterprise environment""")
pgettext("DB: products.Topic.title", """Installation""")
pgettext("DB: products.Topic.description", """How to install Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Explore""")
pgettext("DB: products.Topic.description", """Learn about Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Mac""")
pgettext("DB: products.Topic.description", """Deploy Firefox on your organization's Mac computers""")
pgettext("DB: products.Topic.title", """Policies overview""")
pgettext("DB: products.Topic.description", """How to set up policies on Firefox for your organization.""")
pgettext("DB: products.Topic.title", """Deploy""")
pgettext("DB: products.Topic.description", """Deployment of Firefox in an enterprise environment""")
pgettext("DB: products.Topic.title", """Manage updates, policies & customization""")
pgettext("DB: products.Topic.description", """Policies for Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Autoconfiguration""")
pgettext("DB: products.Topic.description", """How to configure Firefox for Enterprise""")
pgettext("DB: products.Topic.title", """Linux""")
pgettext("DB: products.Topic.description", """Deploy Firefox on your organization's Linux machines.""")
pgettext("DB: products.Topic.title", """Manage settings via policy""")
pgettext("DB: products.Topic.description", """Change Firefox's settings using policies.""")
pgettext("DB: products.Topic.title", """Manage add-ons""")
pgettext("DB: products.Topic.description", """Working with add-ons on Firefox for your organization.""")
pgettext("DB: products.Topic.title", """Learn the Basics. Get Started""")
pgettext("DB: products.Topic.description", """Learn the Basics. Get Started""")
pgettext("DB: products.Topic.title", """Tips and tricks""")
pgettext("DB: products.Topic.description", """Learn tips and shortcuts to help you work faster""")
pgettext("DB: products.Topic.title", """Set up email""")
pgettext("DB: products.Topic.description", """Add and configure your email accounts on Thunderbird""")
pgettext("DB: products.Topic.title", """Install, Migrate and Update""")
pgettext("DB: products.Topic.description", """How to install and keep Thunderbird up to date""")
pgettext("DB: products.Topic.title", """Read, send and organize emails""")
pgettext("DB: products.Topic.description", """Learn how to manage your email messages""")
pgettext("DB: products.Topic.title", """Emails""")
pgettext("DB: products.Topic.description", """Learn to set up accounts, read, send and manage emails""")
pgettext("DB: products.Topic.title", """News Feeds (RSS), Blogs and Social""")
pgettext("DB: products.Topic.description", """Stay up to date with news feeds, blogs and social features""")
pgettext("DB: products.Topic.title", """Contacts""")
pgettext("DB: products.Topic.description", """How to use the address book on Thunderbird""")
pgettext("DB: products.Topic.title", """Calendar""")
pgettext("DB: products.Topic.description", """Related to the Lightning add-on for Calendar""")
pgettext("DB: products.Topic.title", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.description", """Customize controls, options and add-ons""")
pgettext("DB: products.Topic.title", """Thunderbird versions and languages""")
pgettext("DB: products.Topic.description", """Thunderbird versions and languages""")
pgettext("DB: products.Topic.title", """Passwords, forms and search""")
pgettext("DB: products.Topic.description", """Passwords, forms and search""")
pgettext("DB: products.Topic.title", """Thunderbird controls and buttons """)
pgettext("DB: products.Topic.description", """Learn all about Thunderbird controls and functionality.""")
pgettext("DB: products.Topic.title", """Fix problems with email providers (gmail, Yahoo, etc.) """)
pgettext("DB: products.Topic.description", """Learn how to fix problems with Gmail, Yahoo and other email providers""")
pgettext("DB: products.Topic.title", """Download, install and migration""")
pgettext("DB: products.Topic.description", """Download, install and Migration""")
pgettext("DB: products.Topic.title", """Copy your personal information from  one Thunderbird to another""")
pgettext("DB: products.Topic.description", """Copy your personal information from  one Thunderbird to another""")
pgettext("DB: products.Topic.title", """Tab settings""")
pgettext("DB: products.Topic.description", """Tab settings""")
pgettext("DB: products.Topic.title", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.description", """Error messages: what they mean and how to fix""")
pgettext("DB: products.Topic.title", """Privacy and security settings""")
pgettext("DB: products.Topic.description", """Keep your information safe with password and security settings""")
pgettext("DB: products.Topic.title", """Customize Thunderbird with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.description", """Customize Thunderbird with add-ons, plugins, and extensions""")
pgettext("DB: products.Topic.title", """Unblock Thunderbird from connecting to the Internet""")
pgettext("DB: products.Topic.description", """Unblock Thunderbird from connecting to the Internet""")
pgettext("DB: products.Topic.title", """Thunderbird options, preferences and settings """)
pgettext("DB: products.Topic.description", """Thunderbird options, preferences and settings """)
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """Fix slowness, crashing, error messages and other problems""")
pgettext("DB: products.Topic.description", """Troubleshoot error messages on Thunderbird.""")
pgettext("DB: products.Topic.title", """Thunderbird is slow or stops working""")
pgettext("DB: products.Topic.description", """Thunderbird is slow or stops working""")
pgettext("DB: products.Topic.title", """Thunderbird crashes""")
pgettext("DB: products.Topic.description", """Thunderbird crashes""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """Thunderbird won't save settings or remember information""")
pgettext("DB: products.Topic.description", """Thunderbird won't save settings or remember information""")
pgettext("DB: products.Topic.title", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.description", """Problems with add-ons, plugins or unwanted software""")
pgettext("DB: products.Topic.title", """How To""")
pgettext("DB: products.Topic.description", """Articles that tell you how you can do more with Thunderbird""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other""")
pgettext("DB: products.Topic.title", """Technical""")
pgettext("DB: products.Topic.description", """Find solutions for how to use the Firefox Private Network add-on.""")
pgettext("DB: products.Topic.title", """Accounts""")
pgettext("DB: products.Topic.description", """Change account and settings for Private Network.""")
pgettext("DB: products.Topic.title", """Payments""")
pgettext("DB: products.Topic.description", """Manage your payment and subscription""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Troubleshoot issues for Private Network""")
pgettext("DB: products.Topic.title", """General contribution""")
pgettext("DB: products.Topic.description", """Learn how you can contribute to SUMO in general.""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Firefox OS basics""")
pgettext("DB: products.Topic.title", """Basic Features""")
pgettext("DB: products.Topic.description", """Learn the basic functionality for your Firefox OS phone. """)
pgettext("DB: products.Topic.title", """Download and Manage Apps""")
pgettext("DB: products.Topic.description", """Download apps from the Marketplace""")
pgettext("DB: products.Topic.title", """Date and Time""")
pgettext("DB: products.Topic.description", """Setting a date and time on your Firefox OS phone""")
pgettext("DB: products.Topic.title", """Display""")
pgettext("DB: products.Topic.description", """Customize your screen on your Firefox OS device.""")
pgettext("DB: products.Topic.title", """Popcorn Maker""")
pgettext("DB: products.Topic.description", """Learn how to remix web video, audio and images into mashups that you can embed on other websites. """)
pgettext("DB: products.Topic.title", """Webmaker for Android""")
pgettext("DB: products.Topic.description", """Get help with the Webmaker app for Android.""")
pgettext("DB: products.Topic.title", """Intro to Open Badges""")
pgettext("DB: products.Topic.description", """Learn the basic about Open Badges""")
pgettext("DB: products.Topic.title", """Knowledge Base""")
pgettext("DB: products.Topic.description", """Windows 8 Touch support articles""")
pgettext("DB: products.Topic.title", """Get Started""")
pgettext("DB: products.Topic.description", """Klar verwenden""")
pgettext("DB: products.Topic.title", """Firefox Klar for iOS""")
pgettext("DB: products.Topic.description", """Privacy browser for iOS""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Everything you need to know to use Firefox Lite.""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Get Started with Firefox for Fire TV""")
pgettext("DB: products.Topic.title", """Pocket Basics""")
pgettext("DB: products.Topic.description", """New to Pocket? Start here.""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """How to use Firefox Reality""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Learn the basics about ScreenshotGo""")
pgettext("DB: products.Topic.title", """Firefox for Fire TV""")
pgettext("DB: products.Topic.description", """Browser for the Amazon Fire TV.""")
pgettext("DB: products.Topic.title", """Install and set up""")
pgettext("DB: products.Topic.description", """Sync your logins across Firefox and your apps.""")
pgettext("DB: products.Topic.title", """Install and update""")
pgettext("DB: products.Topic.description", """Download and install the mobile app on your device.""")
pgettext("DB: products.Topic.title", """Older versions of Firefox for Android""")
pgettext("DB: products.Topic.description", """See articles for an unsupported version of Firefox for Android.""")
pgettext("DB: products.Topic.title", """Get started""")
pgettext("DB: products.Topic.description", """Learn the basics""")
pgettext("DB: products.Topic.title", """Support Forum""")
pgettext("DB: products.Topic.description", """Topic for any articles related to support forum contribution.""")
pgettext("DB: products.Topic.title", """Calling and Contacts""")
pgettext("DB: products.Topic.description", """Learn how to add and manage contacts, as well as make one-to-one or conference calls on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Thimble""")
pgettext("DB: products.Topic.description", """Learn how to create and share your own webpages quickly and easily.""")
pgettext("DB: products.Topic.title", """BadgeKit""")
pgettext("DB: products.Topic.description", """Learn how to create, assess and issue badges""")
pgettext("DB: products.Topic.title", """About Data Sharing""")
pgettext("DB: products.Topic.description", """In order to process or provide our products and services to you, we share your information with the following business partners. These entities are contractually obligated to handle the data in ways that are approved by Mozilla.""")
pgettext("DB: products.Topic.title", """Firefox Klar for Android""")
pgettext("DB: products.Topic.description", """Privacy browser for Android""")
pgettext("DB: products.Topic.title", """Preferences""")
pgettext("DB: products.Topic.description", """Customize Firefox Lite to your desired settings""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox Fire TV""")
pgettext("DB: products.Topic.title", """Pocket for Mobile""")
pgettext("DB: products.Topic.description", """How to use Pocket on your iPhone, iPad, Android or Kobo.""")
pgettext("DB: products.Topic.title", """Troubleshooting""")
pgettext("DB: products.Topic.description", """Fix problems with Firefox Reality""")
pgettext("DB: products.Topic.title", """Firefox for Echo Show""")
pgettext("DB: products.Topic.description", """Browser for the Amazon Echo Show""")
pgettext("DB: products.Topic.title", """Manage settings and logins""")
pgettext("DB: products.Topic.description", """Setting up your device to work with Firefox Lockwise""")
pgettext("DB: products.Topic.title", """Browsing""")
pgettext("DB: products.Topic.description", """Surf and navigate the Web on Firefox Preview""")
pgettext("DB: products.Topic.title", """How do I use Firefox Preview?""")
pgettext("DB: products.Topic.description", """Get help with using features in Firefox Preview.""")
pgettext("DB: products.Topic.title", """Manage account""")
pgettext("DB: products.Topic.description", """How to change your account settings""")
pgettext("DB: products.Topic.title", """Help articles""")
pgettext("DB: products.Topic.description", """Topic for any articles related to the Knowledge Base (help articles) contribution.""")
pgettext("DB: products.Topic.title", """Email and Messages""")
pgettext("DB: products.Topic.description", """Keep in touch with your contacts through email and messaging.""")
pgettext("DB: products.Topic.title", """X-Ray Goggles""")
pgettext("DB: products.Topic.description", """Learn how to inspect the code behind every webpage.""")
pgettext("DB: products.Topic.title", """Get Involved""")
pgettext("DB: products.Topic.description", """Help the Open Badges community""")
pgettext("DB: products.Topic.title", """Managing Your Data""")
pgettext("DB: products.Topic.description", """Learn how to manage your data (including deleting) for specific products or services.""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot problems with Firefox Lite.""")
pgettext("DB: products.Topic.title", """Pocket for your Computer""")
pgettext("DB: products.Topic.description", """Using Pocket on the Web.""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with Firefox Lockwise""")
pgettext("DB: products.Topic.title", """Library""")
pgettext("DB: products.Topic.description", """Manage bookmarks and history""")
pgettext("DB: products.Topic.title", """Services and Subscriptions""")
pgettext("DB: products.Topic.description", """Free and premium privacy offerings""")
pgettext("DB: products.Topic.title", """Localization""")
pgettext("DB: products.Topic.description", """Topic for any articles related to article localization (L10n) contribution.""")
pgettext("DB: products.Topic.title", """Music, Photos and Video""")
pgettext("DB: products.Topic.description", """Take pictures, record videos and listen to music on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Get the most from webmaker.org""")
pgettext("DB: products.Topic.description", """Help or get help on a Webmaker project.""")
pgettext("DB: products.Topic.title", """Earn Badges""")
pgettext("DB: products.Topic.description", """Earn Badges for the skills you learn online and offline""")
pgettext("DB: products.Topic.title", """Sensible Settings""")
pgettext("DB: products.Topic.description", """Give our users actionable and informed choices by informing and educating at the point of collection and providing a choice to opt-out whenever possible. """)
pgettext("DB: products.Topic.title", """Advanced""")
pgettext("DB: products.Topic.description", """Information for Developers and Beta users.""")
pgettext("DB: products.Topic.title", """Sync""")
pgettext("DB: products.Topic.description", """Sync your browsing information across other devices.""")
pgettext("DB: products.Topic.title", """Troubleshoot""")
pgettext("DB: products.Topic.description", """Fix problems with Firefox Accounts""")
pgettext("DB: products.Topic.title", """Social Support""")
pgettext("DB: products.Topic.description", """Topic for any articles related to the Social Support Program.""")
pgettext("DB: products.Topic.title", """Marketplace""")
pgettext("DB: products.Topic.description", """How to download, manage and use your favorite apps on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Events and help for Mentors""")
pgettext("DB: products.Topic.description", """Help teach digital skills and share creative ways of teaching technology.""")
pgettext("DB: products.Topic.title", """Issue Badges""")
pgettext("DB: products.Topic.description", """Issue digital badges to acknowledge new skills and achievements""")
pgettext("DB: products.Topic.title", """Defense in Depth""")
pgettext("DB: products.Topic.description", """Make privacy a key factor in selecting and interacting with partners. """)
pgettext("DB: products.Topic.title", """Mobile Store Support""")
pgettext("DB: products.Topic.description", """Topic for any articles related to the Mobile Store Support contribution.""")
pgettext("DB: products.Topic.title", """Privacy and security""")
pgettext("DB: products.Topic.description", """Keep your information safe with Firefox OS locks, privacy features and more.""")
pgettext("DB: products.Topic.title", """Display Badges""")
pgettext("DB: products.Topic.description", """Display your digital badges on your social networks, job sites and your own website.""")
pgettext("DB: products.Topic.title", """Privacy and security""")
pgettext("DB: products.Topic.description", """Protect your privacy on Firefox Preview.""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """Learn how to configure the Internet connection, display and time on your Firefox OS device.""")
pgettext("DB: products.Topic.title", """Internet and Connections""")
pgettext("DB: products.Topic.description", """Learn more about Wi-Fi, Bluetooth and NFC connections.""")
pgettext("DB: products.Topic.title", """Settings and preferences""")
pgettext("DB: products.Topic.description", """Manage themes and search settings""")
pgettext("DB: products.Topic.title", """Fix problems with Firefox Preview""")
pgettext("DB: products.Topic.description", """Troubleshoot issues with Firefox Preview""")
pgettext("DB: products.Topic.title", """Fix problems""")
pgettext("DB: products.Topic.description", """Learn how to troubleshoot issues on your Firefox OS phone.""")
pgettext("DB: products.Topic.title", """Advanced Settings""")
pgettext("DB: products.Topic.description", """Do more with Firefox Preview""")
pgettext("DB: products.Topic.title", """Get community support""")
pgettext("DB: products.Topic.description", """Get community support""")
pgettext("DB: products.Topic.title", """View all Firefox OS articles""")
pgettext("DB: products.Topic.description", """View a list of all Firefox OS articles""")
pgettext("DB: products.Topic.title", """How does it work?""")
pgettext("DB: products.Topic.description", """Basics to get started with Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Settings""")
pgettext("DB: products.Topic.description", """How to configure and customize Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Problems with websites""")
pgettext("DB: products.Topic.description", """Problems with websites that don't work well in Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Other""")
pgettext("DB: products.Topic.description", """Other questions with Firefox for Windows 8 Touch.""")
pgettext("DB: products.Topic.title", """Working with messages""")
pgettext("DB: products.Topic.description", """Firefox OS SMS & email""")
pgettext("DB: products.Topic.title", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.description", """Procedures to diagnose and fix problems""")
pgettext("DB: products.Topic.title", """[Obsolete] Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """[Obsolete] Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: products.Topic.title", """Mozilla Persona""")
pgettext("DB: products.Topic.description", """Mozilla Persona""")
pgettext("DB: products.Topic.title", """Hot topics""")
pgettext("DB: products.Topic.description", """Hot topics""")
pgettext("DB: kbadge.Badge.title", """2023 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2023.""")
pgettext("DB: kbadge.Badge.title", """2023 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2023.""")
pgettext("DB: kbadge.Badge.title", """2023 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2023.""")
pgettext("DB: kbadge.Badge.title", """2021 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2021.""")
pgettext("DB: kbadge.Badge.title", """2022 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2022.""")
pgettext("DB: kbadge.Badge.title", """2022 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2022.""")
pgettext("DB: kbadge.Badge.title", """2022 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2022.""")
pgettext("DB: kbadge.Badge.title", """2021 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2021.""")
pgettext("DB: kbadge.Badge.title", """2021 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2021.""")
pgettext("DB: kbadge.Badge.title", """2020 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2019.""")
pgettext("DB: kbadge.Badge.title", """2020 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2019.""")
pgettext("DB: kbadge.Badge.title", """2020 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2019.""")
pgettext("DB: kbadge.Badge.title", """2020 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2020.""")
pgettext("DB: kbadge.Badge.title", """2019 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2019.""")
pgettext("DB: kbadge.Badge.title", """2018 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2018.""")
pgettext("DB: kbadge.Badge.title", """2018 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2018.""")
pgettext("DB: kbadge.Badge.title", """2018 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2018.""")
pgettext("DB: kbadge.Badge.title", """2018 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2018.""")
pgettext("DB: kbadge.Badge.title", """2017 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2017.""")
pgettext("DB: kbadge.Badge.title", """2017 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2017.""")
pgettext("DB: kbadge.Badge.title", """2017 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2017.""")
pgettext("DB: kbadge.Badge.title", """2017 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 20 support forum replies during 2017.""")
pgettext("DB: kbadge.Badge.title", """2016 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2016.""")
pgettext("DB: kbadge.Badge.title", """2016 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2016.""")
pgettext("DB: kbadge.Badge.title", """2016 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2016.""")
pgettext("DB: kbadge.Badge.title", """2016 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2016.""")
pgettext("DB: kbadge.Badge.title", """2015 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 30 support forum replies during 2015.""")
pgettext("DB: kbadge.Badge.title", """2015 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 50 Army of Awesome tweets during 2015.""")
pgettext("DB: kbadge.Badge.title", """2015 KB Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved English edits during 2015.""")
pgettext("DB: kbadge.Badge.title", """2015 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2015.""")
pgettext("DB: kbadge.Badge.title", """2014 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2014 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2014 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2014 badge earners for advancing the Mozilla Mission""")
pgettext("DB: kbadge.Badge.title", """2014 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2014 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2014 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2014 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """Firefox 29 Launch Team""")
pgettext("DB: kbadge.Badge.description", """Awarded to support contributors who contributed (KB article documentation, answering Forum Questions, localizing KB article documentation, tweets, etc) to the launch of Firefox 29, thanks! 

Firefox 29 features:

1. Firefox Desktop: Australis new look and feel
AND Firefox Accounts based sync

2. Firefox for Android: Firefox Accounts based sync

MOAR:

https://sumo.etherpad.mozilla.org/sumo-australis-badges""")
pgettext("DB: kbadge.Badge.title", """2008 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2008.""")
pgettext("DB: kbadge.Badge.title", """2009 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """This badge is awarded to contributors with 10 approved translations edits during 2009.""")
pgettext("DB: kbadge.Badge.title", """2012 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2010 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 Army of Awesome Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Army of Awesome 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 50 Army of Awesome tweets.

Congrats to all SUMO Army of Awesome 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2012 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2010 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2010 badge earners for advancing the Mozilla Mission""")
pgettext("DB: kbadge.Badge.title", """2010 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2010 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2010 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2010 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2010 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2011 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2011 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2011 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2011 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2011 badge earners for advancing the Mozilla Mission!
""")
pgettext("DB: kbadge.Badge.title", """2012 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 KB Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO KB 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 10 approved edits of the English SUMO Knowledge Base.

Congrats to all SUMO KB 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2013 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """2013 Support Forum Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO Forum 2013 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2013 in this case: 30 replies in the English SUMO Forum.

Congrats to all SUMO Forum 2013 badge earners for advancing the Mozilla Mission""")
pgettext("DB: kbadge.Badge.title", """2012 L10n Badge""")
pgettext("DB: kbadge.Badge.description", """The SUMO L10n 2012 mini-badge is part of the SUMO series. It represents contribution to SUMO in 2012; in this case: 10 approved translation edits of the SUMO Knowledge Base.

Congrats to all SUMO L10n 2012 badge earners for advancing the Mozilla Mission!""")
pgettext("DB: kbadge.Badge.title", """Kitsune Contributor""")
pgettext("DB: kbadge.Badge.description", """Badge awarded to those who have contributed to the Kitsune code base.""")
