# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 17:54
from __future__ import unicode_literals

from django.db import migrations


def change_locale_bn_bd_and_bn_in_to_bn_forwards(apps, schema_editor):
    Image = apps.get_model('gallery', 'Image')
    Video = apps.get_model('gallery', 'Video')

    Image.objects.all().filter(locale='bn-BD').update(locale='bn')
    # Change bn-IN images to bn
    Image.objects.all().filter(locale='bn-IN').update(locale='bn')

    Video.objects.all().filter(locale='bn-BD').update(locale='bn')
    # Change bn-IN videos to bn
    Video.objects.all().filter(locale='bn-IN').update(locale='bn')


def change_locale_bn_to_bn_bd_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190507_1052'),
    ]

    operations = [
        migrations.RunPython(change_locale_bn_bd_and_bn_in_to_bn_forwards,
                             change_locale_bn_to_bn_bd_backwards)
    ]
