# Generated by Django 2.2.23 on 2021-08-06 09:25

from django.db import migrations
import kitsune.sumo.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200629_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=kitsune.sumo.models.utf8mb3TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=kitsune.sumo.models.utf8mb3CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=kitsune.sumo.models.utf8mb3TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=kitsune.sumo.models.utf8mb3CharField(db_index=True, max_length=255),
        ),
    ]
