# Generated by Django 3.2.11 on 2022-01-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200629_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_draft',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_draft',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
    ]
