# Generated by Django 5.2.14 on 2026-06-22 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0012_alter_image_created_alter_image_updated_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
