# Generated by Django 4.1.7 on 2023-04-18 14:24

from django.db import migrations


def create_ratelimit_bypass_perm(apps, schema_editor):
    # First we get or create the content type.
    ContentType = apps.get_model("contenttypes", "ContentType")
    global_permission_ct, created = ContentType.objects.get_or_create(
        model="global_permission", app_label="sumo"
    )

    # Then we create a permission attached to that content type.
    Permission = apps.get_model("auth", "Permission")
    perm = Permission.objects.create(
        name="Bypass Ratelimits", content_type=global_permission_ct, codename="bypass_ratelimit"
    )


def remove_ratelimit_bypass_perm(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    perm = Permission.objects.filter(codename="bypass_ratelimit").delete()


class Migration(migrations.Migration):
    replaces = [("sumo", "0001_initial"), ("sumo", "0002_initial_data")]

    initial = True

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_ratelimit_bypass_perm,
            reverse_code=remove_ratelimit_bypass_perm,
        )
    ]
