# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 04:42
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.fields import DateTimeField

import pytz


def make_all_dt_aware(apps, schema_editor):
    """Interpolate all fields and make DateTime fields tz naive UTC"""

    PST_TZ = pytz.timezone('US/Pacific')

    for model in apps.get_models():
        print('\nModel: {}'.format(model))
        fields = [f for f in model._meta.get_fields() if isinstance(f, DateTimeField)]
        queryset = model.objects.all()

        migrated_objs = 0
        all_objs = queryset.count()

        for obj in queryset:
            for field in fields:
                naive_value_pst = getattr(obj, field.name)
                if naive_value_pst:
                    aware_value_pst = naive_value_pst.replace(tzinfo=PST_TZ)
                    aware_value_utc = aware_value_pst.astimezone(pytz.UTC)
                    naive_value_utc = aware_value_utc.replace(tzinfo=None)
                    setattr(obj, field.name, naive_value_utc)
            obj.save()

            migrated_objs += 1
            print('Progress: {}%'.format((migrated_objs * 100.0)/all_objs))


class Migration(migrations.Migration):

    dependencies = [
        ('sumo', '0002_initial_data'),
        ('users', '0019_auto_20190917_0422'),
        ('search', '0004_auto_20160106_1033'),
        ('forums', '0001_initial'),
        ('questions', '0010_auto_20190816_1824'),
        ('kbadge', '0003_auto_20190816_1824'),
        ('flagit', '0001_initial'),
        ('wiki', '0011_auto_20190816_1824'),
        ('kbforums', '0001_initial'),
        ('gallery', '0007_auto_20190816_1824'),
        ('customercare', '0001_initial'),
        ('announcements', '0001_initial'),
        ('kitsune_messages', '0001_initial'),
        ('notifications', '0001_initial'),
        ('journal', '0001_initial')
    ]

    operations = [
        migrations.RunPython(make_all_dt_aware),
    ]
