# Generated by Django 5.2.10 on 2026-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationregistration',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='realtimeregistration',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
