# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedobject',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flaggedobject',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam or other unrelated content'), ('language', 'Inappropriate language/dialog'), ('bug_support', 'Misplaced bug report or support request'), ('abuse', 'Abusive content'), ('other', 'Other (please specify)')], max_length=64),
        ),
    ]
