# Generated by Django 4.1.10 on 2023-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flagit", "0001_squashed_0002_auto_20200629_0826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaggedobject",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam or other unrelated content"),
                    ("language", "Inappropriate language/dialog"),
                    ("bug_support", "Misplaced bug report or support request"),
                    ("abuse", "Abusive content"),
                    ("other", "Other (please specify)"),
                ],
                default="spam",
                max_length=64,
            ),
        ),
    ]
