# Generated by Django 2.2.23 on 2021-08-06 09:25

from django.db import migrations
import kitsune.sumo.models


class Migration(migrations.Migration):

    dependencies = [
        ('flagit', '0002_auto_20200629_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedobject',
            name='notes',
            field=kitsune.sumo.models.utf8mb3TextField(blank=True, default=''),
        ),
    ]
