# Generated by Django 4.2.16 on 2024-12-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flagit", "0003_alter_flaggedobject_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaggedobject",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam or other unrelated content"),
                    ("language", "Inappropriate language/dialog"),
                    ("abuse", "Abusive content"),
                    ("other", "Other (please specify)"),
                ],
                default="spam",
                max_length=64,
            ),
        ),
    ]
