# Generated by Django 5.2.10 on 2026-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagit', '0005_flaggedobject_assigned_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedobject',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flaggedobject',
            name='handled',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
