apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sumo-prod-web
  namespace: sumo-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sumo-prod-web
  minReplicas: 25
  maxReplicas: 50
  targetCPUUtilizationPercentage: 80
