version: '3.4'
services:
  base:
    build:
        context: .
        cache_from:
            - mozmeao/kitsune:base-latest
        dockerfile: docker/dockerfiles/base
    image: mozmeao/kitsune:base-latest

  dev:
    build:
        context: .
        cache_from:
            - mozmeao/kitsune:base-dev-latest
        dockerfile: docker/dockerfiles/base-dev
    image: mozmeao/kitsune:base-dev-latest
