version: '3.4'
services:
  web:
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app:cached

  mariadb:
    volumes:
      - mysqlvolume:/var/lib/mysql

volumes:
    mysqlvolume:
