version: '3.4'
services:
  web:
    command: ./manage.py runserver 0.0.0.0:8000
    env_file: .env-dist
    volumes:
      - ./:/app

  mariadb:
    volumes:
      - mysqlvolume:/var/lib/mysql

volumes:
    mysqlvolume:
